### PR TITLE
[luci-interpreter] Add accessors to individual kernel inputs / outputs

### PR DESCRIPTION
**Pull request by s-barannikov**
* Add getters for kernel input / output tensors.
* Remove boilerplate code.

ONE-DCO-1.0-Signed-off-by: Sergei Barannikov <s.barannikov@samsung.com>

### CODE REVIEW

**Comment by s-barannikov** [comment]
This is a semi-automated refactoring, so I don't expect it to be reviewed thoroughly.

**Comment by seanshpark** [comment]
@s-barannikov this PR made some critical build errors.
Today we are planning to make a release branch and this change block.
If you fix this in an hour or so, I'll wait. If not, we may have to revert this change.

**Comment by s-barannikov** [comment]
@seanshpark 
Sorry for this. I forgot to tell that this PR conflicts with others which add new operators to the interpreter.

**Comment by seanshpark** [comment]
It's OK now :) Please post new PR for this change.

**Comment by s-barannikov** [comment]
Recreated as #3330.

**Pull request merged**
