### PR TITLE
[onert/util] Introduce MDTable write type of ChromeTracingObserver

### PR DESCRIPTION
**Pull request by YongseopKim**
Introduce new write type of ChromeTracingObserver - MD Table

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
for #3578

**Comment by YongseopKim** [comment]
To enable/test this, fix `runtime/onert/core/src/util/EventRecorder.h` like below
```c++
  //WriteFormat _write_format{WriteFormat::SNPE_BENCHMARK};
  WriteFormat _write_format{WriteFormat::MD_TABLE};
```

**Comment by YongseopKim** [comment]
@wateret could you review this?

**Review by wateret — APPROVED** [review]
LGTM

**Comment by wateret** [comment]
@YongseopKim Are you going to work on writing all 3 formats at once?

**Comment by YongseopKim** [comment]
@wateret yes, I'm gonna do it soon.

**Pull request merged**
