### PR TITLE
[luci] Revise QuantizeDequantizeWeightsPass to use iterate

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise QuantizeDequantizeWeightsPass to use
iterate_per_channel method to reduce duplicate codes.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6053, from #6054, next of #6081

To ignore indentation, 
image

**Comment by llFreetimell** [comment]
It would be better to use `// clang-format off` from next time.

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
