### PR TITLE
[onert] Fix tizen x86_64 build fail

### PR DESCRIPTION
**Pull request by chunseoklee**
- Disable tensorflow-lite build on tizen x86_64

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by chunseoklee** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by chunseoklee** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by chunseoklee** [comment]
@nnfw-bot test cross-runtime-test-release

**Review by glistening — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]

**Pull request merged**
