### PR TITLE
[mpqsolver] Fix warnings

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit fixes compiler warnings in mpqsolver.

Draft: https://github.com/Samsung/ONE/pull/10191
Related to: https://github.com/Samsung/ONE/issues/10154

Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Review by jinevening — APPROVED** [review]
LGTM

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Review by staddy — APPROVED** [review]
LGTM

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@stamalakhov and for new members, please check https://github.com/Samsung/ONE/wiki/ONE-Developer's-Certificate-of-Origin and post according PRs.

**Comment by stamalakhov** [comment]
> @stamalakhov and for new members, please check https://github.com/Samsung/ONE/wiki/ONE-Developer's-Certificate-of-Origin and post according PRs.

Understood. I'll try to post next PRs according to the link above. Thank you.

**Pull request merged**
