### PR TITLE
[visq] Improve error message

### PR DESCRIPTION
**Pull request by jinevening**
This improves error message from subprocess.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Before

```
build/release.install/bin/visq -f ~/tmp/palm_detection_lite/palm_detection_lite.opt.circle -q ~/tmp/palm_detection_lite/palm_detection_lite.q8.circle -d ~/tmp/palm_detection_lite/dataset_192.3.h5 --mpeir_output ~/tmp/palm_detection_lite/palm_detection_lite.opt.visq.json --dump_dot_graph
Error raised while running the below command
/home/hjj/ONE/build/release.install/bin/dalgona --input_model /home/hjj/tmp/palm_detection_lite/palm_detection_lite.opt.circle --analysis /home/hjj/ONE/build/release.install/bin/visqlib/DumpFP32FM.py --input_data /home/hjj/tmp/palm_detection_lite/dataset_192.3.h5 --analysis_args /tmp/tmpo5f3mi1l
visq: CalledProcessError: Command '['/home/hjj/ONE/build/release.install/bin/dalgona', '--input_model', '/home/hjj/tmp/palm_detection_lite/palm_detection_lite.opt.circle', '--analysis', '/home/hjj/ONE/build/release.install/bin/visqlib/DumpFP32FM.py', '--input_data', '/home/hjj/tmp/palm_detection_lite/dataset_192.3.h5', '--analysis_args', '/tmp/tmpo5f3mi1l']' returned non-zero exit status 255.
```

After

```
build/release.install/bin/visq -f ~/tmp/palm_detection_lite/palm_detection_lite.opt.circle -q ~/tmp/palm_detection_lite/palm_detection_lite.q8.circle -d ~/tmp/palm_detection_lite/dataset_192.3.h5 --mpeir_output ~/tmp/palm_detection_lite/palm_detection_lite.opt.visq.json --dump_dot_graph
Error raised while running the below command
/home/hjj/ONE/build/release.install/bin/dalgona --input_model /home/hjj/tmp/palm_detection_lite/palm_detection_lite.opt.circle --analysis /home/hjj/ONE/build/release.install/bin/visqlib/DumpFP32FM.py --input_data /home/hjj/tmp/palm_detection_lite/dataset_192.3.h5 --analysis_args /tmp/tmpo5f3mi1l
ERROR: OSError: [Errno 36] File name too long: '/tmp/tmpo5f3mi1l/0/l_batch_normalization_FusedBatchNormV3_model_1_model_depthwise_conv2d_3_depthwise_model_1_model_conv2d_Conv2D1;depthwise_3;Conv2D;model_1_model_batch_normalization_FusedBatchNormV3_model_1_model_depthwise_conv2d_3_depthwise_model_1_model_conv2d_Conv2D1_y1.npy'

At:
  /home/hjj/.local/lib/python3.8/site-packages/numpy/lib/npyio.py(498): save
  <__array_function__ internals>(180): save
  /home/hjj/ONE/build/release.install/bin/visqlib/DumpFP32FM.py(47): DefaultOpPost


visq: CalledProcessError: Command '['/home/hjj/ONE/build/release.install/bin/dalgona', '--input_model', '/home/hjj/tmp/palm_detection_lite/palm_detection_lite.opt.circle', '--analysis', '/home/hjj/ONE/build/release.install/bin/visqlib/DumpFP32FM.py', '--input_data', '/home/hjj/tmp/palm_detection_lite/dataset_192.3.h5', '--analysis_args', '/tmp/tmpo5f3mi1l']' returned non-zero exit status 255.
```

This PR prints contents of stderr.

**Review by mhs4670go — APPROVED** [review]
LGTM. 

@jinevening 
Printing `e.stdout` as well is not necessary?

**Comment by jinevening** [comment]
> Printing e.stdout as well is not necessary?

stdout is not printed because it has too many lines of logs. For example,

```
Running 0th data
Running 1th data
....
Running 999th data
```

Let's print it if necessary.

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
