### PR TITLE
[github] Enable onecc test workflow trigger on push evnet

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit adds the onecc workflow trigger to run on commit push.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
Just curiosity, runners can cover workload?

**Comment by hseok-oh** [comment]
> Just curiosity, runners can cover workload?

Fortunately, yes. 
Please refer this: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Pull request merged**
