### PR TITLE
DRAFT Compiler FE reduce LOC-Class

### PR DESCRIPTION
**Pull request by seanshpark**
on-going draft to reduce LOC-class from our software analysis tool report

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #2843

**Comment by lemmaa** [comment]
FYI, https://github.sec.samsung.net/RS7-Architectural-Refactoring/SAM-Tools/wiki/Metrics-in-SAM#lines-of-code-loc

**Comment by seanshpark** [comment]
Seems that experimental change #2904 works: Value decreased from 975 to 952.
We can apply this pattern to all other Nodes.

**Comment by seanshpark** [comment]
done this for now

**Pull request closed without merging**
