### PR TITLE
[luci] Revise NCHWToNHWCPass Add to support scalar beta

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise NCHWToNHWCPass to support scalar beta to CircleAdd node.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #7308, from draft #7309

**Comment by jinevening** [comment]
Code look ok (there may be a better structure with simpler control flow, but it will require a large change..).

Can you update the comment of `is_NCHW_with_const` to reflect this change?

**Comment by seanshpark** [comment]
> Can you update the comment of is_NCHW_with_const to reflect this change?

Maybe `TODO: simplify support for multiple ranks` ?

**Comment by jinevening** [comment]
I meant the comment in the function declaration.

```cpp
// We assume ADD with const input is NCHW if,
// Input shape: (N, C, H, W)
// Output shape: (N, C, H, W)
// 1. Const shape is (1, C, 1, 1)
// 2. Input, Output, Const have the same C.
```

1 should be changed to something like
`// 1. Const shape is (1, C, 1, 1) or a scalar (1)`

**Review by jinevening — APPROVED** [review]
LGTM Thank you

**Pull request merged**
