### PR TITLE
[one-cmds] Handle already applied patch in prepare-venv

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise one-prepare-venv to handle already applied patch for
onnx-tf package.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6986

**Comment by seanshpark** [comment]
@mhs4670go , could you please release new debian `dev` package after this lands?

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@hseok-oh Please run publish jobs after this PR merged.

**Pull request merged**
