### PR TITLE
[onert] Introduce SoftMaxLayer in train backend

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit introduces SoftMaxLayer in train backend.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Draft: #11742

### CODE REVIEW

**Comment by hseok-oh** [comment]
```
[2023-10-26T09:56:54.404Z] /opt/jenkins_agent/workspace/nnfw/master/pr-onert-cross-debug/runtime/onert/backend/train/ops/SoftMaxLayer.cc: In member function ‘virtual void onert::backend::train::ops::SoftMaxLayer::backward()’:
[2023-10-26T09:56:54.404Z] /opt/jenkins_agent/workspace/nnfw/master/pr-onert-cross-debug/runtime/onert/backend/train/ops/SoftMaxLayer.cc:52:40: error: ‘const onert::backend::IPortableTensor* onert::backend::cpu::ops::SoftMaxLayer::_input’ is private within this context
[2023-10-26T09:56:54.404Z]    52 |   assert(_deriv_output->data_type() == _input->data_type());
[2023-10-26T09:56:54.404Z]       |                                        ^~~~~~
```

**Comment by jyoungyun** [comment]
@hseok-oh  Thank you! I updated this PR. :)

**Review by ragmani — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
