### PR TITLE
[one-cmds] Enable fuse_mul_with_conv

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit enables fuse_mul_with_conv option for one-cmds optimize.

Running onecc for the following `.cfg` file:
```
[onecc]
one-optimize=True

[one-optimize]
input_path=/home/stanislav/repos/WorkSpaces/fuse_mul_conv/original.circle
output_path=/home/stanislav/repos/WorkSpaces/fuse_mul_conv/original_opt_new.circle
fuse_mul_with_conv=True
```
with original model:
image

produced:
image

Please see attachment:
[fuse_mul_with_conv_results.zip](https://github.com/Samsung/ONE/files/13388113/fuse_mul_with_conv_results.zip)

Draft: https://github.com/Samsung/ONE/pull/11991
Related: https://github.com/Samsung/ONE/issues/11897

ONE-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Can you add this to O1 group?

**Review by seanshpark — DISMISSED** [review]
LGTM

**Comment by stamalakhov** [comment]
> Can you add this to O1 group?

Ok.

**Comment by stamalakhov** [comment]
> Can you add this to O1 group?

done.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
