### PR TITLE
[luci] Set node id at luci/import

### PR DESCRIPTION
**Pull request by llFreetimell**
Related Issue : #5794 
Draft : #5821 

For profiling, each node sometimes should have unique node id.
This commit will set unique node id using operator index at `luci/import` step.

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by cgbahk — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
@llFreetimell , how about revise `void GraphBuilder::build()` to return new `CircleNode *` and set the ID in `convert_graph()` after it gets the node.

**Comment by llFreetimell** [comment]
@seanshpark
Suggestion itself looks good but it may require a lot of change. 
(When I searched briefly, some of operations like `CircleIf`, `CircleSplit`, etc are implemented with `void GraphBuilder::build()`, not with `CircleNode *GraphBuilder::build_node()`)
So how about going as it is and revise it in the near future? :)

**Comment by seanshpark** [comment]
> So how about going as it is and revise it in the near future? :)

OK, there are four. I think it's not a huge change.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> (When I searched briefly, some of operations like CircleIf, CircleSplit, etc are implemented with void GraphBuilder::build(), not with CircleNode *GraphBuilder::build_node())

Have you checked with `CircleSplit` and others having it's own `CircleSplitGraphBuilder::build()` ?

**Comment by seanshpark** [comment]
As If, Split and While are not our current interest as of now so this code may work. But strictly speaking this change is incorrect.
You have two(or more?) choices
1. Add this kind of change also to If, Split and While, and then do revision
1. Revise `void GraphBuilder::build()` to `CircleNode *GraphBuilder::build()` and then set NodeID inside `convert_graph()`

**Comment by llFreetimell** [comment]
I will try option 2 first, and there is no big problem, I will go with option 2 :)
Thanks for sharp review :D

**Comment by llFreetimell** [comment]
It is rebased, PTAL :)

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by cgbahk — APPROVED** [review]
LGTM

**Pull request merged**
