### PR TITLE
[res/TensorFlowLiteRecipes] Add Quantization_U8_000

### PR DESCRIPTION
**Pull request by underflow101**
Parent Issue: #1880 
Fired Issue: #3399 

This commit adds recipes for Quantization_U8_000. (Derived from SOS Mine Project)

Please review this Work in Progress codes @seanshpark , @jinevening 
(Since this is my first PR, it will be greatful for any advice for literally anything.)
I'll be happy to get feedback and change to make improvement.

Thank you.
 
Signed-off-by: underflow101 <ikarus125@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@underflow101 , thank you for your contribution!

I must say I'm sorry for any operator in the table is OK but actually we need to add operators that are already working with Float32. `Quantization` currently is not enable in frontend _luci_ module so we cannot test the recipe is working or not.

Can you please pick another operator that exist in `res/TensorFlowLiteRecipes` but has no `---_U8_---`, like `AveragePool2D_000` ?

I'll update the table.

**Comment by seanshpark** [comment]
Tip for posting a PR
- you sent the PR with your `master` branch` --> it would be better to make another branch. for example
   ```
   git branch -b res_work_for_u8_add
   ```
- work on the codes
- send branch
   ```
   git push --set-upstream origin res_work_for_u8_add
   ```
- and when something needs update, apply and post again
   ```
   git add [the file updared]
   # or
   git add .

   git commit -m "fix something"
   git push
   ```

**Comment by underflow101** [comment]
@seanshpark , thanks for your advice.
I'll work on AveragePool2D_000 first then.
From now on, I will work on another branch as you have instructed above.

Thank you.

P.S. Should I Close this PR?

**Comment by seanshpark** [comment]
> P.S. Should I Close this PR?

Yes :)

**Pull request closed without merging**
