### PR TITLE
[onert] Replace SGD kernel with the optimized kernel

### PR DESCRIPTION
**Pull request by ragmani**
This commit replaces SGD kernel with the optimized kernel.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
@jyoungyun Could you check if your model works well with this PR?

**Comment by jyoungyun** [comment]
> @jyoungyun Could you check if your model works well with this PR?

I tested this PR and I got a great result. :)

This is original test result.
```
$ ./Product/out/bin/onert_train --modelfile ../Personal/models/mnist_keras/mnist_keras/mnist_keras.circle --load_input:raw ../Personal/models/data/fashion_mnist/train.input.1000.bin --load_expected:raw ../Personal/models/data/fashion_mnist/train.output.1000.bin --data_length 1000 --learning_rate 0.01 --epoch 5 
Model Expected Filename ../Personal/models/data/fashion_mnist/train.output.1000.bin
Model Input Filename ../Personal/models/data/fashion_mnist/train.input.1000.bin
Model Filename ../Personal/models/mnist_keras/mnist_keras/mnist_keras.circle
Epoch 1/5 - 3.167ms/step - loss: [0] 8.2802
Epoch 2/5 - 3.125ms/step - loss: [0] 1.6288
Epoch 3/5 - 3.199ms/step - loss: [0] 1.0257
Epoch 4/5 - 3.121ms/step - loss: [0] 0.7466
Epoch 5/5 - 3.144ms/step - loss: [0] 0.5897
===================================
MODEL_LOAD   takes 0.349 ms
PREPARE      takes 1.652 ms
EXECUTE      takes 490.541 ms
- MEAN     :  490.541 ms
- MAX      :  490.541 ms
- MIN      :  490.541 ms
- GEOMEAN  :  490.541 ms
```

And it is this PR's result. 👍 
```
$ ./Product/out/bin/onert_train --modelfile ../Personal/models/mnist_keras/mnist_keras/mnist_keras.circle --load_input:raw ../Personal/models/data/fashion_mnist/train.input.1000.bin --load_expected:raw ../Personal/models/data/fashion_mnist/train.output.1000.bin --data_length 1000 --learning_rate 0.01 --epoch 5 
Model Expected Filename ../Personal/models/data/fashion_mnist/train.output.1000.bin
Model Input Filename ../Personal/models/data/fashion_mnist/train.input.1000.bin
Model Filename ../Personal/models/mnist_keras/mnist_keras/mnist_keras.circle
Epoch 1/5 - 0.701ms/step - loss: [0] 8.2802
Epoch 2/5 - 0.664ms/step - loss: [0] 1.6288
Epoch 3/5 - 0.651ms/step - loss: [0] 1.0257
Epoch 4/5 - 0.654ms/step - loss: [0] 0.7466
Epoch 5/5 - 0.658ms/step - loss: [0] 0.5897
===================================
MODEL_LOAD   takes 0.297 ms
PREPARE      takes 1.364 ms
EXECUTE      takes 105.159 ms
- MEAN     :  105.159 ms
- MAX      :  105.159 ms
- MIN      :  105.159 ms
- GEOMEAN  :  105.159 ms
===================================
```

**Comment by ragmani** [comment]
@jyoungyun Thanks for sharing your results.

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
