### PR TITLE
[infra] Add pics to compiler_modules.sh

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit updates compiler_modules.sh to add "pics" used by "pota-quantization-value-test".

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
It will resolve coverage test failure.

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
