### PR TITLE
[circledump] Fix typo in descriptor

### PR DESCRIPTION
**Pull request by yunjayh**
This commit fixes typo in descriptor.

ONE-DCO-1.0-Signed-off-by: yunjayh <yunjayh@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Please split PR for tfldump and circledump, we currently have a rule that each PR should contain one module of `compiler/*`

**Comment by yunjayh** [comment]
> Please split PR for tfldump and circledump, we currently have a rule that each PR should contain one module of `compiler/*`

Fixed to contain changes of `circledump` only! I changed the commit title and message too.

**Comment by seanshpark** [comment]
About the title, you only need to use like `[circledump]` without the `compiler` :)

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Pull request merged**
