### PR TITLE
[onert] Remove OpSequence

### PR DESCRIPTION
**Pull request by wateret**
This commit removes `ir::Opsequence` and change the implementation to
be every operation has lower info. This is similar to when
`OPSEQ_MAX_NODE` is 1. Here are details:

- Remove `ir::OpSequence`
- Change `OpSequenceLowerInfo` to `OperationLowerInfo` - every operation
  has LowerInfo since there is no OpSequence
- Introduce `_has_dynamic_tensor_map` as an alternative for OpSequence
- NOTE Assumes one graph can have only one type of tensor layout

By doing this, Implementation of many things(especially LoweredGraph
passes) are much easier with (almost) no disadvantage.

ONE-DCO-1.0-Signed-off-by: Hanjoung Lee <hanjoung.lee@samsung.com>

### CODE REVIEW

**Comment by wateret** [comment]
Sorry about the large diff, but as it is removing a class that is used widely, it is hard to separate.

**Comment by wateret** [comment]
Draft: #5557

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Review by YongseopKim — APPROVED** [review]
LGTM

**Pull request merged**
