### PR TITLE
[DRAFT] [luci-interpreter] Introduce PAL in luci-interpreter

### PR DESCRIPTION
**Pull request by binarman**
This commit introduces basic HAL to hide system-specific
code, like pthreads.

related issue: #6302

Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by binarman** [comment]
+cc @SlavikMIPT @Bronnikoff

**Comment by seanshpark** [comment]
As I know, `HAL: Hardware Adaptation Layer.`
Is this about hardware? I understand this is about kernels...

**Comment by binarman** [comment]
@seanshpark 

> As I know, HAL: Hardware Adaptation Layer.
Is this about hardware? I understand this is about kernels...

Yes, HAL stands for "Hardware Abstraction/Adaptation Layer".

However this PR is not about hardware, but **platform** (Linux, Windows, bare metal, etc.)
I did not use PAL term, because I did not know that it exists :slightly_smiling_face:

Me, @SlavikMIPT and @Bronnikoff had a discussion how to enable luci-interpreter on MCUs(#6302) 

This PR demonstrates a way to specialize luci-interpreter code depending on operating system(or bare metal).

**Comment by seanshpark** [comment]
> However this PR is not about hardware, but platform (Linux, Windows, bare metal, etc.)
I did not use PAL term, because I did not know that it exists 

`PAL` looks OK :)

**Pull request closed without merging**
