### PR TITLE
[circle2circle] Add Dredd test for Issue_13863

### PR DESCRIPTION
**Pull request by Hanjin-Choi**
This commit adds a dredd_test for Issue_13863.

Related : https://github.com/Samsung/ONE/issues/13863
Draft : https://github.com/Samsung/ONE/pull/14051

ONE-DCO-1.0-Signed-off-by: HanJin Choi hanjin4647@gmail.com

### CODE REVIEW

**Review by zetwhite — APPROVED** [review]
LGTM :+1:

**Review by jinevening — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by shs-park — COMMENTED** [review]
👍

**Pull request merged**
