### PR TITLE
[onert] Pass subgraph index to ExecutionObservers

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
This passes subgraph index to ExecutionObservers, which will be later
used to organize profiling information.

Parent issue: #4901
Draft: #4903

Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Comment by hyunsik-yoon** [comment]
CI console output is as follows.

<details>

image

</details>

I guess this is error while running with Parallel executor and acl_cl backend....
I tried the following but they were all passed.
```
odroid@odroid:~/work/3/ONE$ EXECUTOR=Parallel BACKENDS=acl_cl ./Product/out/test/onert-test verify-tflite --ignoremd5 --api=nnapi --list=Product/out/test/list/frameworktest_list.armv7l.acl_cl.txt --reportdir=report/acl_cl/trace
```
and

```
odroid@odroid:~/work/3/ONE$ EXECUTOR=Parallel BACKENDS=acl_cl ./Product/out/test/onert-test verify-tflite --ignoremd5 --api=nnapi --list=Product/out/test/list/tflite_loader_list.armv7l.txt --reportdir=report/acl_cl/trace
```

Could someone let me know how to reproduce?

**Comment by hyunsik-yoon** [comment]
@nnfw-bot test all

**Comment by hyunsik-yoon** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by hyunsik-yoon** [comment]
CI error was as follows:

<details>

image

</details>


I tried to reproduce on my local device but all test have passed without error. Can anyone help me to reproduce this?

- Run on Odroid XU4
- Tested with Release and also Debug build
- With the following command on XU4

```
$ ./infra/scripts/test_ubuntu_runtime.sh --backend acl_cl --tflite-loader
```

**Comment by hseok-oh** [comment]
Test acl-cl backend:
`./infra/scripts/test_ubuntu_runtime.sh --backend acl_cl --linear-only --tflite-loader`

TFLite loader only:
`BACKENDS=acl_cl ./Product/out/test/onert-test verify-tflite --api=loader --list=Product/out/test/list/tflite_loader_list.armv7l.txt`

Model file (add/1D) by test binary:
`BACKENDS=acl_cl ./Product/out/bin/tflite_loader_test_tool ./Product/out/test/models/cache/add_test1.tflite`

**Comment by hyunsik-yoon** [comment]
@hseok-oh 
Thanks, very helpful to narrow down the problem!

**Comment by hyunsik-yoon** [comment]
PTAL

**Comment by hyunsik-yoon** [comment]
@wateret PTAL~

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
