### PR TITLE
[debian] Remove deprecated files

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit removes deprecated files from install script.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by seanshpark** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Pull request merged**
