### PR TITLE
[armcl-ex] Add copyright to arg_min_max_ex.cl

### PR DESCRIPTION
**Pull request by hseok-oh**
Add copyright to arg_min_max_ex.cl

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dr-venkman PTAL

**Comment by hseok-oh** [comment]
@dr-venkman PTAL

**Comment by hseok-oh** [comment]
PTAL

**Review by dr-venkman — APPROVED** [review]
Thanks for adding the copyright, I must have missed it out. LGTM.

**Pull request merged**
