### PR TITLE
[luci] Support CSE on Tranpose Op

### PR DESCRIPTION
**Pull request by jinevening**
This supports CSE on Transpose Op.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/11726
Draft PR: https://github.com/Samsung/ONE/pull/11869

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
jammy failed with `CommonSubExpressionEliminationTest.Transpose_NEG`
```
[2023-11-06T07:53:14.583Z] [ RUN      ] CommonSubExpressionEliminationTest.Transpose_NEG
[2023-11-06T07:53:14.583Z] 
[2023-11-06T07:53:14.583Z]         Start  86: luci_profile_test
```

**Comment by seanshpark** [comment]
check again
@nnfw-bot test nncc-jammy-debug

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-jammy-debug 

check again

**Comment by seanshpark** [comment]
Same failure
```
[2023-11-06T08:52:22.265Z] [ RUN      ] CommonSubExpressionEliminationTest.Transpose_NEG
[2023-11-06T08:52:22.265Z] 
[2023-11-06T08:52:22.265Z]         Start  86: luci_profile_test
```

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
