### PR TITLE
[one-cmds] Add rawdata2hdf5 to one-cmds

### PR DESCRIPTION
**Pull request by jinevening**
This adds rawdata2hdf5 to one-cmds

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: #4944

### CODE REVIEW

**Comment by jinevening** [comment]
**To reviewers**: Pillow is an image processing library, which is used to test `rawdata2hdf5`.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
