### PR TITLE
[circle-partitioner] Add readme descriptions

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise readme with descriptions about how circle-partitioner works.

ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6230

**Comment by seanshpark** [comment]
@nnfw-bot test all

**Comment by seanshpark** [comment]
@nnfw-bot test all

**Comment by seanshpark** [comment]
`pr-nncc-debug` and `release` is working but the indicators are wrong cause of timing...

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
