### PR TITLE
[onert] Introduce TrainableFnSequence

### PR DESCRIPTION
**Pull request by ragmani**
This commit introduces TrainableFnSequence that has trainable functions.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM. (optional) There are a lot of Trainable... What about specifying it is sequence of Trainable Functions by `TrainableFnSequence`?

**Comment by ragmani** [comment]
> There are a lot of Trainable... What about specifying it is sequence of Trainable Functions by TrainableFnSequence?

Feel free to change names if you have a better name.

**Comment by ragmani** [comment]
I changed the name to TrainableFnSequence.
\cc @jyoungyun

**Review by glistening — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
