### PR TITLE
[debian] Relocate dh_install command

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit relocates dh_install command. `dh_install` should be run at the end.

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
