### PR TITLE
[infra] Revise to include compile flags

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise CMakeLists to include compilation flags depending on target platform.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #8379, from draft #8407

**Review by hyunsik-yoon — DISMISSED** [review]

**Comment by seanshpark** [comment]
> 18:50:28 CMake Error at cmake/ApplyCompileFlags.cmake:13 (include):
18:50:28   include could not find load file:
18:50:28 
18:50:28     /opt/jenkins_slave/workspace/nnfw/master/pr-nncc-debug@2/infra/nncc/cmake/buildtool/config/config_x86_64-linux.cmake
18:50:28 Call Stack (most recent call first):
18:50:28   CMakeLists.txt:166 (include)

**Comment by seanshpark** [comment]
I think I need to add `onfig_x86_64-linux.cmake` -_-;;;

**Comment by seanshpark** [comment]
PTAL

**Review by hyunsik-yoon — APPROVED** [review]

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
ping @chunseoklee

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
