### PR TITLE
[one-cmds] Add missing optimization options to How-to doc

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit will add missing optimization options to how-to doc of `one-cmds`.

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
FYI, someday, I'll make options list file and doc will refer to these file for convenience.

**Review by jinevening — APPROVED** [review]
LGTM

**Review by seanshpark — DISMISSED** [review]
LGTM thank you!

**Review by struss — DISMISSED** [review]
LGTM

**Comment by llFreetimell** [comment]
Conflict resolved.... -_-;;

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by struss — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
