### PR TITLE
[quantizer] Add tests for QuantizePreCheckerPass

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This commit adds some tests for QuantizePreCheckerPass.

from https://github.com/Samsung/ONE/pull/8606#issuecomment-1063797186

for https://github.com/Samsung/ONE/issues/8580

ONE-DCO-1.0-Signed-off-by: Artem Balyshev a.balyshev@partner.samsung.com

### CODE REVIEW

**Comment by BalyshevArtem** [comment]
This PR should be rebased after #8606 will be merged.

**Comment by seanshpark** [comment]
This test passes without #8606. Is this test valid?

**Review by jinevening — APPROVED** [review]
Code looks good to me. Let's wait until #8606 is landed.

**Comment by jinevening** [comment]
> This test passes without https://github.com/Samsung/ONE/pull/8606. Is this test valid?

It seems that debug_test and release_test did not run for this PR (commit message and format check was done).

**Comment by seanshpark** [comment]
I'll check the test is valid (that should fail)

**Comment by seanshpark** [comment]
> 09:51:47 /opt/jenkins_slave/workspace/nnfw/master/pr-nncc-debug/compiler/luci/pass/src/QuantizePreCheckerPass.test.cpp:17:10: fatal error: luci/Pass/QuantizePreCheckerPass.h: No such file or directory
09:51:47  #include "luci/Pass/QuantizePreCheckerPass.h"
09:51:47           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
09:51:47 compilation terminated.

Well... compile itself fails...

**Review by jinevening — APPROVED** [review]
LGTM Thank you

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
