### PR TITLE
[DRAFT] Rename MaxPoolWithArgMax

### PR DESCRIPTION
**Pull request by Bronnikoff**
This draft renames `MaxPoolWithArgMax` to `MaxPoolWithArgmax`.

ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov <max120199@gmail.com>

------------------------

For: #7306

### CODE REVIEW

**Comment by Bronnikoff** [comment]
In order to not break build of nncc during applying this changes, we need to:

1. Temporary exclude `MaxPoolWithArgMax_00*` recipes from *res/TensorFlowLiteRecipes/* folder.
2. Apply changes in *tflchef*
3. Apply changes in *common-artifacts*
4. Return renamed recipes back to  *res/TensorFlowLiteRecipes/* folder.

So, this draft divided to corresponding commits, which applies renaming step-by-step.

**Comment by Bronnikoff** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by Bronnikoff** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by Bronnikoff** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by binarman** [comment]
I don't want to change history of recipes, so I want to change original plan a little:

>1. Temporary exclude MaxPoolWithArgMax_00* recipes from res/TensorFlowLiteRecipes/ folder.
>2. Apply changes in tflchef
>3. Apply changes in common-artifacts
>4. Return renamed recipes back to res/TensorFlowLiteRecipes/ folder.

1. Support both variants of tests in tflchef
2. Disable new tests in common-artifacts
3. Fix resources
4. Apply changes in tflchef
5. Cleanup common-artifacts (remove old names)

**Comment by binarman** [comment]
Everything is merged, closing

**Pull request closed without merging**
