### PR TITLE
[luci] Add CircleReader data_format method

### PR DESCRIPTION
**Pull request by dayo09**
This commit is to add a CircleReader interface getting `data_format`.

ONE-DCO-1.0-Signed-off-by: dayo09 <dayg502@gmail.com>

### CODE REVIEW

**Review by seanshpark — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
It would be better to be specific for the title like `[luci] Add CircleReader data_format method`

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Comment by dayo09** [comment]
@seanshpark @llFreetimell I have changed the title. PTAL!

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Pull request merged**
