### PR TITLE
[luci-value-py-test] Enable SelectV2

### PR DESCRIPTION
**Pull request by ragmani**
This commit enables SelectV2 Op value test.

ONE-DCO-1.0-Signed-off-by: ragmani ragmani0216@gmail.com

---

For #12148

### CODE REVIEW

**Comment by mhs4670go** [comment]
Could you apply this change in the `luci-value-py-test`? `luci-value-test` module has been deprecated.

**Comment by ragmani** [comment]
> Could you apply this change in the luci-value-py-test? luci-value-test module has been deprecated.

Is the same way as `luci-value-test` to enable tests?

**Comment by ragmani** [comment]
> And can I see the issue that luci-value-test has been deprecated. I found the issue https://github.com/Samsung/ONE/issues/12071, but couldn't find any related comment.

I heard from @mhs4670go offline that compiler project is deprecated if `exclude.me` file exists in the project.

**Comment by mhs4670go** [comment]
> Is the same way as `luci-value-test` to enable tests? 

Yeah, you can apply the change the way `luci-value-test` does. Just remove the sharp sign from the below codes.
https://github.com/Samsung/ONE/blob/be49160015d223839d4032e8edc6efa0f860f540/compiler/luci-value-py-test/test.lst#L142-L144

> And can I see the issue that `luci-value-test` has been deprecated. I found the issue #12071, but couldn't find any related comment.

https://github.com/Samsung/ONE/pull/12367#issuecomment-1869474779

**Comment by mhs4670go** [comment]
You can modify the commit title, too. `luci-value-test` -> `luci-value-py-test`.

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Review by mhs4670go — APPROVED** [review]

**Pull request merged**
