### PR TITLE
[recipe] Add recipe for Gather/SparceToDense_AddV2/Cast pattern

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This commit adds recipe for Gather/SparceToDense_AddV2/Cast pattern.

Draft: https://github.com/Samsung/ONE/pull/8674
for https://github.com/Samsung/ONE/issues/8375#issuecomment-1070126309

ONE-DCO-1.0-Signed-off-by: Artem Balyshev a.balyshev@partner.samsung.com

### CODE REVIEW

**Comment by BalyshevArtem** [comment]
This pr should be rebased after #8683 will be merged.

**Comment by BalyshevArtem** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
Could you please add `operand`s first then `operator`s like other recipe files?

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
