### PR TITLE
[infra] Remove remain ARMCompute test build

### PR DESCRIPTION
**Pull request by hseok-oh**
ARMCompute still build some tests. Let's remove remain test build.

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by chunseoklee** [comment]
x64-builder fails with certificate error since days ago(http://nnfw.mooo.com:8080/job/nnfw/job/master/job/pr-x64-builder-tester/)

**Review by chunseoklee — APPROVED** [review]

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder

**Comment by hseok-oh** [comment]
> x64-builder fails with certificate error since days ago(http://nnfw.mooo.com:8080/job/nnfw/job/master/job/pr-x64-builder-tester/)

I don't know reason, but anyway I resolved this issue by setting `git`'s `sslVerify` option to false on build server.

**Pull request merged**
