### PR TITLE
[one-cmds] Remove unused option

### PR DESCRIPTION
**Pull request by seanshpark**
This will remove unused option that was added by misunderstanding.

### CODE REVIEW

**Comment by seanshpark** [comment]
- for https://github.com/Samsung/ONE/pull/13936#discussion_r1744875810

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Review by shs-park — APPROVED** [review]
LGTM!
=)

**Pull request merged**
