### PR TITLE
[onert] Introduce ExecutionContext

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduces ExecutionContext struct.
It includes IODescription and execution options to be used by executor.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Draft: #13013

### CODE REVIEW

**Comment by hseok-oh** [comment]
```
curl: (28) Failed to connect to bart.sec.samsung.net port 443: Connection timed out
```

@nnfw-bot test onert-cross-aarch64-release

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-cross-aarch64-release

**Review by zetwhite — APPROVED** [review]
LGTM :+1:

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
