### PR TITLE
[onecc-docker] Change docker file path

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit changes the docker file path.
The dockerfile will be placed in the bin directory.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
Seems `onecc-docker` and `docker/` folder are placed at the same directory. `Dockerfile` will be moved after this PR?

**Comment by seanshpark** [comment]
@jyoungyun , can you explain about this change? was it a typo? or something else?

**Comment by jyoungyun** [comment]
> Seems `onecc-docker` and `docker/` folder are placed at the same directory. `Dockerfile` will be moved after this PR?

https://github.com/Samsung/ONE/blob/3f5c35ffc61b4c1c2a2567625fc7b45a586fe985/compiler/onecc-docker/debian/onecc-docker.install#L1-L2
According to above codes, `onecc-docker` is located in `bin` directory. The original code finds the `docker` directory in the `bin` directory. However, the `docker` directory is placed in the parent directory of `onecc-docker` file.
So I changed the code.

**Comment by seanshpark** [comment]
Q) can we change this?
```diff
compiler/onecc-docker/onecc-docker /usr/share/one/bin/
- compiler/onecc-docker/docker/Dockerfile /usr/share/one/docker/
+ compiler/onecc-docker/docker/Dockerfile /usr/share/one/bin/docker/
```

**Comment by jyoungyun** [comment]
> Q) can we change this?

Sure :)

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Pull request merged**
