### PR TITLE
[luci] Dump PartitionTable byopnames

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable dump of PartitionTable byopnames items.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6723, #7164, from draft #6231

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
