### PR TITLE
[circle dump] Added L2Norm to circle dump

### PR DESCRIPTION
**Pull request by AShedko**
Signed-off-by: a.shedko <sirius.frozen@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
I'v added `NO MERGE` cause there is no body text in commit message but our IC passed. This is a problem.
@hseok-oh , can you please take a look?

**Comment by seanshpark** [comment]
Change looks good. I'll continue landing with @hseok-oh 's check.

**Comment by hseok-oh** [comment]
@seanshpark I found out that our CI server (AWS) don't support command `bc`, so body checker is not working correctly. Thanks for report. I'll update CI script to work without `bc`.

**Comment by seanshpark** [comment]
@AShedko , can you please edit your commit message that explains about this change?
- https://github.com/Samsung/ONE/pull/1590/commits/9f1a15df673c590f48e2a516d427d5709004de41

**Comment by AShedko** [comment]
Rebased and updated desciption

**Pull request merged**
