### PR TITLE
DRAFT Compiler FE: Support  Reduce Max operation

### PR DESCRIPTION
**Pull request by d-krylov**
Support  Reduce Max operation 

ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>

### CODE REVIEW

**Comment by binarman** [comment]
@d-krylov python example is missing

**Comment by seanshpark** [comment]
Seems OK with `python example is missing`

**Comment by seanshpark** [comment]
Can we close this draft? or are there any left to land?

**Comment by seanshpark** [comment]
@binarman , Can we close this draft? or are there any left to land?

**Comment by binarman** [comment]
Yes, all done, closing

**Pull request closed without merging**
