### PR TITLE
[infra/onert] Fix buildtool build bug (#12356)

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit fixes buildtool build fail by invalid download option.

This PR is cherry-picked from the master branch.
ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@mhs4670go Need one more approval to merge release branch

**Review by Seunghui98 — APPROVED** [review]
LGTM 👍

**Pull request merged**
