### PR TITLE
[one-cmds] Enable finding backend command from system path

### PR DESCRIPTION
**Pull request by jinevening**
This enables to find backend command from system path.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Currently, backend should be placed in (1) `bin` folder where `one-codegen` exists or  (2) `backends` folder

For convenience, I'd like to enable finding backend command from the system path.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> For convenience, I'd like to enable finding backend command from the system path.

@jinevening , this will change(add) characteristic of backend command search algorithm
it would be better describe here about the reason for this change, not just `convenience`
but actual problem or something like.

**Comment by jinevening** [comment]
> it would be better describe here about the reason for this change, not just convenience
but actual problem or something like.

When we make a release package of ONE, `one-codegen` is not linked with any backend. So, we should copy (or make a symbolic link of) the binary of the backend into the corresponding directories before using `one-codegen`. This change allows `one-codegen` to find the backend if the backend is available in the system path. This will reduce the step to use `one-codegen`.

Note that this change is backward-compatible, because the search on the system path is only conducted if the backend is not found in the `bin` directory or `backends` directory.

**Comment by seanshpark** [comment]
> Note that this change is backward-compatible, because the search on the system path is only conducted if the backend is not found in the bin directory or backends directory.

I this just that I would like to leave records for this change as it's directly related with UX.
So there is no issues or problems with this change? 
This is what I can imagine.
- A may install (by manual?) a backend to some folder and add the PATH
- B may install (by manual?) a backend to some folder but forgot to add to the PATH

If you have'nt then it would be nice if you add something about this in the documents.

**Comment by glistening** [comment]
I also think it would be good if it is written somewhere in ONE_GUIDE. I thought there was already an explanation for rule for finding backend driver. As I remember, at least it was there in some issue or PR. @jyoungyun Do you remember the location?

**Comment by jyoungyun** [comment]
@glistening Do you mean here? We have discussed this code before.
https://github.com/Samsung/ONE/blob/c2a31b05d86250d2708cf1fa87a9a1615fd401ad/compiler/one-cmds/one-codegen#L39-L54

And `one-profile` has the same rule with `one-codegen`. If this changes is applied, `one-profile` must be modified too.

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
