### PR TITLE
[luci/import] Clean up some comments

### PR DESCRIPTION
**Pull request by shs-park**
Some of comments have been cleaned up
- Commas deleted
- Unnecessary comments deleted

ONE-DCO-1.0-Signed-off-by: Seungho Henry Park [shs.park@samsung.com](mailto:shs.park@samsung.com)

---

Related to: #10930 
Draft PR: #10985

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Comment by seanshpark** [comment]
@shs-park , current commit signed-off does not have `ONE-DCO-` prefix.
please fix this.

**Review by seanshpark — CHANGES_REQUESTED** [review]
plz fix signed-off

**Comment by shs-park** [comment]
signed-off Fixed!
There was auto script problem in my local git system.
Thanks for finding this problem.

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
