### PR TITLE
[luci/service] Support MUL dynamic shape inference

### PR DESCRIPTION
**Pull request by qsunki**
This supports dynamic shape inference for MUL.

ONE-DCO-1.0-Signed-off-by: sunki <ajsthfldu@outlook.com>

---
Related to: #13697 
Draft PR: #13777

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by zetwhite — DISMISSED** [review]
LGTM :+1:

**Comment by qsunki** [comment]
I have checked this comment https://github.com/Samsung/ONE/pull/13780#pullrequestreview-2265214545 and have applied it to the current PR.

**Review by zetwhite — APPROVED** [review]

**Review by shs-park — APPROVED** [review]
LGTM!
=)

**Pull request merged**
