### PR TITLE
[onert] Refactor EventWriter

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
Refactor `EventWriter`.
Three specific methods were written as separate classes,  `SNPEWriter`, `ChromeTracingWriter`, and `MDWriter`.

(while working on #4903 for #4901)

Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Comment by wateret** [comment]
```
19:43:36 In file included from /opt/jenkins_slave/workspace/nnfw/master/pr-android-runtime-builder/runtime/onert/core/src/util/EventWriter.cc:17:
19:43:36 /opt/jenkins_slave/workspace/nnfw/master/pr-android-runtime-builder/runtime/onert/core/src/util/EventWriter.h:81:24: error: private field '_recorder' is not used [-Werror,-Wunused-private-field]
19:43:36   const EventRecorder &_recorder;
19:43:36                        ^
19:43:36 1 error generated.
```

Unused member

**Review by wateret — DISMISSED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
@wateret Thanks, removed!

**Review by YongseopKim — APPROVED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by hyunsik-yoon** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by hyunsik-yoon** [comment]
@nnfw-bot test cross-runtime-test-release
@nnfw-bot test cross-runtime-test-debug

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
