### PR TITLE
[common-artifacts] Use variable for target files

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise to use variable for target files.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #8379, from draft #8407

**Review by mhs4670go — APPROVED** [review]
LGTM. But IMHO, actually, current codes are readable and short enough to me.

**Comment by seanshpark** [comment]
This is to prepare override target executables for cross build.
For cross build, we need to run host executable.
In next PR, the variable will changee for cross build.

**Comment by mhs4670go** [comment]
> This is to prepare override target executables for cross build.
For cross build, we need to run host executable.
In next PR, the variable will change for cross build.

I thought cross-build means our preset for package is going to be built at cross platform. And our preset doesn't have `common-artifacts` for build list. Is there any reason for building `common-artifacts`?

**Comment by seanshpark** [comment]
> Is there any reason for building common-artifacts?

To validate value testing of `luci` + `luci-interpreter` in ARM32 target is the main reason.
For this, I used `luci-value-test` and this uses files from `common-artifacts`

But as I could't find ARM32 TensorFlow and lite, I could not use the tflite interpreter as generating reference output data.
So I tought of (1) prepare reference input/output data with host build (2) use those files as reference data to compare the output of ARM32 luci-interpreter.

Current draft has modified versions of test scripts that runs in ARM32 target device.

**Comment by seanshpark** [comment]
Hum... actually common-artifacts generated files doesn't seem to be used cross build testing...

I think it was because current dependency link from "requires.cmake" fixes the dependency.

**Comment by seanshpark** [comment]
I'll check if we can skip whole `common-artifacts` for cross build.
That is #8511 can be revised.

**Comment by seanshpark** [comment]
This change is not needed. We can skip this module for ARM32 cross build.

**Pull request closed without merging**
