### PR TITLE
[onert] Introduce Pool2D train operation

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit introduces Pool2D train operation.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Comment by jyoungyun** [comment]
@nnfw-bot test onert-x64-release

**Comment by jyoungyun** [comment]
@nnfw-bot test onert-x64-release

**Comment by ragmani** [comment]
@jyoungyun Could you add converting `Pool2D` as well like #11015 ?

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
