### PR TITLE
[res] TensorFlowLiteRecipes for PadV2

### PR DESCRIPTION
**Pull request by a-zh**
This adds PadV2 model recipe

Draft: #3566
Issue: #3362

### CODE REVIEW

**Comment by seanshpark** [comment]
```
01:23:35 [ 57%] Generating PadV2_000.tflite
01:23:35 terminate called after throwing an instance of 'std::out_of_range'
01:23:35   what():  map::at
01:23:35 [ 57%] Building CXX object compiler/luci/export/CMakeFiles/luci_export.dir/src/CircleExporterUtils.cpp.o
01:23:35 compiler/luci/tests/CMakeFiles/luci_testfiles.dir/build.make:1402: recipe for target 'compiler/luci/tests/PadV2_000.tflite' failed
```

**Review by lufterc — APPROVED** [review]
LGTM :+1:

**Review by d-krylov — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by ai-moiseev — APPROVED** [review]
LGTM

**Comment by binarman** [comment]
Merging without @kvochko approval, since he is on vacation.

**Pull request merged**
