### PR TITLE
[tools/mec] Revise MANIFEST.in

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise MANIFEST.in to include tests and exclude HOWTO.md.

### CODE REVIEW

**Comment by seanshpark** [comment]
- for #14330

**Review by batcheu — APPROVED** [review]
LGTM

**Comment by batcheu** [comment]
I didn't notice that 'mec' is abbreviation of '**m**odel_**e**xplorer_**c**ircle' 😯

**Comment by seanshpark** [comment]
> 'mec' is abbreviation of 'model_explorer_circle'

yes... `model_explorer_circle` is quite long for my laziness :)

**Pull request merged**
