### PR TITLE
[draft][npud] Add Trix backend

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit is a draft PR.
It contains the detail implementation of Trix Backend.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Comment by glistening** [comment]
@jyoungyun

At a glance, `runtime/service/npud/backend/trix/util/ConfigSource.cc` is likely to make the same problem @hseok-oh had solved in #9576, which I reported:

Internal Analysis Report says:

```
DC Top 25

No 1. runtime/onert/core/src/util/ConfigSource.cc
No 2. runtime/service/npud/util/ConfigSource.cc
...
```

I think we may factor out `ConfigSource.*` under `runtime/libs`.

_Originally posted by @glistening in https://github.com/Samsung/ONE/issues/9525#issuecomment-1206075245_

**Comment by jyoungyun** [comment]
> I think we may factor out `ConfigSource.*` under `runtime/libs`.

I'm sorry but I couldn't catch your intention. As I know, @hseok-oh already moved the `EnvConfigSource` related files to `misc`. And npud uses the misc library. Which part should I modify?

**Comment by glistening** [comment]
@jyoungyun This draft introduce another `ConfigSource.cc` — `runtime/service/npud/backend/trix/util/ConfigSource.cc`. It seems to have duplicated code. It seems copy-and-pasted code. Almost all code seems to be duplicated. I concerns it may our DC score again.

**Comment by jyoungyun** [comment]
@glistening I understood. I will look for the way to use it as one.
/cc @hseok-oh

**Pull request closed without merging**
