### PR TITLE
[luci/pass] Change names in FuseGeluPass.test

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This PR refactors FuseGeluPass.test to add more patterns at future.

for issue: https://github.com/Samsung/ONE/issues/11002
from draft: https://github.com/Samsung/ONE/pull/11016

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Plz change title. This change only changes test name, not refactoring.

**Review by jinevening — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
You need to update commit. see commits in https://github.com/Samsung/ONE/pull/11021/commits

**Comment by BalyshevArtem** [comment]
> You need to update commit. see commits in https://github.com/Samsung/ONE/pull/11021/commits

Done

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Review by jinevening — APPROVED** [review]

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
