### PR TITLE
Add hall-of-fame section to README.md

### PR DESCRIPTION
**Pull request by lemmaa**
- Introduced hall-of-fame as a thank you for the contributor.

Signed-off-by: Sung-Jae Lee <sj925.lee@samsung.com>

### CODE REVIEW

**Comment by lemmaa** [comment]
You can preview the rendering [here](https://github.com/Samsung/ONE/pull/1922/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8).

@Samsung/one , please let me know, if you have any other comments to introduce this feature, or give me +1. I experienced this in https://github.com/huggingface/transformers/blob/master/README.md

**Comment by cgbahk** [comment]
:rocket:

**Comment by wateret** [comment]
Actually I think its position shouldn't be at the top. I would prefer basic info comes first.

**Comment by lemmaa** [comment]
> Actually I think its position shouldn't be at the top. I would prefer basic info comes first.

@wateret , @jinevening , could you please pin point the proper position you suggest?

**Comment by wateret** [comment]
For me, I would like it at the bottom.

**Comment by jinevening** [comment]
> For me, I would like it at the bottommost.

@lemmaa , me too.

**Comment by glistening** [comment]
> For me, I would like it at the bottommost.

I also think it is not good to put hall-of-frame at top because

1) For outside developers, who visited here first time, they expect to get what is about `ONE`, not about who are the most or first committed person.
2) If someone would like to find this information, he/she can see from `insights`.

I prefer to get it at the bottom. However, I am not against this PR. I am just saying my opinion.

**Comment by lemmaa** [comment]
@wateret , @jinevening , @glistening , @ragmani , @hseok-oh , @llFreetimell , the position is changed to bottommost.

I also thought a lot about the top and bottom, but I wanted to mark it more clearly because the purpose of the introduction itself was to encourage external developers to participate in the project. I still disagree from a kind of marketing point of view, but many people's opinions are bottommost, so I'm going to do that first. :)

**Comment by hseok-oh** [comment]
@nnfw-bot test all

**Pull request merged**
