### PR TITLE
[one-cmds] Add test cases for one-profile

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds several test cases for one-profile.

Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

This PR is related to #7360 .

### CODE REVIEW

**Comment by jyoungyun** [comment]
This issue depends on #7360. So it's natural to break.

**Comment by jyoungyun** [comment]
All test case of `one-profile` is passed.
```
one-profile_001.test SUCCESS
one-profile_002.test SUCCESS
one-profile_003.test SUCCESS
one-profile_004.test SUCCESS
one-profile_neg_001.test SUCCESS
ALL TESTS PASSED!
```

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
