### PR TITLE
[onnx-tools] Introduce _gather_value_infos

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce _gather_value_infos in onnx-dump.

### CODE REVIEW

**Comment by seanshpark** [comment]
- for #13973
- from #13976

**Comment by jinevening** [comment]
There is a typo in the commit message. [onx-tools] -> [onnx-tools]

I left some comments in the draft PR. PTAL

**Comment by seanshpark** [comment]
@jinevening , applied :)

**Review by jinevening — APPROVED** [review]
LGTM Thank you!

**Review by shs-park — APPROVED** [review]
LGTM!
=)

**Pull request merged**
