### PR TITLE
[common-artifacts] Skip prepare venv for cross build

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise to skip preparation of venv for cross build.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #8379, from draft #8407

**Review by mhs4670go — APPROVED** [review]
LGTM
(optional) It would be better to comment the reason why it has to be skipped.

**Comment by seanshpark** [comment]
> It would be better to comment the reason why it has to be skipped.

Ah, main reason is that 
(1) I'm not sure preparing host venv for target build is needed
(2) TensorFlow for ARM32 doesn't seem to exist.

**Comment by seanshpark** [comment]
This change is not needed. We can skip this module for ARM32 cross build.

**Pull request closed without merging**
