### PR TITLE
[one-cmds] Fix invalid input arguments

### PR DESCRIPTION
**Pull request by jinevening**
This fixes invalid input arguments

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug
@nnfw-bot test nncc-release

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug
@nnfw-bot test nncc-release

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug
@nnfw-bot test nncc-release

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
@nnfw-bot test nncc-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
