### PR TITLE
[DRAFT] Compiler FE Support for LOG Op

### PR DESCRIPTION
**Pull request by kishcs**
On-going draft PR to support LOG Op

ONE-DCO-1.0-Signed-off-by: kishore.cs <kishore.cs@samsung.com>

Ref: #953

### CODE REVIEW

**Comment by seanshpark** [comment]
@kishcs , as our ONE repo is now public, not private anymore, you may have to,
- rename your ONE private to something else
- fork ONE again
- push this PR again, maybe with `--force` option

**Comment by kishcs** [comment]
> @kishcs , as our ONE repo is now public, not private anymore, you may have to,
> 
> * rename your ONE private to something else
> * fork ONE again
> * push this PR again, maybe with `--force` option

ohh okay. I forked, so it created ONE-1, may be I will rename old ONE first, then fork.
Thanks :)

**Comment by kishcs** [comment]
I raised PR for res/TensorflowPythonExamples. Will that affect the DRAFT PR (yet to create) ?

**Comment by seanshpark** [comment]
> I raised PR for res/TensorflowPythonExamples. Will that affect the DRAFT PR (yet to create) ?

I'm not sure... let's go on with what you want to proceed...

**Pull request closed without merging**
