### PR TITLE
[circle2circle] Add an option for RemoveUnnecessaryCastPass

### PR DESCRIPTION
**Pull request by jiwaszki**
This commit adds an option for RemoveUnnecessaryCastPass.

ONE-DCO-1.0-Signed-off-by: Jan Iwaszkiewicz <j.iwaszkiewi@samsung.com>

### CODE REVIEW

**Comment by jiwaszki** [comment]
From: https://github.com/Samsung/ONE/pull/13760
For: https://github.com/Samsung/ONE/issues/13623

**Comment by mhs4670go** [comment]
It needs to be rebased as the base commist doesn't have the recipe.

**Comment by jiwaszki** [comment]
@mhs4670go yeah it's waiting for https://github.com/Samsung/ONE/pull/13893 to be merged.
What is more common practice in the project? Should I split/post it only when all of required parts are merged to master? Or do it like I am doing it now? (Now means that all parts are posted at the "same" time, where some are waiting for others. That gives time to review all of them, check smaller parts without waiting.)

**Comment by seanshpark** [comment]
> What is more common practice in the project?

Good question. I think you're the first to ask this :)
Common is to post one by one for having dependencies and post multiples if not.
But it's OK to post like this and re-base when dependent has landed.

**Pull request merged**
