### PR TITLE
update-version script is added

### PR DESCRIPTION
**Pull request by glistening**
There are several files to be updated when version is changed.
`update-version` will do it at once. For example,

$ update-version 1.7.0

It will change tizen spec, nnfw_version, doc_version.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

### CODE REVIEW

**Comment by glistening** [comment]
Running `update-version`
```
$ ./infra/nnfw/command/update-version 1.7.0
```
will change:

```diff
diff --git a/docs/conf.py b/docs/conf.py
index f571110..59094e7 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -21,7 +21,7 @@ copyright = '2020, Samsung Research & contributors'
 author = 'Samsung Research & contributors'
 
 # The full version, including alpha/beta/rc tags
-release = '1.4.0'
+release = '1.7.0'
 
 # -- General configuration ---------------------------------------------------
 
diff --git a/packaging/nnfw.spec b/packaging/nnfw.spec
index 1cb9922..fce3d90 100644
--- a/packaging/nnfw.spec
+++ b/packaging/nnfw.spec
@@ -1,6 +1,6 @@
 Name:    nnfw
 Summary: nnfw
-Version: 1.5.0
+Version: 1.7.0
 Release: 1
 Group:   Development
 License: Apache-2.0 and MIT and BSD-2-Clause
diff --git a/runtime/onert/api/include/nnfw_version.h b/runtime/onert/api/include/nnfw_version.h
index 0c32a69..d787870 100644
--- a/runtime/onert/api/include/nnfw_version.h
+++ b/runtime/onert/api/include/nnfw_version.h
@@ -21,6 +21,6 @@
  * NNFW_VERSION is a uint32 value representing nnfw runtime version
  * in 0xMMmmmmPP, where MM = major, mmmm = minor, PP = patch
  */
-#define NNFW_VERSION 0x01000500
+#define NNFW_VERSION 0x01000700
 
 #endif // __NNFW_VERSION_H__
```

**Comment by hseok-oh** [comment]
It's better in `tools/`, not `infra/command`, IMO.

**Comment by glistening** [comment]
@hseok-oh There are no scripts under `tools`. All scripts has its own subdirectory. Are you okay to put this script under `tools`? Or do you want to introduce a subdirectory? If so, what name do you prefer?

**Comment by hseok-oh** [comment]
>Are you okay to put this script under tools? Or do you want to introduce a subdirectory?

Introduce a subdirectory

>If so, what name do you prefer?

I don't have any preference. (ex. `update_version` ? )

**Comment by glistening** [comment]
@hseok-oh My idea is exactly same to yours. I create `update-version` directory before your comment. Also, I've make `update-version` to work even out of `nnfw` root directory.

**Pull request merged**
