### PR TITLE
[mir] Update clang-format version

### PR DESCRIPTION
**Pull request by hseok-oh**
Use clang-format-8 style for mir

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@binarman , I don't exactly remember that `mir` and related projects are following the format check. But if it's OK with you, we can merge this. If SRR want's to go with own format then it is OK not to land this for me.

**Review by binarman — APPROVED** [review]
LGTM
Thank you!

**Comment by binarman** [comment]
@seanshpark 
> I don't exactly remember that mir and related projects are following the format check. But if it's OK with you, we can merge this. If SRR want's to go with own format then it is also OK not to land this for me.

Originally mir user it's own code style, but I think it is ok to unify it with main repo now.
(AFAIK there are no automatic check that could break because of this)

**Review by a-zh — APPROVED** [review]
LGTM

**Review by ai-moiseev — APPROVED** [review]
LGTM

**Pull request merged**
