### PR TITLE
[circle2circle] Add substitute_expand_dims_to_reshape option

### PR DESCRIPTION
**Pull request by dayo09**
Let's add substitute_expand_dims_to_reshape option to circle2circle cli.

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
Plz follow https://github.com/Samsung/ONE/wiki/ONE-Developer%27s-Certificate-of-Origin

**Comment by dayo09** [comment]
@seanshpark I changed the DCO. PTAL :-D

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
