### PR TITLE
[luci] Introduce NCHW to NHWC convert sub option enums

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce two sub option enums for ConvertNCHWToNHWC to
convert also with I/O that will replace 'preserve' sub options.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6832

**Comment by jinevening** [comment]
Do we have to add new options?

Why not change the default value of `--nchw_to_nhwc_preserve_input_shape` to true in `Circle2Circle.cpp`?

**Comment by seanshpark** [comment]
> Do we have to add new options?
> Why not change the default value of --nchw_to_nhwc_preserve_input_shape to true in Circle2Circle.cpp?

That can be an option.
This point is from how the user will think for this feature.
As of default, compiler will convert nodes from NCHW to NHWC but not inputs nor outputs.
From the view, "provide an option to make I/O conversion" will directly translates to 
"NCHW_to_NHWC_input_shape" and "NCHW_to_NHWC_output_shape"

But foir "..preserve..." option, user has to think twice for the option.

And with compilation option, we have 
```
circle2circle --nchw_to_nhwc_preserve_input_shape
```
to turn it off, it would be something like (not sure this is the way...)
```
circle2circle --nchw_to_nhwc_preserve_input_shape 0
```
or in `cfg` file
```
nchw_to_nhwc_preserve_input_shape=False
```
which is a twist...

So, for user interface simplicity, IMHO it seems better with `nchw_to_nhwc_input_shape`

**Comment by jinevening** [comment]
I see. Thanks for the detailed explanation.

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
