### PR TITLE
[onert] Support circle schema v0.6

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit updates onert frontend to support circle schema v0.6.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: https://github.com/Samsung/ONE/issues/11381
Schema: #11382

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Comment by hseok-oh** [comment]
Circle schema update PR (https://github.com/Samsung/ONE/pull/11382) is merged.

**Review by ragmani — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
