### PR TITLE
[infra] Add `circle-interpreter` to debain package

### PR DESCRIPTION
**Pull request by yunjayh**
This commit adds `circle-interpreter`to debian package.

Signed-off-by: yunjay-hong <yunjay.hong@samsung.com>

---

for: #9634 
draft: #9635

### CODE REVIEW

**Review by jinevening — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
It would be better to merge `circle-interpreter-test` first :)

**Comment by seanshpark** [comment]
@yunjayh , before landing this let's provide the tests first.
- circle-interpreter-test
- one-cmds test for circle-interpreter (as I know this will be called from one-infer)

**Comment by yunjayh** [comment]
The tests are landed! PTAL

> * circle-interpreter-test

- Done

> * one-cmds test for circle-interpreter (as I know this will be called from one-infer)

- The tests which are planned to do in `one-cmds` test are implemented in `circle-interpreter-test`. :smile:

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
