### PR TITLE
[debian] Update changelog

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit updates changelog for release 1.26.0.

Related: #12299 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by jinevening — APPROVED** [review]
LGTm

**Comment by jinevening** [comment]
It seems that 1.25.0 is missing.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> It seems that 1.25.0 is missing.

FYI 1.25.0 was released only with runtime: https://github.com/Samsung/ONE/releases/tag/1.25.0

**Pull request merged**
