### PR TITLE
[onert] Unify element-wise unary operations to ElementwiseUnary.

### PR DESCRIPTION
**Pull request by ragmani**
For issue #3625

This commit unifies element-wise activation operations to ElementwiseActivation for reducing code duplication.

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
@nnfw-bot test cross-runtime-test-release

**Review by wateret — APPROVED** [review]
LGTM

**Comment by ragmani** [comment]
Rebase this.

**Review by hseok-oh — APPROVED** [review]

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
