### PR TITLE
[compiler/luci/tests] Add Items for U8

### PR DESCRIPTION
**Pull request by underflow101**
Related Issue: #1880 
Fired Issue: #3519 

This commit adds 3 items below at `compiler/luci/tests/test.lst` for `./nncc build` and `./nncc test`.
	- `AveragePool2D_U8_000`
	- `L2Normalize_U8_000`
	- `Logistic_U8_000`

Please review this PR, @seanshpark @jinevening .
I'll be happy to get feedback and change to make improvement.

Thank you.

Signed-off-by: underflow101 <ikarus125@gmail.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
There is no `addwrite` of `AveragePool2D_U8_000` and `L2Normalize_U8_000`. This tests fail because of NYI?

**Comment by underflow101** [comment]
> There is no `addwrite` of `AveragePool2D_U8_000` and `L2Normalize_U8_000`. This tests fail because of NYI?

I think I missed this when I was checking out my branch.
I will rewrite for 2 items and recommit!

Thank you for your advice! :)

**Comment by underflow101** [comment]
> LGTM thank you!

I'm sorry for your inconvenience, @seanshpark 
I added addwrite() for AveragePool2D_U8_000 and L2Normalize_U8_000 again (since these 2 were missing while I was changing my branch).

Could you please check again?

Thank you, @seanshpark !

**Comment by underflow101** [comment]
20.07.29 17:50(GMT+9):
pr-nncc-release & pr-nncc-debug has failed due to `addread(Logistic_U8_000)` & `addwrite(Logistic_U8_000)`.

This probably happened because I have commited these before [res/TensorFlowLiteRecipe] Logistic_U8_000 (#3516) was merged.
I fetched upstream from my local git,  rebased, and then re-committed this.

Thank you.

**Pull request closed without merging**
