### PR TITLE
[infra] Infra for clang-format-8 migration on each directory

### PR DESCRIPTION
**Pull request by hseok-oh**
- ."clang-format.8" : clang-format style file for clang-format-8

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Part of #5223 
Related issue: #5131

### CODE REVIEW

**Comment by mhs4670go** [comment]
I'm not sure but to migrate it step by step, `clang-format-8` will be applied to the folder that has `.clang-format`. And then `.clang-format`s will be removed later. Is it right?

**Comment by hseok-oh** [comment]
@mhs4670go Exactly

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
