### PR TITLE
[infra] Extract cmake options to separate file

### PR DESCRIPTION
**Pull request by seanshpark**
This will extract cmake options to separate CfgOptionFlags.cmake file.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
from draft #8578

**Comment by seanshpark** [comment]
CC @yunjayh

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Pull request merged**
