### PR TITLE
[luci] Refactoring constant folding tests

### PR DESCRIPTION
**Pull request by jinevening**
This refactors constant folding tests.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/5700

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
Error:
```
12:00:22 The following tests FAILED:
12:00:22 	 71 - luci_pass_test (SEGFAULT)
12:00:22 Errors while running CTest
```

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
