### PR TITLE
[onert] Remove ONERT_TRAIN flag

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit removes ONERT_TRAIN flag.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: #12293

### CODE REVIEW

**Comment by hseok-oh** [comment]
Related PRs: #12290 #12297

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
I'll merge this without @ragmani 's review for other PRs.

**Pull request merged**
