### PR TITLE
[onert/test] Remove unused function in tflite loader test tool

### PR DESCRIPTION
**Pull request by hseok-oh**
Remove unused function executeGraph
Remove unused headers and dependency

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
@hseok-oh Beyond this PR. I think the name `tflite_loader_test` is misnomer at this moment. It does not just test whethter `tflite` is loadable with `tflite_loader`. It does 1) **`run`** `onert` and 2) run `tflite interpreter` and 3) compare them. We can do same thing with `nnpkgtc` automatically though it requires more work to work them in our CI.

I have no idea of good name since it does too much thing though it is convenient. Perhaps `tflite_run_comparator` or `tflite_loader_run` may be better at least for me.

**Review by glistening — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@glistening I also agree with your opinion.

**Pull request merged**
