### PR TITLE
[luci/tests] added L2 Normalize to luci tests

### PR DESCRIPTION
**Pull request by AShedko**
added L2 Normalize to luci tests
draft #1432 
Signed-off-by: Shedko Andrey/AI Tools Lab /SRR/Engineer/Samsung Electronics <a.shedko@samsung.com>

### CODE REVIEW

**Comment by AShedko** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
```
20:50:19 64/75 Test #64: luci_unit_readtest .........................***Failed    1.73 sec
20:50:19 FAILED
20:50:19 - L2Normalize_000
20:50:19 
20:50:19       Start 65: luci_unit_writetest
20:50:21 65/75 Test #65: luci_unit_writetest ........................***Failed    2.07 sec
20:50:21 FAILED
20:50:21 - L2Normalize_000
20:50:21 
```
maybe something is missing / rebase needed...

**Comment by AShedko** [comment]
No rebase needed for now. #1466 has to be merged first.

**Comment by hseok-oh** [comment]
@AShedko  Please check this PR

**Comment by seanshpark** [comment]
```
00:07:01 64/75 Test #64: luci_unit_readtest .........................***Failed    1.25 sec
00:07:01 FAILED
00:07:01 - L2Normalize_000
00:07:01 
00:07:01       Start 65: luci_unit_writetest
00:07:02 65/75 Test #65: luci_unit_writetest ........................***Failed    1.48 sec
00:07:02 FAILED
00:07:02 - L2Normalize_000
00:07:02 
```

Maybe rebase to master...

**Comment by AShedko** [comment]
PTAL, @seanshpark , @parjong

**Comment by parjong** [comment]
@AShedko You don't need my approval if you work on _luci_ ;-) The approval from @seanshpark would be enough.

**Pull request merged**
