### PR TITLE
[onert] Change core install path

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit changes core library install path: lib -> lib/nnfw.
Only API libraries are installed to lib.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by ragmani — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]

**Comment by hseok-oh** [comment]
@jyoungyun @ragmani PTAL

**Review by ragmani — APPROVED** [review]

**Comment by hseok-oh** [comment]
@jyoungyun PTAL

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
