### PR TITLE
[luci] Remove MigrateLegacyShapeDtypePass

### PR DESCRIPTION
**Pull request by llFreetimell**
Parent Issue : #5501

`MigrateLegacyShapeDtypePass` was for copying and pasting annotated loco items.
However, as `CircleShapeInferencePass` and `CircleTypeInferencePass` are introduced and they can copy and paste the items,
`MigrateLegacyShapeDtypePass` is no more needed.
Thus this commit will remove it.

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@llFreetimell , have you revived the code that was removed for this Pass ?

**Comment by llFreetimell** [comment]
@seanshpark `CircleShapeInferencePass` and `CircleTypeInferencePass` will be responsible for that :)

- `ShapeInferencePass`, `TypeInferencePass` : Inference shape and annotate it as loco item
- `CircleShapeInferencePass`, `CircleTypeInferencePass`: Inference shape and copy it to the shape and dtype of `CircleNode`

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
