### PR TITLE
[record-minmax] verify circle file

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit enables record-minmax to verify circle file.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by ragmani** [comment]
Please rebase this.

**Comment by mhs4670go** [comment]
@ragmani This will be rebased after #3926 is merged.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]

**Pull request merged**
