### PR TITLE
[mir-interpreter] Add exclude.me

### PR DESCRIPTION
**Pull request by seanshpark**
This will add exclude.me to exclude this module from build.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #11814 , from  #11848

**Comment by seanshpark** [comment]
> compiler/mir/src/mir_onnx_importer/ONNXHelpers.cpp:20:10: fatal error: MirInterpreter.h: No such file or directory

**Review by jinevening — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
