### PR TITLE
[tflchef] Remove local graph_name

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise to remove local graph_name variable.

### CODE REVIEW

**Comment by seanshpark** [comment]
- for #13627

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@Samsung/one_compiler PTAL

**Review by Seunghui98 — APPROVED** [review]
LGTM :)

**Review by shs-park — COMMENTED** [review]
👍

**Pull request merged**
