### PR TITLE
[doxygen] Update doxygen config file

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit updates doxygen config file
- Update project name: nnas -> ONE
- Reduce page size
  - Restrict input files
  - Exclude test files and README.md on each directory
- Change main page: roadmap.md -> README.md
- Simplify graph generation
- Remove dot path setting: use default

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: #10103

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@hseok-oh , maybe add @lemmaa  ?

**Comment by hseok-oh** [comment]
You can test doxygen generation by fetching this PR commit and run `./nnas doxygen` (need `apt install doxygen graphviz`)

**Comment by hseok-oh** [comment]
@lemmaa PTAL

**Review by lemmaa — APPROVED** [review]
LGTM. Sorry for the late review.

**Pull request merged**
