### PR TITLE
[tflite2circle] Add verbose option

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds verbose option.

Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM

**Comment by jyoungyun** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@jyoungyun As you said in offline, there is no contents to verbose. What it is for?

**Comment by jyoungyun** [comment]
@mhs4670go 
Yes, there is no log data in this tool. But I want to keep the same usability between our tools. All other tools in this project, there is a verbose option. What do you think about it?

**Comment by mhs4670go** [comment]
@jyoungyun Technically speaking, verbose option is only needed to `one-cmds`(python script). Because c++ tools can be verbosed just by setting `LUCI_LOG` environment. Anyway, if it looks fine to you, this can be merged.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by jyoungyun** [comment]
> Technically speaking, verbose option is only needed to one-cmds(python script). Because c++ tools can be verbosed just by setting LUCI_LOG environment. Anyway, if it looks fine to you, this can be merged.

Yes, right. But if users want to use the native tool directly, they probably don't know the LOG TAG like `LUCI_LOG`. Because there is a `--verbose` option, the user will be able to use it more conveniently.

Thank you!

**Pull request merged**
