### PR TITLE
[luci-interpreter] Add more `KernelBuilder` tests

### PR DESCRIPTION
**Pull request by s-barannikov**
Issue #1088.

Add more tests of `KernelBuilder`.

ONE-DCO-1.0-Signed-off-by: Sergei Barannikov <s.barannikov@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Please add negative tests too with `_NEG` suffix in the name.

**Comment by s-barannikov** [comment]
@seanshpark 
Provided the correct circle model, the functions being tested will never fail. I can't see what negative tests should look like. Can you suggest something?

**Comment by seanshpark** [comment]
> Can you suggest something?

I haven't reviewed the codes. I also can't suggest. It's about our SE requirements to provide negative testing.
If we keep adding only postive tests, our project may be rejected.

**Comment by seanshpark** [comment]
You can add negative tests in another PR but please add within our project timeline.

**Comment by s-barannikov** [comment]
> It's about our SE requirements to provide negative testing.
If we keep adding only postive tests, our project may be rejected.

OK, I will bear this in mind.

**Comment by jinevening** [comment]
IMHO, one way to make a negative test is to make a test expected to throw an exception (caused by wrong behaviors).

Building a kernel for `CircleInput`, `CircleOutput`, or `CircleConst` will throw an exception. It would be possible to make negative tests for those Ops using EXPECT_THROW.

**Comment by s-barannikov** [comment]
@jinevening Thank you for the idea. I will add them in other PR.

**Pull request merged**
