### PR TITLE
[onert] Supports UnidirectionalSequenceLSTM on base_loader

### PR DESCRIPTION
**Pull request by ragmani**
For issue #3851

This commit supports UnidirectionalSequenceLSTM on base_loader.
  - Apply variable tensor to LSTMLayer
  - Support UnidirectionalSequenceLSTM on base_loader

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Review by hseok-oh — APPROVED** [review]

**Comment by ragmani** [comment]
This PR needs #4655. I will do rebase after merge #4655

**Comment by ragmani** [comment]
I did rebase.

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by ragmani** [comment]
@glistening PTAL

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
