### PR TITLE
[common-artifacts] Exclude SVDF

### PR DESCRIPTION
**Pull request by seanshpark**
This will exclude tests for SVDF Op.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For  #8203

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Comment by BalyshevArtem** [comment]
Q:
According to #8279 there is also `res/TensorFlowLiteRecipes/Part_Add_SVDF_000/test.recipe` and according to https://github.com/Samsung/ONE/pull/8231#discussion_r782575151 I will add `SVDF_001/test.recipe`  - that is why should we add them to this PR?

**Comment by seanshpark** [comment]
> According to #8279 there is also res/TensorFlowLiteRecipes/Part_Add_SVDF_000/test.recipe

Thanks for point this!
I think I forgot this one. But I think it's OK as `Part_Add_SVDF_000` will be used when partition codes. I'll post in another PR.

> according to #8231 (comment) I will add SVDF_001/test.recipe - that is why should we add them to this PR?

Yes, after this lands, please post `SVDF_001` recipe PR :)

**Pull request merged**
