### PR TITLE
[infra] temporary fix of nncc docker build script

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit is temporary fix of nncc docker build script.

setuptools lastest version has got some bugs as of now.

Related : #4052 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM!!

**Comment by hseok-oh** [comment]
I don't think this can resolve issue #4052 becuase 
- Current docker image built 5 month ago
- Compile test phase don't use docker image

**Comment by seanshpark** [comment]
> I don't think this can resolve issue #4052 becuase

Besides this patch is needed for now. Let's take some time and find out.

**Pull request merged**
