### PR TITLE
[luci] numOutputs for CircleCustom

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise CircleCustom Op to provide number of outputs.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
This patch is to revise CircleCustom to look like other multi-output IRs.

**Comment by seanshpark** [comment]
Related: #6030

**Review by mhs4670go — APPROVED** [review]
LGTM

@seanshpark 
Just curiosity, `loco::succs()` method isn't enough?

**Comment by seanshpark** [comment]
> Just curiosity, loco::succs() method isn't enough?

Using `loco::succs()` is enough. Just to provide explicit method for number of outputs like other multi-output IRs.

**Pull request merged**
