### PR TITLE
[moco-log] Add exclude.me

### PR DESCRIPTION
**Pull request by seanshpark**
This will add exclude.me to exclude this module from build.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #11814 , from  #11848

**Review by jinevening — APPROVED** [review]
I think 1 approval is enough for this kind of PR :)

**Comment by seanshpark** [comment]
> I think 1 approval is enough for this kind of PR :)

Ah, thanks :)
Change itself is simple but I want to be sure this module is checked for necessity which I could miss.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
