### PR TITLE
[tfgraph-xform] Upgrade to tensorflow 1.13.1

### PR DESCRIPTION
**Pull request by hseok-oh**
Use tensorflow 1.13.1 source and prototext

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

For #2995

### CODE REVIEW

**Comment by hseok-oh** [comment]
I've checked on my local environment (build only)

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by parjong — APPROVED** [review]

**Comment by parjong** [comment]
Why don't you remove this project.

This project aims to import "constant folding pass" in the T/F into ONE, but it is no longer necessary as now ONE Compiler can access TensorFlow Python API.

**Comment by hseok-oh** [comment]
>This project was an attempt to integrate "constant folding pass" T/F into ONE, but it is no longer necessary as ONE Compiler can now access TensorFlow Python API.

Then it looks better to remove `tfgraph-xform`. @seanshpark , please give your opinion.

**Comment by seanshpark** [comment]
>  please give your opinion.

I think we can remove  `tfgraph-xform`

**Comment by hseok-oh** [comment]
OK. I'll close this PR

**Pull request closed without merging**
