### PR TITLE
[onert] Move wrong param axis of Split to inputs

### PR DESCRIPTION
**Pull request by ragmani**
For issue #4053

This commit moves wrong param axis of Split to inputs.

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Review by hyunsik-yoon — DISMISSED** [review]
It would be better if we have test cases for these ops (e.g., split, argmax, etc) when axis is not a const.

**Comment by ragmani** [comment]
> It would be better if we have test cases for these ops (e.g., split, argmax, etc) when axis is not a const.

Okay, I will add test cases.

**Review by hyunsik-yoon — APPROVED** [review]
LGTM :-)

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
