### PR TITLE
[tflite2circle] verify tflite file

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit enables tflite2circle to verify tflite file.

ONE-DCO-1.0-Signed-off-by: seongwoo mhs4670go@naver.com

### CODE REVIEW

**Comment by seanshpark** [comment]
@mhs4670go , your branch is from `mhs4670go:release/1.8.0` ...

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-debug @nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-debug

**Pull request closed without merging**
