### PR TITLE
[circledump] Fix static warnings

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit fixes static warnings in `circledump`.

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Review by YiHyunJin — APPROVED** [review]
LGTM

**Pull request merged**
