### PR TITLE
[nnfwapi] Rename everything to "NNFW API"

### PR DESCRIPTION
**Pull request by wateret**
Rename everything with "ONEAPI" to "NNFW API". This is to avoid
confusion on inconsistent names for the same thing.

ONE-DCO-1.0-Signed-off-by: Hanjoung Lee <hanjoung.lee@samsung.com>

### CODE REVIEW

**Comment by hyunsik-yoon** [comment]
Shouldn't we change `nnfw` to `one`? I am not sure why we need do it in reverse way.

**Comment by wateret** [comment]
@hyunsik-yoon 

The API file name is `nnfw.h` and all the APIs are prefixed with `nnfw_`. But these can't be easily changed.

Plus, there is an opinion - https://github.com/Samsung/ONE/issues/355#issuecomment-620084270.

**Comment by hyunsik-yoon** [comment]
@wateret,
Ah. Thanks for the explanation. now I understand the situation.

**Comment by wateret** [comment]
> How about move the contents of `docs/nnfw/howto/HowToUseONEAPI.md` to `docs/howto/how-to-use-api.md`? Currently, `docs/nnfw` and `docs/nncc` is remaining for just keeping old documents before migration to new documentation structure.

Will do as a separate commit, as this could cause a conflict with other PRs.

**Pull request merged**
