### PR TITLE
[luci-interpreter] Support for relu6 activation

### PR DESCRIPTION
**Pull request by ai-moiseev**
Add support for relu6 activation op in luci-interpreter.
For #1612

ONE-DCO-1.0-Signed-off-by: Alexander Moiseev <a.moiseev@samsung.com>

### CODE REVIEW

**Review by s-barannikov — COMMENTED** [review]
Could you please rework tests as in #4191? I.e. use makeInputTensor instead of using writeData.
This will save me some time later. Thanks in advance!

**Comment by ai-moiseev** [comment]
> Could you please rework tests as in #4191? I.e. use makeInputTensor instead of using writeData.
> This will save me some time later. Thanks in advance!

Sure! I'll convert this PR into draft for now and will update it shortly.

**Review by s-barannikov — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
