### PR TITLE
[onecc-docker] Dockerfile for onecc-docker

### PR DESCRIPTION
**Pull request by holawan**
This PR is a Dockerfile for Dockerizing onecc

ONE-DCO-1.0.-Signed-off-by: Dongwan Kim <asdf134652@gmail.com>

Co-authored-by: seunghui-lee <hithere1012@naver.com>
Co-authored-by: Junsu Kim <xofkdqkqh@naver.com>

issue: #9712, #9725
draft: #9736 
related_pr : #9772

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug nncc-release

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug nncc-release

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
