### PR TITLE
[res] gelu TF examples

### PR DESCRIPTION
**Pull request by seanshpark**
This will add TF examples for gelu operator

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For  #4033

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-debug

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@seanshpark Just in my opinion, even though of course we officially supports tensorflow 1.X, sometimes we run this python script with tensorflow 2.X, which throws an error because tensorflow 2.X needs to be eager execution disabled like this PR. How about adding the command that disables eager execution to python script by default?

**Comment by seanshpark** [comment]
> How about adding the command that disables eager execution to python script by default?

Need to get opinion from @parjong  :)

For me, I'm note sure about this at the moment...

**Comment by seanshpark** [comment]
Not sure why debug/release build fails... :(

**Comment by mhs4670go** [comment]
@seanshpark Hmmm.. neither no I..

**Comment by seanshpark** [comment]
close as another #4046 passed

**Pull request closed without merging**
