### PR TITLE
[luci/lang] support RoPE Operation

### PR DESCRIPTION
**Pull request by ys44kim**
this commit supports for RoPE operation in luc IR

ONE-DCO-1.0-Signed-off-by: youngsik kim <ys44.kim@samsung.com>

draft : #13978
issue : #13972

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> compiler/luci/partition/src/CircleOpCode.cpp:35:62: error: ‘BuiltinOperator_ROPE’ was not declared in this scope

**Comment by ys44kim** [comment]
circle schema : https://github.com/Samsung/ONE/pull/14013

**Comment by hseok-oh** [comment]
@nnfw-bot test tizen-gbs

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-release nncc-debug

**Comment by seanshpark** [comment]
> compiler/luci/partition/src/CircleOpCode.cpp:35:62: error: ‘BuiltinOperator_ROPE’ was not declared in this scop

**Pull request merged**
