### PR TITLE
[circle-quantizer] Support requantization from int8 to uint8

### PR DESCRIPTION
**Pull request by jinevening**
This supports requantization from int8 to uint8

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to #3779 Draft PR #3823

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
CC @mhs4670go 

@jinevening , is the options exclusive or can we run requantize with other options ?

**Comment by jinevening** [comment]
> @jinevening , is the options exclusive or can we run requantize with other options ?

This option is exclusive, which means that it should not run with `--quantize_dequantize_weights` or `--quantize_with_minmax`.

**Comment by seanshpark** [comment]
> This option is exclusive, which means that it should not run with --quantize_dequantize_weights or --quantize_with_minmax.

OK, if current implementation permits multiple options, please post changes to make exclusive in next PR.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
> please post changes to make exclusive in next PR.

I've uploaded #3964

**Pull request merged**
