### PR TITLE
[luci] Add DepthToSpace in tests

### PR DESCRIPTION
**Pull request by d-krylov**
Add DepthToSpace in luci tests

ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Maybe rebase to master
```
03:21:56       Start 64: luci_unit_readtest
03:21:57 64/75 Test #64: luci_unit_readtest .........................***Failed    1.05 sec
03:21:57 FAILED
03:21:57 - DepthToSpace_000
03:21:57 
03:21:57       Start 65: luci_unit_writetest
03:21:58 65/75 Test #65: luci_unit_writetest ........................***Failed    1.23 sec
03:21:58 FAILED
03:21:58 - DepthToSpace_000
03:21:58 
```

**Comment by binarman** [comment]
For some reason my chengeres in branch does not affect this PR, I will try to do it with @d-krylov tomorrow.
If we fail, we will close this and make another PR

**Comment by binarman** [comment]
Ok, this was my mistake. I improperly configured my local remotes =_=
Now it is ok

**Comment by seanshpark** [comment]
@binarman , can you review/approve?

**Comment by binarman** [comment]
@seanshpark
done! I just didn't wait for tests and went to sleep yesterday =)

**Pull request merged**
