### PR TITLE
[onert] Update NNAPI header

### PR DESCRIPTION
**Pull request by hseok-oh**
Update NNAPI header: android-11.0.0_r3

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: #4391

### CODE REVIEW

**Comment by hseok-oh** [comment]
@wateret @chunseoklee PTAL

**Comment by hseok-oh** [comment]
@wateret @chunseoklee PTAL

**Review by glistening — APPROVED** [review]
LGTM. @ragmani This PR introduces `ANEURALNETWORKS_IF` and `ANEURALNETWORKS_WHILE`.

**Review by ragmani — APPROVED** [review]
LGTM

**Review by wateret — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@chunseoklee PTAL

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
