### PR TITLE
[infra] Replace TFLite 2.3.0 cmake config for runtime

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit moves TFLite 2.3.0 build cmake and makes version

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot x64-builder

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-release
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
