### PR TITLE
[luci-interpreter] Add tests for gather

### PR DESCRIPTION
**Pull request by yunjayh**
This commit adds more tests for gather.

ONE-DCO-1.0-Signed-off-by: yunjayh <yunjayh@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@yunjayh , can you rebase to latest codes? Gather optimized kernel has landed.

**Comment by yunjayh** [comment]
Rebased! PTAL :D

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
