### PR TITLE
[model2nnpkg] Fix typo

### PR DESCRIPTION
**Pull request by hseok-oh**
Fix parsing error by typo in MANIFEST file

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
It will fix package test #4963

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-debug
@nnfw-bot test cross-runtime-test-release

**Review by glistening — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
Thanks for the fix !

**Pull request merged**
