### PR TITLE
MIN supports INT32 type

### PR DESCRIPTION
**Pull request by chunseoklee**
Now, MIN Layer supports INT32 type

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Review by ragmani — DISMISSED** [review]
LGTM

**Comment by ragmani** [comment]
Could you add a test for MIN int32 type?

**Comment by chunseoklee** [comment]
> Could you add a test for MIN int32 type?

Yes. 

Do you have any idea of this code : 

```
# minimum.mode.py
  17 def test(name, input0, input1, output0, input0_data, input1_data, output_data):
  18   model = Model().Operation("MINIMUM", input0, input1).To(output0)
  19 
  20   quant8 = DataTypeConverter().Identify({
  21       input0: ["TENSOR_QUANT8_ASYMM", 0.5, 127],
  22       input1: ["TENSOR_QUANT8_ASYMM", 1.0, 100],
  23       output0: ["TENSOR_QUANT8_ASYMM", 2.0, 80],
  24   })
  25 
  26   Example({
  27       input0: input0_data,
  28       input1: input1_data,
  29       output0: output_data,
  30   }, model=model, name=name).AddVariations("relaxed", "float16", "int32", quant8)
  31 
```

**Comment by wateret** [comment]
Please remove dot before `int32` in the filename.

**Comment by ragmani** [comment]
The kernel of acl cl for this operation doesn't support int32 type yet.

**Review by ragmani — APPROVED** [review]

**Pull request merged**
