### PR TITLE
[luci/svc] Revise CircleSlice shape inference

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise shape infernce of CircleSlice not to break,
where begin/size is not Constant but CircleSlice itself has all known shape.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
- for #12961

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
@seanshpark Could you take a look at https://github.com/Samsung/ONE/issues/12961#issuecomment-2092017685?

**Comment by seanshpark** [comment]
I think we can drop this change as with non-constant `begin`, `size` output should be dynamic.

**Pull request closed without merging**
