### PR TITLE
[luci-compute] Update compute kernel version

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit updates kernel version to TFLite v2.16.1.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
Fail on ubuntu 18.04 release build

```
[2024-05-29T07:25:42.618Z] onecc_006.test FAILED
script returned exit code 255
```

**Comment by hseok-oh** [comment]
In my environment (18.04 docker image), I tested 5 times but `one_006.test` is passed.

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
