### PR TITLE
Introduce tflite_run for tflite 2.2.0

### PR DESCRIPTION
**Pull request by YongseopKim**
- This is a temporal runner for tflite 2.2.0.
- Current tflite_run cannot use tflite 2.2.0 because of introduction for
nnapi delegate of tflite 2.2.0.
- To introduce this, the tflite_run_2_2_0 removes the dependency on
libtflite which has our own nnapi delegate comparing to the original
tflite_run.

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
## how to build
```
dragon@loki:~/Works/github/ONE$ OPTIONS="-DBUILD_TFLITE_RUN_2_2_0=ON" BUILD_TYPE=Release TARGET_ARCH=armv7l CROSS_BUILD=1 make -f Makefile.template clean configure build install
```

## how to run
<details><summary>inv3</summary>
```
odroid@odroid:/home/dragon/Works/github/ONE$ ./Product/out/bin/tflite_run_2_2_0 ./benchmark_nnpkg_models/inception_v3/inception_v3.tflite -w5 -r5
input tensor indices = [317,]
... warmup 1 takes 2255.59 ms
... warmup 2 takes 2142.69 ms
... warmup 3 takes 2143.44 ms
... warmup 4 takes 2152.53 ms
... warmup 5 takes 2141.2 ms
... run 1 takes 2144.24 ms
... run 2 takes 2141.95 ms
... run 3 takes 2141.08 ms
... run 4 takes 2133.23 ms
... run 5 takes 2127.97 ms
output tensor indices = [316(max:905),]
===================================
MODEL_LOAD   takes 12.534 ms
PREPARE      takes 0.849 ms
EXECUTE      takes 2137.696 ms
- MEAN     :  2137.696 ms
- MAX      :  2144.245 ms
- MIN      :  2127.968 ms
- GEOMEAN  :  2137.687 ms
===================================
```
```
odroid@odroid:/home/dragon/Works/github/ONE$ ./Product/out/bin/tflite_run_2_2_0 ./benchmark_nnpkg_models/inception_v3/inception_v3.tflite -m1 -w5 -r1
input tensor indices = [317,]
... warmup 1 takes 2408.01 ms
... warmup 2 takes 2325.22 ms
... warmup 3 takes 2328.31 ms
... warmup 4 takes 2325.23 ms
... warmup 5 takes 2319.86 ms
... run 1 takes 2133.47 ms
output tensor indices = [316(max:905),]
===================================
MODEL_LOAD   takes 12.462 ms
PREPARE      takes 0.944 ms
EXECUTE      takes 2133.475 ms
- MEAN     :  2133.475 ms
- MAX      :  2133.475 ms
- MIN      :  2133.475 ms
- GEOMEAN  :  2133.475 ms
===================================
RSS
- MODEL_LOAD   takes 1352 kb
- PREPARE      takes 10240 kb
- EXECUTE      takes 149534 kb
- PEAK         takes 149534 kb
===================================
HWM
- MODEL_LOAD   takes 1352 kb
- PREPARE      takes 10240 kb
- EXECUTE      takes 149534 kb
- PEAK         takes 149534 kb
===================================
PSS
- MODEL_LOAD   takes 1222 kb
- PREPARE      takes 8402 kb
- EXECUTE      takes 152002 kb
- PEAK         takes 152002 kb
===================================
```
</details>

<details><summary>mv2</summary>
```
odroid@odroid:/home/dragon/Works/github/ONE$ ./Product/out/bin/tflite_run_2_2_0 ./benchmark_nnpkg_models/mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.tflite -w5 -r5
input tensor indices = [173,]
... warmup 1 takes 164.216 ms
... warmup 2 takes 126.857 ms
... warmup 3 takes 126.412 ms
... warmup 4 takes 126.703 ms
... warmup 5 takes 126.085 ms
... run 1 takes 126.538 ms
... run 2 takes 126.216 ms
... run 3 takes 137.785 ms
... run 4 takes 127.016 ms
... run 5 takes 126.821 ms
output tensor indices = [62(max:491),]
===================================
MODEL_LOAD   takes 9.984 ms
PREPARE      takes 0.243 ms
EXECUTE      takes 128.875 ms
- MEAN     :  128.875 ms
- MAX      :  137.785 ms
- MIN      :  126.216 ms
- GEOMEAN  :  128.800 ms
===================================

```
```
odroid@odroid:/home/dragon/Works/github/ONE$ ./Product/out/bin/tflite_run_2_2_0 ./benchmark_nnpkg_models/mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.tflite -m1 -w5 -r1
input tensor indices = [173,]
... warmup 1 takes 152.6 ms
... warmup 2 takes 128.258 ms
... warmup 3 takes 128.929 ms
... warmup 4 takes 129.214 ms
... warmup 5 takes 128.303 ms
... run 1 takes 125.849 ms
output tensor indices = [62(max:491),]
===================================
MODEL_LOAD   takes 10.157 ms
PREPARE      takes 0.312 ms
EXECUTE      takes 125.849 ms
- MEAN     :  125.849 ms
- MAX      :  125.849 ms
- MIN      :  125.849 ms
- GEOMEAN  :  125.849 ms
===================================
RSS
- MODEL_LOAD   takes 1408 kb
- PREPARE      takes 4444 kb
- EXECUTE      takes 21323 kb
- PEAK         takes 21323 kb
===================================
HWM
- MODEL_LOAD   takes 1408 kb
- PREPARE      takes 4444 kb
- EXECUTE      takes 21323 kb
- PEAK         takes 21323 kb
===================================
PSS
- MODEL_LOAD   takes 1204 kb
- PREPARE      takes 4288 kb
- EXECUTE      takes 23758 kb
- PEAK         takes 23758 kb
===================================
```
</details>

**Comment by YongseopKim** [comment]
I'd like to get feedback about **the place** of `tflite_run_2_2_0`
- I put it on `tests/tools/`.
- In fact, this is a temp runner for tflite. When tflite 2.2.0 lands(is supported) officially on ONE, this will be removed.
- Therefore, this `tflite_run_2_2_0` could be `contrib/`.
- I'm wondering where to put it.

**Comment by glistening** [comment]
@YongseopKim 

> I'd like to get feedback about the place of tflite_run_2_2_0

I don't care about the place of `tflite_run` v2.2.0. However, I don't want to build `tflite_run_2_2.0` by default. It will increase required time to get `onert` because it will require downloading tensorflow 2.2.0 source and building tensorflow lite.

--- 
I also had same issue — my given model doesn't run with `tflite` v1.13. Thus, I built `tflite` from tensorflow v2.2.0 source using `make` or `bazel`. Then, it gives `benchmark_model` which measures time and memory, and per-operation profiling and more options.

**Comment by YongseopKim** [comment]
internal model result: [this](https://github.sec.samsung.net/gist/YongseopKim/7a3df77d5d293af3c00ae73847896037)

**Pull request merged**
