### PR TITLE
[runtime] Update runtime version to 1.26.0

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit updates runtime version to 1.26.0.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: #11484

### CODE REVIEW

**Review by ragmani — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
