### PR TITLE
[crew] Introduce write ini and find in PConfigIni

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce write_ini and find methods in PConfigIni.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6230, from draft #6231

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Review by Hyunjun85 — DISMISSED** [review]

**Review by juitem — APPROVED** [review]
LGTM

**Review by Hyunjun85 — APPROVED** [review]

**Review by juitem — APPROVED** [review]

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
