### PR TITLE
[common-artifacts] Revise circle2circle option

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise circle2circle option for optimization tests to include fold_dequantize.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #9479 , from #9480

**Comment by jinevening** [comment]
Can I ask why we need this change? Export of FLOAT16 is not supported?

**Comment by seanshpark** [comment]
> Can I ask why we need this change? Export of FLOAT16 is not supported?

`Net_Dequantize_Add_*` models have float16 tensors, which I intentionally didn't export this.
Reason is that our OneRT and TRIX don't support float16 so it would be an error.
(I think it would be better to add some comments to luci/export about this.)

So, what I could do for now is that, use `fold_dequantize` option and remove `float16` in `circle2circle` testing.
This PR is for this purpose.

**Comment by seanshpark** [comment]
I've posted #9506

**Comment by jinevening** [comment]
Thanks for the explanation.

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
