### PR TITLE
[onecc] Add to debian package

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit installs onecc binary to /usr/share/one/bin.
This file is also linked to /usr/bin/.

Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Related issue: #7299

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> 12:16:42 make[2]: *** No rule to make target '/opt/jenkins_slave/workspace/nnfw/master/pr-nncc-debug/compiler/one-cmds/onecc.template.cfg', needed by 'compiler/one-cmds/onecc.template.cfg'.  Stop.

**Comment by jyoungyun** [comment]
oh, I'm sorry. This PR has a dependency with #7319.
But I want to merge it first. So I removed the related code.
PTAL~~

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
