### PR TITLE
[onert] Introduce OptimizerCode

### PR DESCRIPTION
**Pull request by ragmani**
This commit introduces OptimizerCode.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by glistening** [comment]
@ragmani Could you please explain the role of `OptimizeCode`? Or if you have a draft, please refer to it.

**Comment by ragmani** [comment]
> Could you please explain the role of OptimizeCode? Or if you have a draft, please refer to it.

This is the type of optimizer to be used in onert. And optimizer types obtained through the API will be converted to this type.

**Comment by glistening** [comment]
Ah, it is `OptimizerType`. I guessed it is about the code the Optimizer generated.

**Review by glistening — APPROVED** [review]

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
