### PR TITLE
[luci] Support quantization of Pow

### PR DESCRIPTION
**Pull request by dayo09**
This commit supports quantization of Pow and its verification.

ONE-DCO-1.0-Signed-off-by: Dayoung Lee <dayg502@gmail.com>

-----

For #6367
Includes #6581 (The commit doesn't contain functional relations, but many merge conflicts are expected.)

### CODE REVIEW

**Comment by seanshpark** [comment]
```
[luci] Verify quantization of Sqrt …
[luci] Support quantization of Elu …
```
Maybe branch out not from master?

**Comment by dayo09** [comment]
@seanshpark 
Sorry, I forgot to put `PR/NO MERGE`.
It includes previous prs, because the prs on this test always crashes at merge, I just decided to put them in serial.

> Includes #6581 (The commit doesn't contain functional relations, but many merge conflicts are expected.)

**Comment by dayo09** [comment]
@seanshpark @jinevening Ready for review ;-D

**Review by jinevening — APPROVED** [review]
LGTM Thank you

**Comment by seanshpark** [comment]
I'll merge this after #6586 lands

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
