### PR TITLE
[res] Introduce Part_If_Add_Sub_001

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce Part_If_Add_Sub_001 recipe that has IF inside IF node.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6708, from draft #7223

**Comment by seanshpark** [comment]
IF `cond` is undefined... -_-;;;

image

**Comment by seanshpark** [comment]
Now 
image

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
