### PR TITLE
[test/nnfw_api] Fix nnfw_api_gtest fail on x86_64

### PR DESCRIPTION
**Pull request by hseok-oh**
Disable xnnpack backend test if xnnpack is not used

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Review by YongseopKim — APPROVED** [review]
LGTM

**Review by wateret — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@glistening PTAL

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
