### PR TITLE
[TFLiteVanillaRun] Apply cpuinfo to it

### PR DESCRIPTION
**Pull request by YongseopKim**
Build ruy with cpuinfo can use dotprod on arm64. Let's use it.

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
The effect of this pr for internal models: [this](https://github.sec.samsung.net/gist/YongseopKim/afaaf2bba3661411e101b1efe0d40a2d)

**Comment by YongseopKim** [comment]
PTAL @periannath

**Review by periannath — APPROVED** [review]
LGTM

**Comment by YongseopKim** [comment]
PTAL @chunseoklee

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
