### PR TITLE
Use version number 1.12.0

### PR DESCRIPTION
**Pull request by chunseoklee**
Use version 1.12.0 after merging this PR

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by chunseoklee** [comment]
This PR will(and should) be merged right after 1) #4922 is merged and 2) new branch(for 1.11.0) is created.

**Comment by hseok-oh** [comment]
Please change to `ready for review` if it ready to merge

**Comment by chunseoklee** [comment]
#4922 is ready to merge.

**Pull request merged**
