### PR TITLE
[infra/gbs] Change gbs.conf url to reference

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit changes gbs.conf url from latest to reference.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by YongseopKim — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
Why do you change url to reference?

**Comment by hseok-oh** [comment]
> Why do you change url to reference?

I don't know the exact reason, but recently ahub is updated to use this url.

**Pull request merged**
