### PR TITLE
[circle-part-eval] Run evaluation

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable evaluation of partition with test list.

Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6230, from draft #6231

**Comment by seanshpark** [comment]
> 14:32:34 Scanning dependencies of target circle_part_eval_prepare
14:32:34 make[2]: *** No rule to make target 'compiler/common-artifacts/Part_Add_Sub_000.tflite', needed by 'compiler/circle-part-eval/Part_Add_Sub_000/Part_Add_Sub_000.tflite'.  Stop.

@mhs4670go , do you have any idea what might be the problem? my local works OK...

**Comment by mhs4670go** [comment]
@seanshpark As I said in the messenger, I think this error happened because existing design didn't build it with right dependency tree. If `add_dependencies` works, I'll post an issue to discuss about this.

**Comment by seanshpark** [comment]
> add_dependencies(circle_part_eval_prepare common_artifacts_deps)

This was needed :)

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
