### PR TITLE
[luci/tests] Enable read/write for extended Buffer

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable read/write tests for extended Buffer.

### CODE REVIEW

**Comment by seanshpark** [comment]
- for #13674
- from #13615

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
circle dump of this model
```
$ ../../circledump/circledump Conv2D_006.circle
Dump: Conv2D_006.circle
...
Buffers: B(index) (length) values, if any; (length *) for ext_offset
...
B(3) (64 *) 00 00 0x80 0x3f 00 00 00 0x40 00 00 0x40 0xc0 00 00 0x80 0xc0 ...
B(4) (8 *) 00 00 0x80 0x3f 00 00 00 0x40 ...
...

$ ../../circledump/circledump Conv2D_006_w.circle
Dump: Conv2D_006_w.circle
...
Buffers: B(index) (length) values, if any; (length *) for ext_offset
...
B(2) (64 *) 00 00 0x80 0x3f 00 00 00 0x40 00 00 0x40 0xc0 00 00 0x80 0xc0 ...
B(3) (8 *) 00 00 0x80 0x3f 00 00 00 0x40 ...
...
```

**Review by shs-park — COMMENTED** [review]
👍

**Pull request merged**
