### PR TITLE
[onert] introduce ir::Sparsity

### PR DESCRIPTION
**Pull request by glistening**
Sparsity has several members. It will have its own structure.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

### CODE REVIEW

**Comment by glistening** [comment]
It is a part of #4128.

**Review by wateret — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
@wateret I've fixed a typo. PTAL.

```diff
@@ -43,7 +43,7 @@ public:
   /**
-   * @brief Returns indeces array. See compressed sparse row format.
+   * @brief Returns indices array. See compressed sparse row format.
    */
   const uint16_t *w1_indices() const { return _w1_indices.data(); }
```

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
