### PR TITLE
[pics] Introduce pics module

### PR DESCRIPTION
**Pull request by jinevening**
This introduces a pics module.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Draft PR: https://github.com/Samsung/ONE/pull/10283
Related to: #10281

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug

**Comment by hseok-oh** [comment]
```
13:35:16  112/118 Test #112: dalgona_single_op_test .....................***Failed    1.74 sec
13:35:16  -- Found DALGONA: /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-pipeline-debug@2/build/compiler/dalgona/dalgona
13:35:16  -- Found workdir: /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-pipeline-debug@2/build/compiler/common-artifacts
13:35:16  /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-pipeline-debug@2/build/compiler/common-artifacts /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-pipeline-debug@2/build/compiler/dalgona-test
13:35:16  /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-pipeline-debug@2/build/compiler/dalgona-test
13:35:16  FAILED
13:35:16  - Conv2D_000
13:35:16  - Conv2D_001
13:35:16  - Conv2D_002
13:35:16  - Conv2D_003
13:35:16  - Split_000
13:35:16  - InstanceNorm_000
13:35:16  
13:35:16          Start 113: circle2circle_dredd_recipe_test
```

@seanshpark Since setting `LUCI_LOG=100` env variable on debug test, `dalgona-test` sometimes randomly fails with above message.

**Comment by seanshpark** [comment]
>  sometimes randomly fails

maybe there exist uninitialized variable?

**Pull request merged**
