### PR TITLE
[one-cmds] Intruduce --remove-strided-slice command desciption

### PR DESCRIPTION
**Pull request by a-zh**
This commit introduce `--remove-strided-slice` command for `ONE` project

Signed-off-by: Anton Zhukov <anton.v.zhukov@gmail.com>

For https://github.com/Samsung/ONE/pull/5721

Draft: https://github.com/Samsung/ONE/pull/5876

### CODE REVIEW

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by a-zh** [comment]
@struss @seanshpark **PTL**

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by struss — APPROVED** [review]
LGTM

**Pull request merged**
