### PR TITLE
[debian] Add 1.16.1 changelog

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds 1.16.1 changelog.

Related: #6886 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
This PR is for land to master... maybe to 1.16.0 release branch?

**Comment by seanshpark** [comment]
Need to revise version to 1.16.1 ?
If so, I'll post PR with `compiler/vconone`.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@seanshpark 
> This PR is for land to master... maybe to 1.16.0 release branch?

I think this PR should be merged to both of master and 1.16.0. I posted #6891 as well.

**Pull request merged**
