### PR TITLE
[debian] Add execute permission

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds execute permission to rules file.

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-debug

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-debug

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
