### PR TITLE
[res] TF py examples of cond_1

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce TF python example of cond inside cond.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
From https://github.com/Samsung/ONE/issues/6708#issuecomment-881208691

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Comment by seanshpark** [comment]
> 11:16:28 FATAL: java.io.IOException: Remote call on JNLP4-connect connection from ip-172-31-16-125.ap-northeast-2.compute.internal/172.31.16.125:48578 failed
11:16:28 java.lang.InterruptedException

@hseok-oh , could you please take a look at this error?

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
