### PR TITLE
Use Arm Compute Library v20.05

### PR DESCRIPTION
**Pull request by ragmani**
This commit changes used acl version from v19.11.1 to v20.05.
  - Add including divided toolchanin headers
  - Indroduce CLDirectTransposeConvLayer
  - Disable applying correct_dims to input of softmax on acl_cl
  - Remove CLArgOperationKernel, CLCastKernel, CLDepthToSpaceKernel, CLGEMMLowpMatrixMultiplyKernelEx, CLNegKernel, CLPReLUKernel, CLSpaceToDepthKernel and CLTransposeConvLayerUpsampleKernel
  - Remove CPPUpsampleKernelEx, NECastKernel, NEDepthToSpaceLayerKernelEx, NEPReLUKernel and NESpaceToDepthLayerKernelEx
  - Remove CLArgOperation, CLBatchToSpaceND, CLCast, CLDepthToSpace, CLDirectTransposeConvLayer, CLLogicalNot, CLNeg, CLPReLU, CLPixelWiseDivision, CLRNNLayerEx, CLSpaceToDepth, CLStridedSliceEx and CLTransposeConvLayerUpsample
  - Remove CPPUpsampleEx, NECast, NEDepthToSpaceLayerEx, NEGEMMLowpMatrixMultiplyCoreEx, NEPReLU, NERNNLayerEx, NEReduceMeanEx, NESpaceToBatchLayerEx and NESpaceToDepthLayerEx
  - Update CLTransposeConvLayer, NETransposeConvLayer, CLFullyConnectedHybridLayer and NEFullyConnectedHybridLayer
  - Update skip list files of nnapi gtest for acl

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by wateret** [comment]
I think we need to decide whether including this in 1.7.0 or not. AFAIR we are going to create a branch for 1.7.0 tomorrow.

cc: @chunseoklee

**Comment by chunseoklee** [comment]
> I think we need to decide whether including this in 1.7.0 or not. AFAIR we are going to create a branch for 1.7.0 tomorrow.
> 
> 
> 
> cc: @chunseoklee 

Stay unless sth happens

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by ragmani** [comment]
@nnfw-bot test tizen-gbs-builder

**Pull request merged**
