### PR TITLE
[common-artifacts] Fix generate nnpackage depends

### PR DESCRIPTION
**Pull request by seanshpark**
This will fix cmake depends of generate nnpackage.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Without this change, every build time has ` Generate XXX nnpackage`
```
[ 73%] Generate CircleBatchMatMul_000 nnpackage
Generating nnpackage CircleBatchMatMul_000.opt in .
[ 73%] Generate InstanceNorm_000 nnpackage
Generating nnpackage InstanceNorm_000.opt in .
[ 73%] Generate InstanceNorm_001 nnpackage
```

`${MODEL_PATH}` is input file so adding to `DEPENDS` looks OK but don't know what the reason may be...

@mhs4670go , could you please double check this ?

**Comment by seanshpark** [comment]
#6502 has landed and this is not needed anymore.

**Comment by mhs4670go** [comment]
@seanshpark Actually, I don't know why this happen. As I know, there are two conditions where `cmake` re-run `add_custom_command`.
1. There's no `OUTPUT`
2. `DEPENDS` got old
But, `add_custom_command` in this PR already satisfied above two condition. So, one thing I can guess is that `cmake` doesn't consider a directory `OUTPUT` of `add_custom_command`.

To resolve this, I've tried to make directory first and then run `nnpackage`, which has done exactly what we wanted:) I'll post the PR.
```cmake
# Generate nnpackage directory
  add_custom_command(OUTPUT ${NNPKG_DIR}
      COMMAND ${CMAKE_COMMAND} -E make_directory ${NNPKG_DIR}
      DEPENDS ${MODEL_PATH}
      COMMENT "Generate ${RECIPE} nnpackage test directory"
    )
  list(APPEND TEST_DEPS ${NNPKG_DIR})

  add_custom_command(OUTPUT ${NNPKG_MODEL}
    COMMAND ${MODEL2NNPKG} ${MODEL_PATH}
    DEPENDS ${MODEL2NNPKG} ${MODEL_PATH} ${NNPKG_DIR}
    COMMENT "Generate ${RECIPE} nnpackage"
  )
  list(APPEND TEST_DEPS ${NNPKG_MODEL})
```

**Comment by seanshpark** [comment]
> #6502 has landed and this is not needed anymore.

Ah... I've got mixed up and closed this.. anyway #6515 is posted :)

**Pull request closed without merging**
