### PR TITLE
[infra] Update FP16

### PR DESCRIPTION
**Pull request by hseok-oh**
Let's update FP16 library.
This updated version is used for tensorflow 2.8, and change by this update includes for MSVC only.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Draft: #9500 
Related issue: #9632

### CODE REVIEW

**Comment by hseok-oh** [comment]
I added reviewer @seanshpark because `fp16` is used on compiler's `luci` and `souschef`.

**Comment by chunseoklee** [comment]
> change by this update includes only for MSVC only.

What do you mean by this sentense ?

**Comment by hseok-oh** [comment]
>What do you mean by this sentense ?

You can check diff by this PR on below link

https://github.com/Maratyszcza/FP16/commit/4dfe081cf6bcd15db339cf2680b9281b8451eeb3

This change is related with MSVC only.

**Review by seanshpark — APPROVED** [review]
LGTM :)

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
