### PR TITLE
[souschef] Unify gaussian generators

### PR DESCRIPTION
**Pull request by binarman**
This commit unifies float, int32_t and uint8_t gaussian generators.

ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@binarman , I think from #6533 , `as new method intruduction of template <typename T> std::vector<uint8_t> GenerateGaussian(int32_t count, float mean, float stddev)` wasn't enough to express what I wished...

For upcoming PRs, I would like you to do in some order to reduce misunderstanding and for simple and clear code understanding.
Each PR would be better to have single purpose: add, change, remove, for single subject.
And it is OK to have large lines of changes if the purpose is still single. 

Also it would be better to add an issue (for this PR, I think it is not necessary) to describe reason and background. And full draft code if there are multiple subject of changes. (#6533 seems to show the full code so no draft is needed for this case)

For this PR, I wish you could post in separate PRs:
- introduce new template method 
- revise existing codes to use new method
- add new codes that uses new types
- remove unused code if any

**Comment by binarman** [comment]
@seanshpark 
> For this PR, I wish you could post in separate PRs:

Hmm, in case I prefer to create issue, because number or required PRs growing too fast (first I thought that 2 will be enough)
Progress will be tracked in #6576

P.s.
> revise existing codes to use new method
> remove unused code if any

Probably this two PRs are actually one, because during revise old code will be removed.

**Comment by seanshpark** [comment]
> Probably this two PRs are actually one, because during revise old code will be removed.

Strictly speaking, there are 3 distinct actions: add new method, change existing code to use new method, remove old method.

**Comment by binarman** [comment]
> Strictly speaking, there are 3 distinct actions: add new method, change existing code to use new method, remove old method.

Ok! I was confused, because previously this rule was applied only to interfaces, but this PR affects only implementation in one file.

**Comment by seanshpark** [comment]
As there are time difference and applying too strict changes will make delay in progress.
I hope not to apply too many changes of purpose in one PR.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
If you like, you can merge this or get another approval :)

**Comment by binarman** [comment]
> As there are time difference and applying too strict changes will make delay in progress.

This is not so an urgent task. I just want to update infrastructure =)

I've already cut changes (and refactored them a little), so i would like to proceed in other PRs.
I am going to close this one after changes are merged, (consider this as a draft I guess)

**Comment by binarman** [comment]
Closing, everything from this PR is merged

**Pull request closed without merging**
