### PR TITLE
[angkor] Add NNCC_LIBRARY_NO_PIC option to CMakeLists.txt

### PR DESCRIPTION
**Pull request by SlavikMIPT**
This commit adds NNCC_LIBRARY_NO_PIC option to have an opportunity to disable POSITION_INDEPENDENT_CODE property.

ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov slavikmipt@gmail.com

### CODE REVIEW

**Review by m-bronnikov — DISMISSED** [review]
LGTM

**Review by jj-crypto — DISMISSED** [review]

**Comment by binarman** [comment]
CMake variable is renamed to comply with #8071

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by binarman — APPROVED** [review]

**Review by m-bronnikov — APPROVED** [review]
LGTM

**Pull request merged**
