### PR TITLE
[luci] Introduce copy_QuantParam

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce copy_QuantParam method.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #7627, from draft  #7627

**Review by jinevening — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug
@nnfw-bot test nncc-release

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-release

**Pull request merged**
