### PR TITLE
[circlechef] Use cmake variable for tools command

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise to use cmake variables for circlechef-file and
circlechef-reverse tools.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #8379, from draft #8407

**Review by ragmani — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@hyunsik-yoon PTAL

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Pull request merged**
