### PR TITLE
[res] Add PyTorchExamples of Linear

### PR DESCRIPTION
**Pull request by underflow101**
Parent Issue: #4830 
Fired Issue: #4889 

This commit adds PyTorch Example of nn.Linear.

Tested with `ptem,py` and passed the test.

Please review this PR, @seanshpark .
I'll be happy to get feedback and change to make improvement.

Thank you.

(Derived from SOS Mine Project)

Signed-off-by: underflow101 <ikarus125@gmail.com>

### CODE REVIEW

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
Ah, this conflicts with #4894

**Comment by seanshpark** [comment]
If you like, can you add `torch.matmul` to this PR? I'll close #4894

**Comment by underflow101** [comment]
> If you like, can you add `torch.matmul` to this PR? I'll close #4894

Okay, I'll do that.
But it makes me feel that I'm stealing your commit.... :(

**Comment by seanshpark** [comment]
> But it makes me feel that I'm stealing your commit.... :(

It's OK :) This was posted first

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
