### PR TITLE
[record-minmax] Use dio-hdf5 module

### PR DESCRIPTION
**Pull request by jinevening**
This replaces local HDF5Importer with dio-hdf5.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/8735
Draft PR: https://github.com/Samsung/ONE/pull/8736

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@jinevening , just a comment.
I see as there are multiple action of changes in this PR.
I hope you can divide them but as you may want to go as-is and I respect your decision, I'll land this.

What I see in this change are;
- replace `luci_interpreter` to `loco`
- adding link of `dio-hdf5`
- use `dio_hdf5/HDF5Importer.h` instead of `HDF5Importer.h`
- remove linking with `HDF5` in cmake
- remove `HDF5Importer.*` files

One or two maybe need to be together.

**Comment by jinevening** [comment]
@seanshpark Thank you for the kind suggestion. I'll make my future PRs have one purpose as much as possible.

**Pull request merged**
