### PR TITLE
[infra] Match package filename with foldername created on externals

### PR DESCRIPTION
**Pull request by juitem**
Change:
 cpuinfo  to CPUINFO
 eigen    to TENSORFLOW-2.3.0-EIGEN
 gemmlowp to GEMMLOWP
 gtest    to GTEST
 oourafft to OOURAFFT
 ruy      to RUY

Signed-off-by: Juitem JoonWoo Kim <jw1772.kim@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
I'm not a runtime guy but why do we need this change? It would be to have a link to some issue.

**Comment by juitem** [comment]
> I'm not a runtime guy but why do we need this change? It would be to have a link to some issue.

if filename and foldername exactly matches,
we can try extract files first without trying to download from internet.
which will enable build on gbs with the same makefile without adding additional changes on nnfw.spec

ex) additional code for ExternalSourceTools
```
  # Try copy from packging directory first
  if(NOT EXISTS "${CACHE_DIR}")
    file(MAKE_DIRECTORY "${CACHE_DIR}")
  endif()
  if(NOT EXISTS "${OUT_DIR}" OR NOT URL_CHECK)
    set(BUILTIN_PKGS_PATH "${NNAS_PROJECT_SOURCE_DIR}/packaging")
    if(EXISTS "${BUILTIN_PKGS_PATH}/${DIRNAME}.tar.gz")
      SET(BUILTIN_PKG_PATH "${BUILTIN_PKGS_PATH}/${DIRNAME}.tar.gz")
    endif()
    string(TOLOWER ${DIRNAME} DIRNAME_LOWER)
    if(EXISTS "${BUILTIN_PKGS_PATH}/${DIRNAME_LOWER}.tar.gz")
      SET(BUILTIN_PKG_PATH "${BUILTIN_PKGS_PATH}/${DIRNAME_LOWER}.tar.gz")
    endif()

    if(EXISTS "${BUILTIN_PKG_PATH}")
      execute_process(COMMAND ${CMAKE_COMMAND} -E tar xfz ${BUILTIN_PKG_PATH}
                    WORKING_DIRECTORY "${CACHE_DIR}")
      message(STATUS " ExternalSource: Found archive from pacakaging folder" )
    endif()

    Stamp_Check(URL_CHECK "${STAMP_PATH}" "${URL}")
  endif()
```

Of course, this commit will not resolve gbs build issues at once, this can be the first step

**Comment by chunseoklee** [comment]
@juitem I am OK with this patch. But, I prefer keeping  ExternalSourceTools' s logic via stamp file. 
Could you please show me what nnfw.spec file looks like after patch ? (IMHO, nnfw.spec looks similar after modifying  ExternalSourceTools)

**Comment by juitem** [comment]
> @juitem I am OK with this patch. But, I prefer keeping ExternalSourceTools' s logic via stamp file.

I'm not sure if the patch should be placed inside of ExternalSourceTools,
but I think we don't need to download the files already we have on packaging directory.
if stamp value written in each makefile and archive's stamp mismatches, and then ExternalSourceTools's logic will
download from internet.

>  Could you please show me what nnfw.spec file looks like after patch ? (IMHO, nnfw.spec looks similar after modifying ExternalSourceTools)

yes, there's only small a change for now.
we can keep nnfw.spec or can remove 'Source1002~1015'

regardless of additional patch on ExternalSourceTools,
I think rename 'eigen.tar.gz' to 'TENSORFLOW-2.3.0-EIGEN.tar.gz' looks more clear.

```
diff --git a/infra/cmake/modules/ExternalSourceTools.cmake b/infra/cmake/modules/ExternalSourceTools.cmake
index 0bfbaa33b..277484d3d 100644
--- a/infra/cmake/modules/ExternalSourceTools.cmake
+++ b/infra/cmake/modules/ExternalSourceTools.cmake
@@ -39,6 +39,29 @@ function(ExternalSource_Download PREFIX)
   # Compare URL in STAMP file and the given URL
   Stamp_Check(URL_CHECK "${STAMP_PATH}" "${URL}")
 
+  # Try copy from packging directory first
+  if(NOT EXISTS "${CACHE_DIR}")
+    file(MAKE_DIRECTORY "${CACHE_DIR}")
+  endif()
+  if(NOT EXISTS "${OUT_DIR}" OR NOT URL_CHECK)
+    set(BUILTIN_PKGS_PATH "${NNAS_PROJECT_SOURCE_DIR}/packaging")
+    if(EXISTS "${BUILTIN_PKGS_PATH}/${DIRNAME}.tar.gz")
+      SET(BUILTIN_PKG_PATH "${BUILTIN_PKGS_PATH}/${DIRNAME}.tar.gz")
+    endif()
+ #
+ # remove case-lower, if all archive names are matched.
+ #
+ #
+    if(EXISTS "${BUILTIN_PKG_PATH}")
+      execute_process(COMMAND ${CMAKE_COMMAND} -E tar xfz ${BUILTIN_PKG_PATH}
+                    WORKING_DIRECTORY "${CACHE_DIR}")
+      message(STATUS " ExternalSource: Found archive from pacakaging folder" )
+    endif()
+
+    Stamp_Check(URL_CHECK "${STAMP_PATH}" "${URL}")
+  endif()
+

   if(NOT EXISTS "${OUT_DIR}" OR NOT URL_CHECK)
     file(REMOVE "${STAMP_PATH}")
     file(REMOVE_RECURSE "${OUT_DIR}")

diff --git a/packaging/eigen.tar.gz b/packaging/TENSORFLOW-2.3.0-EIGEN.tar.gz
similarity index 100%
rename from packaging/eigen.tar.gz
rename to packaging/TENSORFLOW-2.3.0-EIGEN.tar.gz

diff --git a/packaging/nnfw.spec b/packaging/nnfw.spec
index 0d170e7ed..2aeed5362 100644
--- a/packaging/nnfw.spec
+++ b/packaging/nnfw.spec
@@ -8,20 +8,6 @@ License: Apache-2.0 and MIT and BSD-2-Clause
 Source0: %{name}-%{version}.tar.gz
 Source1: %{name}.manifest
 Source1001: nnapi_test_generated.tar.gz
-Source1002: gtest.tar.gz
-Source1003: eigen.tar.gz
-Source1004: gemmlowp.tar.gz
-Source1005: ruy.tar.gz
-Source1006: cpuinfo.tar.gz
-Source1007: XNNPACK.tar.gz
-Source1008: FXDIV.tar.gz
-Source1009: PTHREADPOOL.tar.gz
-Source1010: PSIMD.tar.gz
-Source1011: FP16.tar.gz
-Source1012: OPENCL_HEADERS.tar.gz
-Source1013: FARMHASH.tar.gz
-Source1014: ABSEIL.tar.gz
-Source1015: oourafft.tar.gz
 Source2001: nnfw.pc.in
 Source2002: nnfw-plugin.pc.in
 
@@ -123,20 +109,6 @@ NNFW test rpm. It does not depends on nnfw rpm since it contains nnfw runtime.
 cp %{SOURCE1} .
 mkdir ./externals
 tar -xf %{SOURCE1001} -C ./tests/nnapi/src/
-tar -xf %{SOURCE1002} -C ./externals
-tar -xf %{SOURCE1003} -C ./externals
-tar -xf %{SOURCE1004} -C ./externals
-tar -xf %{SOURCE1005} -C ./externals
-tar -xf %{SOURCE1006} -C ./externals
-tar -xf %{SOURCE1007} -C ./externals
-tar -xf %{SOURCE1008} -C ./externals
-tar -xf %{SOURCE1009} -C ./externals
-tar -xf %{SOURCE1010} -C ./externals
-tar -xf %{SOURCE1011} -C ./externals
-tar -xf %{SOURCE1012} -C ./externals
-tar -xf %{SOURCE1013} -C ./externals
-tar -xf %{SOURCE1014} -C ./externals
-tar -xf %{SOURCE1015} -C ./externals
 
 %build
 %ifarch arm armv7l aarch64 x86_64 %ix86
```

**Comment by hseok-oh** [comment]
>I think we don't need to download the files already we have on packaging directory.

Archives files in `packaging/` directory is temporary solution for tizen build system. Don't forget that this repo's main target is not restricted on tizen. On maintainer's view, I want to minimize binary files on git repo. 

>regardless of additional patch on ExternalSourceTools,
I think rename 'eigen.tar.gz' to 'TENSORFLOW-2.3.0-EIGEN.tar.gz' looks more clear.

Agree

**Review by chunseoklee — APPROVED** [review]

**Review by hseok-oh — APPROVED** [review]

**Review by jj-crypto — APPROVED** [review]

**Pull request merged**
