### PR TITLE
[luci] Revise BatchNormPatternFinder test

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise BatchNormPatternFinder pass test with TestIOGraph.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6110, from #6111

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
CC @jinevening

**Pull request merged**
