### PR TITLE
[tests/nnfw_api] Introduce GenModelTrain class

### PR DESCRIPTION
**Pull request by YongseopKim**
This commit introduces GenModelTrain class and others for it.

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

---

draft: https://github.com/Samsung/ONE/pull/12665

### CODE REVIEW

**Comment by YongseopKim** [comment]
After this, I'll pr one test with GenModelTrain.

**Comment by YongseopKim** [comment]
PTAL @Samsung/one_onert

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
