### PR TITLE
[luci-interpreter] Add KernelsToBuild.lst to pal\mcu.

### PR DESCRIPTION
**Pull request by SlavikMIPT**
This commit adds KernelsToBuild.lst to pal\mcu

ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <slavikmipt@gmail.com>

### CODE REVIEW

**Review by binarman — APPROVED** [review]
LGTM, see https://github.com/Samsung/ONE/pull/7717/files#diff-673ed217b83737871607462975c58318aeadc8611003f448c5e4b9223c036607 for full list we can support at this moment (using reference implementations, not cmsis)

**Comment by seanshpark** [comment]
Just curious, why use back slash ?

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Comment by SlavikMIPT** [comment]
> Just curious, why use back slash ?

windows user)

**Pull request merged**
