### PR TITLE
[infra/onert] Fix buildtool build bug

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit fixes buildtool build fail by invalid download option.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@seanshpark Packaging job is failed by this runtime bug.

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Pull request merged**
