### PR TITLE
Script to benchamrk adb/sdb target on host

### PR DESCRIPTION
**Pull request by chunseoklee**
ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by wateret** [comment]
I guess `test/scripts` would be more proper directory for this file?

**Comment by wateret** [comment]
Do you want to keep the path as-is?

**Comment by wateret** [comment]
@nnfw-bot test all

**Comment by ragmani** [comment]
@nnfw-bot test format-checker

**Pull request merged**
