### PR TITLE
[onecc] Add subcommand test cases

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds some test cases for subcommand of onecc.

Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Related issue: #7299
Draft PR: #7303

### CODE REVIEW

**Comment by jyoungyun** [comment]
Test result:

```
# ./test/runtestall.sh
onecc_001.test SUCCESS
onecc_002.test SUCCESS
onecc_003.test SUCCESS
onecc_004.test SUCCESS
onecc_005.test SUCCESS
onecc_006.test SUCCESS
onecc_007.test SUCCESS
onecc_008.test SUCCESS
onecc_009.test SUCCESS
onecc_010.test SUCCESS
onecc_011.test SUCCESS
onecc_012.test SUCCESS
onecc_013.test SUCCESS
onecc_014.test SUCCESS
onecc_015.test SUCCESS
onecc_016.test SUCCESS
onecc_017.test SUCCESS
onecc_018.test SUCCESS
onecc_019.test SUCCESS
onecc_020.test SUCCESS
onecc_neg_001.test SUCCESS
onecc_neg_002.test SUCCESS
onecc_neg_003.test SUCCESS
onecc_neg_004.test SUCCESS
onecc_neg_005.test SUCCESS
onecc_neg_006.test SUCCESS
onecc_neg_007.test SUCCESS
ALL TESTS PASSED!
```

**Comment by jyoungyun** [comment]
PTAL. Thanks!
/cc @mhs4670go @seanshpark

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
