### PR TITLE
Release note 1.22.0

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit is a release note for 1.22.0.

Related: #10540 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
This PR should be merged after #10544

**Review by seanshpark — DISMISSED** [review]
LGTM

**Review by jinevening — DISMISSED** [review]
LGTM

**Comment by mhs4670go** [comment]
@seanshpark All the tests and static analysis for release has passed. Please merge plz:)

**Review by lemmaa — APPROVED** [review]
LGTM. Thanks!

**Comment by lemmaa** [comment]
Since there is no change except for the file name, merge based on the existing approval.

**Pull request merged**
