### PR TITLE
[one-cmds] Add Fold Gather pass to one-cmds

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This pr adds fold gather pass to one-cmds. This pass can remove Gather operation which can be folded

draft: https://github.com/Samsung/ONE/pull/8682
for issue: https://github.com/Samsung/ONE/issues/8375

ONE-DCO-1.0-Signed-off-by: Artem Balyshev a.balyshev@partner.samsung.com

### CODE REVIEW

**Comment by BalyshevArtem** [comment]
This pr should be rebased after https://github.com/Samsung/ONE/pull/8720 will be merged

**Review by jinevening — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]

**Comment by BalyshevArtem** [comment]
@seanshpark, I think we can merge this pr

**Comment by seanshpark** [comment]
@BalyshevArtem , just curious, I think all your commit message has also `
Co-authored-by: Artem Balyshev <a.balyshev@partner.samsung.com>` . Could you please explain why you add this?

**Comment by BalyshevArtem** [comment]
> just curious,

Oh, sorry, I think its this is added automatically, due to I rebased these prs from another computer, I will try to make sure that it is not added anymore :)

**Pull request merged**
