### PR TITLE
[luci] Remove luci namespace from operators list

### PR DESCRIPTION
**Pull request by binarman**
This commit removes lusi:: namespace from CircleNodes.lst.

For #7288

ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by binarman** [comment]
This is related to luci-interpreter KernelBuilder refactoring.
I have two possible variants for now: #7298 (this PR is part of this) and #7338

I am still trying to invent best solution, because both existing have some disadvantages.

**Comment by seanshpark** [comment]
@binarman , I can't catch why this change is needed, can you please explain a bit?
Change it self seems OK.

**Comment by binarman** [comment]
> @binarman , I can't catch why this change is needed, can you please explain a bit?
Change it self seems OK.

This PR is definitely confusing =)
This is why I worked on different solutions yesterday.

Back to your question:

**Prerequisites**
This change is part of #7298.

in #7288 (luci-interpreter for MCU) we want to make luci-interpreter build-time configurable (compile only needed kernels, instead of all collection).
For this we need:
1) Select only needed source files in cmake.
2) Generate KernelBuilder with only needed visit methods.

@Bronnikoff proposed to use configuration file with list of needed operators (see https://github.com/Samsung/ONE/pull/7289/files#diff-aeca1300daf2df3fa6dc67ca4b218d7e7978dbe0a138ae4e5f83c6fea5d4ddbd)
This file should be included in both CMake (select files to compile) and KernelBuilder visitor.

**Problem**
Original solution removed KernelBuilder refactoring you did some time ago (by introducing smaller "KernelBuilderLets") this dropped SAM score.

**My solution**
To fit both analysis and configurability I proposed to replace traditional visitor with builder registry that maps opcode to builder function (different implementations in #7298 (this PR is part of this), #7338 and #7339).
So we first fill builder registry with pairs (opcode, builder_function)
when we want to generate kernel we gets builder by opcode and calls it.

**FINALLY, THE ANSWER**
Original configuration file contains only kernel name, but BuilderRegistry from my solution needs both **opcode** and builder name to be filled, I used `luci/IR/CircleNodes.lst` to get opcode information from kernel name.
Unfortunately `luci::` prefix gets in the way =(

P.s. I hope we will use different solution (one of #7338 and #7339), so I'll close this PR.

**Comment by binarman** [comment]
oops, forgot to add mention
@seanshpark

**Comment by binarman** [comment]
This draft is implemented and merged in other PR. closing

**Pull request closed without merging**
