### PR TITLE
Fix coverity 1148326

### PR DESCRIPTION
**Pull request by chunseoklee**
- Fix coverity 1148326

Change-Id: I98d2ff22050078bd8a392a58904b968965c1c46d
Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
Will we merge this PR? We need one more approve.

**Comment by chunseoklee** [comment]
> Will we merge this PR? We need one more approve.

Yes. This patch is already merged on tizen repo.

**Comment by chunseoklee** [comment]
PTAL @Samsung/nnfw

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
