### PR TITLE
[onert] Use try block in train_prepare

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit uses try block in train_prepare.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Draft: #11035

### CODE REVIEW

**Comment by jyoungyun** [comment]
I would like to use throw error when loss type is not supported at runtime.
To do this, move the existing code inside try block.

```
try {
  auto convertLossType = [](const int &type) {
    if (type == NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR)
      return onert::ir::operation::Loss::Type::MEAN_SQUARED_ERROR;
    if (type == NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY)
      return onert::ir::operation::Loss::Type::CATEGORICAL_CROSSENTROPY;
    else
      throw std::runtime_error("not supported loss type");
  };

  onert::compiler::train::LossInfo loss_info;
  loss_info.type = convertLossType(tinfo.loss);

  onert::compiler::train::TrainingInfo training_info;
  training_info.setBatchSize(tinfo.batch_size);
  training_info.setLossInfo(loss_info);
}
catch {}
```

**Review by ragmani — DISMISSED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]

**Comment by jyoungyun** [comment]
I rebased this PR, please review again.

**Review by ragmani — APPROVED** [review]

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
