### PR TITLE
DRAFT lcov for compiler

### PR DESCRIPTION
**Pull request by seanshpark**
To make a line coverage report for compiler of 2020

Signed-off-by: SaeHie Park <saehie.park@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@hseok-oh , PTAL

**Comment by hseok-oh** [comment]
@seanshpark I got below error on configure

```
CMake Error at /home/nfs/git/ONE/compiler/circlechef/tests/CMakeLists.txt:67 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:circle-verify>

  No target "circle-verify"


-- Generating done
-- Build files have been written to: /home/nfs/git/ONE/build/nncc
```

**Comment by seanshpark** [comment]
@hseok-oh , I've added `circle-verify` . please check again

**Comment by hseok-oh** [comment]
@seanshpark 
I'll make PR for configure script (for build item maintain).
Build, test, and coverage report will run by CI script.

**Comment by seanshpark** [comment]
Close as CI provides coverage report :)

**Pull request closed without merging**
