### PR TITLE
[onert] Fix incorrect result of Cast op with bool type input in acl_cl backend

### PR DESCRIPTION
**Pull request by ragmani**
For issue #4309

This commit fixes results mismatch errors when using cast ops with bool type input.
  - Add a acl_cl kernel for cast operation with bool type input
  - Applied the kernel
  - Add some nnfw_api testcases

### CODE REVIEW

**Review by wateret — CHANGES_REQUESTED** [review]
LGTM, but please add negative test cases(2 or more). It is due to the release criteria. 😞

**Comment by ragmani** [comment]
> LGTM, but please add negative test cases(2 or more). It is due to the release criteria. disappointed

@wateret 
How to create negative test cases unexpected result?

**Comment by ragmani** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by wateret** [comment]
Negative tests are not necessarily relevant to this PR. This is just for release criteria, to continuously keep the ratio of positive and negative TCs. You can also add negative tests with a separate PR.

It is announced in #41 .

> - The number of **negative test cases** must be equal or greater than the **positive ones**.
>     - **I won't accept the commits that only contain positive tests**
>

**Comment by wateret** [comment]
For example, these days I started making some invalid models - https://github.com/Samsung/ONE/blob/master/tests/nnfw_api/src/one_op_tests/LogSoftmax.cc

**Comment by ragmani** [comment]
> Negative tests are not necessarily relevant to this PR. This is just for release criteria, to continuously keep the ratio of positive and negative TCs. You can add negative tests with a separate PR if irrelevant, but please make them at the same time.

@wateret 
To add some irrelevant negative tests to this PR such as invalid model tests, I have to add some commits that fix error handling for the invalid model. It would make this PR big and multirole for fixing two or more error. Is it right?

**Review by wateret — APPROVED** [review]
LGTM, agreed on adding negative tests after landing.

**Pull request merged**
