### PR TITLE
[record-minmax-thread-safety-test] Upgrade TF to 2.12.1

### PR DESCRIPTION
**Pull request by seanshpark**
This will upgrade test environment TF to 2.12.1.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #11255 , from draft  #11278

**Review by jinevening — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-jammy-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Pull request merged**
