### PR TITLE
[luci-value-test] Enable CumSum operation

### PR DESCRIPTION
**Pull request by batcheu**
This enables CumSum operation in luci value test.

ONE-DCO-1.0-Signed-off-by: Jonghwa Lee <jonghwa3.lee@samsung.com>

---
Realated w/ : #11842 
Draft PR : #11810

### CODE REVIEW

**Comment by seanshpark** [comment]
`tcgenerate(CumSum_000)` exist... is it OK?

**Comment by batcheu** [comment]
> `tcgenerate(CumSum_000)` exist... is it OK?

Yes, Both of build and test works just fine :)

**Comment by batcheu** [comment]
> > `tcgenerate(CumSum_000)` exist... is it OK?
> 
> Yes, Both of build and test works just fine :)

I don't fully understand how all tests are configured, but it seems `luci-value-test` doesn't have dependency with common-artifact generation. The evaluation seems to be done by `luci_eval_verifier.py` (wo/ testDataGenerator) script which generates random input data by itself.

```cmake
if(NOT CMAKE_CROSSCOMPILING)
  get_target_property(ARTIFACTS_BIN_PATH testDataGenerator BINARY_DIR)
  add_test(NAME luci_value_test
    COMMAND "${CMAKE_CURRENT_SOURCE_DIR}/evalverify.sh"                   // execute evalverify.sh
            "${CMAKE_CURRENT_BINARY_DIR}"
            "${ARTIFACTS_BIN_PATH}"
            "${NNCC_OVERLAY_DIR}/venv_2_12_1"
            "$<TARGET_FILE:luci_eval_driver>"
            ${LUCI_VALUE_TESTS}
  )
  ...
  endif()
```
```sh
# evalverify.sh
15 VERIFY_SCRIPT_PATH="${VERIFY_SOURCE_PATH}/luci_eval_verifier.py"      
...
38    source "${VIRTUALENV}/bin/activate"                                                                            
39    "${VIRTUALENV}/bin/python" "${VERIFY_SCRIPT_PATH}" \             // execute luci_eval_verifier.py                                              
40   --driver "${INTERPRETER_DRIVER_PATH}" \                                                                        
41    --model "${TESTCASE_FILE}"                
```

```python
# luci_eval_verifier.py
57  # Generate random input data. 
58  num_inputs = len(interpreter.get_input_details())
...
93     interpreter.set_tensor(input_details["index"], input_data)
94     input_data.tofile(circle_model + ".input" + str(i))
95     input_details["shape"].tofile(circle_model + ".input" + str(i) + ".shape", sep=',')
96     with open(circle_model + ".input" + str(i) + ".dtype", 'w') as dtype_file:
97         dtype_file.write(input_dtype)

102  # Execute luci interpreter.
103  subprocess.run(
104     [
105         driver, circle_model,
106         str(num_inputs), circle_model + ".input", circle_model + ".output"
107     ],
108     check=True)


```

However,

**Comment by seanshpark** [comment]
in `common-artifacts`, `tcgenerate()` looks like it's for `nnpackage test`
```
  if(NOT DEFINED NO_TCGEN_${RECIPE})
    # Generate test directory
    set(TC_DIRECTORY "${NNPKG_DIR}/metadata/tc")
    add_custom_command(OUTPUT ${TC_DIRECTORY}
      COMMAND ${CMAKE_COMMAND} -E make_directory ${TC_DIRECTORY}
      COMMENT "Generate ${RECIPE} nnpackage test directory"
    )
```

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
