### PR TITLE
DRAFT: Make negative BN gamma to positive

### PR DESCRIPTION
**Pull request by jinevening**
On going draft to make a pass to enforce positive batchnorm gamma

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: #4773

### CODE REVIEW

**Comment by jinevening** [comment]
### Background

`FusePreActivationBatchNormPass` can be applied only when batchnorm gamma is positive. `MakeBatchNormGammaPositivePass` manually changes negative gamma to positive, allowing users to apply `FusePreActivationBatchNormPass` for those models with negative gammas.

As depicted in the comment, this pass can change the execution result, so users should carefully use this pass.

**Comment by seanshpark** [comment]
Code looks OK

**Comment by mhs4670go** [comment]
@jinevening This pass uses only when user want to run `FusePreActivationBatchNormPass` Pass? If so, how about making these two pass into anther one pass? Not codes level, interface level.

**Comment by jinevening** [comment]
> If so, how about making these two pass into anther one pass?

That was my first plan :) I've changed my mind after conversation with @parjong . He said that we had better make `MakeBatchNormGammaPositivePass` as a separate pass and make a user decide whether to use this option or not.

**Comment by mhs4670go** [comment]
@jinevening Right. I thought if `FusePreActivationBatchNormPass` is the only pass that follows `MakeBatchNormGammaPositivePass`, the decision whether to use `MakeBatchNormGammaPositivePass` or not is same with the one whether to use `ONE_PASS_INCLUDING_TWO_PASS` or not. Maybe it seems not the only one I guess as the conversion you said above.

**Comment by jinevening** [comment]
> Okay. I thought if FusePreActivationBatchNormPass is the only pass that follows MakeBatchNormGammaPositivePass, the decision whether to use MakeBatchNormGammaPositivePass or not is same with the one whether to use ONE_PASS_INCLUDING_TWO_PASS or not. Maybe it seems not the only one I guess as the conversion you said above.

My explanation might have confused you. `FusePreActivationBatchNormPass` is an independent pass. It can be used without `MakeBatchNormGammaPositivePass`. It will remove batchnorm with non-negative gamma and leave batchnorm with negative gamma.

`MakeBatchNormGammaPositivePass` just helps to increase the applicability of `FusePreActivationBatchNormPass` for some special models that the change does not affect the model accuracy (e.g., ResNet V2).

**Pull request closed without merging**
