### PR TITLE
[infra] Introduce nncc install command

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduces nncc install command.
It simplifies nncc install path setting on local environment by using "--prefix" option.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
Example) Install nncc to `build/out` directory

```
export NNCC_WORKSPACE=build/nncc
./nncc configure -DCMAKE_BUILD_TYPE=Release -DEXTERNALS_BUILD_THREADS=8
./nncc build -j8
./nncc install --prefix build/out
```

**Comment by seanshpark** [comment]
What I do with `nncc`
```
(1) NNCC_WORKSPACE=$(BUILD_TYPE_FOLDER) ./nncc configure (options) \
		-DCMAKE_INSTALL_PREFIX="$(LOCAL_INSTALL_FOLDER)"

(2) NNCC_WORKSPACE=$(BUILD_TYPE_FOLDER) ./nncc build

(3) NNCC_WORKSPACE=$(BUILD_TYPE_FOLDER) ./nncc build install
```
- (2) can be omitted


@hseok-oh , can you please share your problem for adding `install` ?

**Comment by hseok-oh** [comment]
Not have a problem. But it can help to decide or change install path after build.

**Comment by seanshpark** [comment]
> Not have a problem. But it can help to decide or change install path after build.

Thanks for the explanation. code itself looks OK.
I don't have any objection for adding this file but I cannot decide this by my self.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
