### PR TITLE
[luci] Enable passes for module optimizations

### PR DESCRIPTION
**Pull request by llFreetimell**
Parent Issue : #4961

Until now, optimizations are done only for `loco::Graph`.
This commit will enable optimizations for `luci::Module` such as `FuseBCQPass`
and add basic `luci` service passes for `luci::Module`

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Review by seanshpark — DISMISSED** [review]
LGTM

**Review by jinevening — DISMISSED** [review]
LGTM Thank you

**Comment by llFreetimell** [comment]
I added `RemoveDeadNodeWithQueryPass` but forgot it was `logo::Pass`.
I will update this at another PR, sorry for bothering...

**Review by jinevening — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
