### PR TITLE
[onert] Revisit trix_loader to remove Subgraphs

### PR DESCRIPTION
**Pull request by glistening**
- Rename subgraphs to model
- Remove loadSubgraphs()

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

### CODE REVIEW

**Comment by glistening** [comment]
I don't know why. Checks did not started. Let me close and open it to trigger.

**Comment by glistening** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by glistening** [comment]
@nnfw-bot test cross-runtime-test-release  cross-runtime-test-debug

**Comment by glistening** [comment]
@nnfw-bot test cross-runtime-test-release
@nnfw-bot test cross-runtime-test-debug

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
