### PR TITLE
[luci/service] Correct Unique operation

### PR DESCRIPTION
**Pull request by dr-venkman**
Parent Issue : #2568
Draft PR : #2829

This commit corrects shapeinferencing for unique operation

ONE-DCO-1.0-Signed-off-by: venkat.iyer <venkat.iyer@samsung.com>

### CODE REVIEW

**Comment by dr-venkman** [comment]
CI test error caused by faulty line at `tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh:60`

Solution: Replace
```
if [ $name == "" ]; then
  name=${modelfile%.*}
fi
```
by
```
if [[ $name == "" ]]; then
  name=${modelfile%.*}
fi
```

**Comment by seanshpark** [comment]
> CI test error caused by faulty line at tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh:60

Please rebase. Current master is fixed.

**Comment by dr-venkman** [comment]
@seanshpark, PTAL

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
