### PR TITLE
[luci-interpreter] Introduce UnidirectionalSequenceLSTMParams

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce UnidirectionalSequenceLSTMParams.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for https://github.com/Samsung/ONE/issues/9895#issuecomment-1290152184, from #9899

**Comment by seanshpark** [comment]
CC @binarman

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
