### PR TITLE
[luci/pass] Fix typos in FuseXxxToFC test

### PR DESCRIPTION
**Pull request by seanshpark**
This will fix typos in fuse Add/Mul to FullyConnected pass unit tests.

### CODE REVIEW

**Comment by seanshpark** [comment]
from https://github.com/Samsung/ONE/pull/13439#discussion_r1678852483

@shs-park many thanks!!!

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
@mhs4670go , PTAL again, I've updated FC weight size.

**Review by shs-park — APPROVED** [review]
Thank you.
LGTM!
=)

**Comment by seanshpark** [comment]
@mhs4670go PTAL

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
