### PR TITLE
[q-implant] q-implant implementation

### PR DESCRIPTION
**Pull request by wnwoghd22**
This commit will enable `q-implant`.

ONE-DCO-1.0-Signed-off-by: Jaehong Ju <wnwoghd22@gmail.com>

### CODE REVIEW

**Comment by wnwoghd22** [comment]
for #11254 #11529
draft #11530

**Comment by 0minyoung0** [comment]
@nnfw-bot test nncc-debug

**Comment by wnwoghd22** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
> fatal error: error writing to /tmp/ccxSQQAJ.s: No space left on device

@hseok-oh , could you please check our CI servers?

**Comment by hseok-oh** [comment]
@nnfw-bot test all

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
