### PR TITLE
[record-minmax] Revise error msg again

### PR DESCRIPTION
**Pull request by seanshpark**
This will remove "Error:" prefix as safemain will append "ERROR:" prefix

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
rollback of #4214

**Comment by seanshpark** [comment]
Current code drops
```
ERROR: Error: Given data file is not HDF5
```

**Review by jinevening — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
