### PR TITLE
[release/1.9.0][one-cmds] Print error msg when error occurs

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit will enable printing error message when error occurs

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
For #4201

**Review by lemmaa — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Comment by llFreetimell** [comment]
@nnfw-bot test nncc-release
@nnfw-bot test nncc-debug

**Comment by llFreetimell** [comment]
@nnfw-bot test nncc-debug

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
