### PR TITLE
[luci] Add Floor Mod test

### PR DESCRIPTION
**Pull request by binarman**
Enables second Floor Mod test

ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by binarman** [comment]
part of #1598

**Comment by binarman** [comment]
hmmm

**Comment by seanshpark** [comment]
FYI, run the test with `LUCI_LOG=1` env. we may get some information.

**Comment by binarman** [comment]
Thank you!
I am confused, because these tests run fine on my local machine =/

**Comment by binarman** [comment]
ok, I think I figured it out.
I rebased on old master without recipe.
local test run succeed. because I didn't clean build directory and generated tflite/circle files were still there.

**Pull request merged**
