### PR TITLE
[onecc-docker] Change the release name of one-compiler in docker file

### PR DESCRIPTION
**Pull request by Seunghui98**
This commit changes the release name of one-compiler in docker file. 
The name will be changed to match the url of one-compiler release name asset.

ONE-DCO-1.0.-Signed-off-by: Seunghui Lee <shsh1004.lee@samsung.com>

Related Issue : [#10773]

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
`.deb` package naming with `version` is from 1.22.0.
if someone wants to build 1.21.0 or lower then this change will fail the build.
is it possible to check version? ( @jyoungyun , do we need to do this version check?)

**Comment by jyoungyun** [comment]
> is it possible to check version? ( @jyoungyun , do we need to do this version check?)

Yes, we need to do version check. I will implement this soon. This PR focuses on renaming the debian package name. This is because name matching does not work in this script after ONE supports multiple ubuntu OS, Bionic and Focal. So I want to fix this first and modify it so that we can get ONE-Compiler pacakge flexibly in the future.

I asked @Seunghui98 to simply change the name string.

It would be nice to create a new issue to solve version check issue.

**Review by jyoungyun — APPROVED** [review]
LGTM

This changing does not consider many cases. I'm planning to develop this script as a separate issue due to the lack of design in the first place.

This script changes the wrong name so that it can operate normally in the upcoming release.

Design issue related to this script will be discussed in #10811 issue.

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
