### PR TITLE
[luci-interpreter] Support Sum kernel on Linux

### PR DESCRIPTION
**Pull request by jinevening**
This supports fp32 Sum kernel on Linux.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/10531

### CODE REVIEW

**Comment by jinevening** [comment]
For reviewers:

I copied most of codes from `ReduceProd` kernel, which works similarly with `Sum`.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM
(if possible please add item to `compiler/luci-value-test/test.lst`)

**Comment by jinevening** [comment]
> (if possible please add item to compiler/luci-value-test/test.lst)

I checked the tests run well in my local computer. I'll add tests in the following PR.

**Pull request merged**
