### PR TITLE
Disable gpu_cl backend on x86_64

### PR DESCRIPTION
**Pull request by chunseoklee**
DO NOT use gpu_cl on x86_64 arch. not tested yet.

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by chunseoklee** [comment]
- part of  #https://github.com/Samsung/ONE/pull/7144
- For https://github.com/Samsung/ONE/issues/7190

**Review by YiHyunJin — DISMISSED** [review]
LGTM

**Comment by chunseoklee** [comment]
@YiHyunJin Threr was a type. PTAL again.

**Review by YiHyunJin — APPROVED** [review]

**Comment by chunseoklee** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by chunseoklee** [comment]
@nnfw-bot test android-runtime-builder

**Pull request merged**
