### PR TITLE
[onert] Introduce QuantizeManager

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduces QuantizeManager.
It is uses by nnfw API.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: https://github.com/Samsung/ONE/issues/11391
Draft: https://github.com/Samsung/ONE/pull/11298

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Comment by glistening** [comment]
@nnfw-bot test onert-x64-release

**Review by glistening — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Pull request merged**
