### PR TITLE
[one-cmds] Move utils.py into onelib dir

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit moves utils.py into onelib dir.

Related; #9359

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
Please merge this PR with #10331 to prevent build break.

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> Please merge this PR with https://github.com/Samsung/ONE/pull/10331 to prevent build break.

I think if you (1) add utils.py (2) update debian files (3) revise to use utils.py then we don't need to land at once.

**Pull request merged**
