### PR TITLE
[onert] Do not call planDealloc for I/O tensors

### PR DESCRIPTION
**Pull request by wateret**
Do not call planDealloc for I/O tensors since they cannot be
deallocated. They hold user-given buffers.

ONE-DCO-1.0-Signed-off-by: Hanjoung Lee <hanjoung.lee@samsung.com>

### CODE REVIEW

**Comment by wateret** [comment]
Fix #4585

**Comment by wateret** [comment]
@nnfw-bot test cross-runtime-test-debug

**Review by chunseoklee — APPROVED** [review]

**Comment by chunseoklee** [comment]
I have confirmed it supports internal model

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Pull request merged**
