### PR TITLE
Apply -O3 for release build

### PR DESCRIPTION
**Pull request by chunseoklee**
- Apply -O3 for release build

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by s-barannikov** [comment]
Did it give some performance? AFAIK -O3 enables optimizations which can hugely increase code size which is important for small devices.

**Comment by chunseoklee** [comment]
> Did it give some performance? AFAIK -O3 enables optimizations which can hugely increase code size which is important for small devices.
> 
> 
> 
> 

Then, I will measure bin size

**Comment by chunseoklee** [comment]
@s-barannikov Here is the size : 

IMHO, there is not much increase in size.

- O3
```
-rwxrwxr-x 1 twoflower twoflower 2.5M  7월  8 11:03 libarm_compute.so*
-rwxrwxr-x 1 twoflower twoflower  12M  7월  8 11:03 libarm_compute_core.so*
-rw-r--r-- 1 twoflower twoflower 1.5M  7월  8 11:03 libarm_compute_ex.so
-rwxrwxr-x 1 twoflower twoflower 732K  7월  8 11:03 libarm_compute_graph.so*
-rw-r--r-- 1 twoflower twoflower 445K  7월  8 11:03 libbackend_acl_cl.so
-rw-r--r-- 1 twoflower twoflower 420K  7월  8 11:03 libbackend_acl_neon.so
-rw-r--r-- 1 twoflower twoflower 1.8M  7월  8 11:03 libbackend_cpu.so
-rw-r--r-- 1 twoflower twoflower 132K  7월  8 11:03 libcircle_loader.so
-rw-r--r-- 1 twoflower twoflower 234K  7월  8 11:03 libneuralnetworks.so
-rw-r--r-- 1 twoflower twoflower 252K  7월  8 11:03 libnnfw-dev.so
-rw-r--r-- 1 twoflower twoflower  69K  7월  8 11:03 libnnfw_lib_benchmark.so
-rw-r--r-- 1 twoflower twoflower 2.7M  7월  8 11:03 libonert_core.so
-rw-r--r-- 1 twoflower twoflower 128K  7월  8 11:03 libtflite_loader.so
```
- O2
```
-rwxrwxr-x 1 twoflower twoflower 2.5M  7월  8 10:26 libarm_compute.so*
-rwxrwxr-x 1 twoflower twoflower  12M  7월  8 10:26 libarm_compute_core.so*
-rw-r--r-- 1 twoflower twoflower 1.5M  7월  8 10:26 libarm_compute_ex.so
-rwxrwxr-x 1 twoflower twoflower 732K  7월  8 10:26 libarm_compute_graph.so*
-rw-r--r-- 1 twoflower twoflower 448K  7월  8 10:26 libbackend_acl_cl.so
-rw-r--r-- 1 twoflower twoflower 427K  7월  8 10:26 libbackend_acl_neon.so
-rw-r--r-- 1 twoflower twoflower 1.7M  7월  8 10:26 libbackend_cpu.so
-rw-r--r-- 1 twoflower twoflower 138K  7월  8 10:26 libcircle_loader.so
-rw-r--r-- 1 twoflower twoflower 230K  7월  8 10:26 libneuralnetworks.so
-rw-r--r-- 1 twoflower twoflower 261K  7월  8 10:26 libnnfw-dev.so
-rw-r--r-- 1 twoflower twoflower  71K  7월  8 10:26 libnnfw_lib_benchmark.so
-rw-r--r-- 1 twoflower twoflower 2.7M  7월  8 10:26 libonert_core.so
-rw-r--r-- 1 twoflower twoflower 133K  7월  8 10:26 libtflite_loader.so
```

> Did it give some performance? 

a little. For example, internal model runs in 12 ms and 11.5 ms on O2 and O3, respectively.

**Comment by glistening** [comment]
When I applied `-O3` a few weeks ago, there was no significant performance benefit for my target model on armv7l (xu4) and perhaps `x86_64`.

**Comment by chunseoklee** [comment]
>  is there some model runs faster with -O3?

Yes. 

> For example, an internal model runs in 12 ms and 11.5 ms on O2 and O3, respectively.

**Pull request merged**
