### PR TITLE
[visq] Add TAE metric

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit adds Total Absolute Error metric.

Draft: #10432
Related: #10393

ONE-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
The code looks good to me.

Could you add a unittest for TAE to `testQErrorComputer.py` ?

**Comment by stamalakhov** [comment]
> The code looks good to me.
> 
> Could you add a unittest for TAE to `testQErrorComputer.py` ?

ok.

**Comment by stamalakhov** [comment]
> Could you add a unittest for TAE to `testQErrorComputer.py` ?

done.

**Review by jinevening — APPROVED** [review]
LGTM Thank you

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
