### PR TITLE
[one-cmd] Add SubstituteTransposeToReshape option on optimize

### PR DESCRIPTION
**Pull request by struss**
For #5703 

This will introduce `SubstituteTransposeToReshape` option on one-optimize.

ONE-DCO-1.0-Signed-off-by: KiDeuk Bang <rrstrous@nate.com>

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@struss , what about other files in one-cmds ?

**Comment by struss** [comment]
> @struss , what about other files in one-cmds ?

Oh, I will add on others. Thanks!

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
