### PR TITLE
[luci] Support const input quantization of Gather

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds support for const input quantization for Gather op.

Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@jyoungyun , this change is OK but you've conflict with my current task of enabling Gather.
See #8245.

**Comment by jinevening** [comment]
The change looks good to me.

In addition to this change, we'll need to add Gather Op to `PropagateQuantParamPass`. The ofm of Gather is a subsample of ifm, so it would be better to make the qparam of ifm same with that of ofm.

**Comment by jyoungyun** [comment]
> @jyoungyun , this change is OK but you've conflict with my current task of enabling Gather.

I saw your changes. Your patches quantize all input params including indices. Do we need to quantize indices?

**Comment by seanshpark** [comment]
> Your patches quantize all input params including indices.

Um? which code are you mentioning?

**Comment by jyoungyun** [comment]
This code is duplicated with #8268. So I close it.

**Pull request closed without merging**
