### PR TITLE
[luci] Update logic of FuseInstanceNormPass

### PR DESCRIPTION
**Pull request by llFreetimell**
Related Issue : #5501

This commit will update following things in `FuseInstanceNormPass`.

- If some dimension is unknown, `FuseInstanceNormPass` cannot be applied
- Reshape of `CircleConst` creates redundant `CircleReshape`. Thus just reshape the `CircleConst`

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
@cgbahk 
```cxx
/**
 * Instance norm pattern would be fused like following diagram:
 *
 *    [In] --------------------------- CircleInstanceNorm --- [Out]
 *                                     / /
 *    const_as_gamma --- TFLReshape --- /
 *                                     /
 *    const_as_beta ---- TFLReshape ---
 *
 * Note
 *  - 'const_as_gamma' and 'const_as_beta' are from original graph
 *  - Value of 'const_as_epsilon' would be copied to CircleInstanceNorm's attribute
 *  - TFLReshape is added as CircleInstanceNorm only accept 1D tensor
 *  - 'TFLConst --- TFLReshape' is expected to be fused in constant folding for Reshape
 */
```
This comment is really old.. but I have a question.
> TFLReshape is added as CircleInstanceNorm only accept 1D tensor

`const_as_gamma` seems to have 1D shape by itself. Could you let me know why it needs `TFLReshape`?

**Comment by cgbahk** [comment]
> `const_as_gamma` seems to have 1D shape by itself. Could you let me know why it needs `TFLReshape`?

I'm not sure but I guess I was dealing with `1x1x.. xD` constant tensor for gamma and beta.
(nnfw 9103)

**Comment by mhs4670go** [comment]
Hmmm.. 
> gamma : 1-dimensional tensor of size C

The spec says it is 1-D tensor but, as @cgbahk said, sometimes it might be higher dimension.

@llFreetimell Could we remove this reshape op?

**Comment by llFreetimell** [comment]
@mhs4670go 
This PR is for removing `CircleReshape`, not for removing reshaping itself :)
As @cgbahk said, there may be some cases that higher dimension appears.
Nevertheless, we can reshape the higher dimension node just by modifying rank and dimension of `CircleConst` :)

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
