### PR TITLE
[onert] Make Controlflow backend always loaded

### PR DESCRIPTION
**Pull request by wateret**
Make Controlflow backend always loaded, this is to use this backend for
input/output which is part of #1325.

ONE-DCO-1.0-Signed-off-by: Hanjoung Lee <hanjoung.lee@samsung.com>

### CODE REVIEW

**Comment by ragmani** [comment]
Can fp16 be enabled with this commit?

**Comment by wateret** [comment]
@YongseopKim Could you please let me know how to test Fp16?

**Comment by YongseopKim** [comment]
@wateret if the `test` means just running, set `FP16_ENABLE=1`.
else if it does matching the result with a kind of golden data, nothing.

To test(the latter), I did with the eye by `tflite_run`(like 'the diff is 0.00001 so that's enough').
(FYI, I tried founding the proper tolerance, but I couldn't.)

**Comment by wateret** [comment]
I checked that all the outputs are the same - running below command with this commit and without this commit.

```
MODELFILE_SERVER=http://npu.mooo.com/archive/tflite_test_model FP16_ENABLE=1 ./infra/scripts/test_ubuntu_runtime.sh --backend acl_cl --linear-only
```

**Comment by ragmani** [comment]
I checked at afc0996180db41bf11717c8cc1b0a64a617c2cb0 without this commit.
The results are different.

<Details>

```bash
$ FP16_ENABLE=1 BACKENDS="acl_cl" ./Product/armv7l-linux.release/out/bin/nnapi_test inceptionv3_slim_2016.tflite 
[NNAPI TEST] Run T/F Lite Interpreter without NNAPI
[NNAPI TEST] Run T/F Lite Interpreter with NNAPI
nnapi function 'ANeuralNetworksModel_create' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperand' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_setOperandValue' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperation' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_identifyInputsAndOutputs' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_finish' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_create' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_finish' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_create' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setInput' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setOutput' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_startCompute' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_wait' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
[NNAPI TEST] Compare the result
  Tensor #314: UNMATCHED
    910 diffs are detected
    Max absolute diff at [0, 490]
       expected: 6.06485
       obtained: 6.14062
       absolute diff: 0.0757737
    Max relative diff at [0, 214]
       expected: 0.00783977
       obtained: 0.00115967
       relative diff: 0.852079
         (tolerance level = 7.14776e+06)
```

</Details>

I checked at afc0996180db41bf11717c8cc1b0a64a617c2cb0 with this commit.
The results are the same.
<Details>

```bash
$ FP16_ENABLE=1 BACKENDS="acl_cl" ./Product/armv7l-linux.release/out/bin/nnapi_test inceptionv3_slim_2016.tflite 
[NNAPI TEST] Run T/F Lite Interpreter without NNAPI
[NNAPI TEST] Run T/F Lite Interpreter with NNAPI
nnapi function 'ANeuralNetworksModel_create' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperand' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_setOperandValue' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperation' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_identifyInputsAndOutputs' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_finish' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_create' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_finish' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_create' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setInput' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setOutput' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_startCompute' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_wait' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_free' is loaded from '/home/odroid/nfs/Product/armv7l-linux.release/out/bin/../lib/libneuralnetworks.so' 
[NNAPI TEST] Compare the result
  Tensor #314: MATCHED
    Max absolute diff at [0, 869]
       expected: 3.57375
       obtained: 3.57371
       absolute diff: 3.48091e-05
    Max relative diff at [0, 355]
       expected: 0.00142744
       obtained: 0.00143293
       relative diff: 0.00382688
         (tolerance level = 32102.2)
[NNAPI TEST] PASSED
```

</Details>

**Comment by wateret** [comment]
@ragmani Oh you're right. I must have run tests wrongly.

**Comment by wateret** [comment]
@ragmani @YongseopKim PTAL

**Pull request merged**
