### PR TITLE
[one-cmds] Enable fuse_mul_div

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This commit enables fuse_mul_div option for one-cmds optimize.

for issue: https://github.com/Samsung/ONE/issues/11956
from draft https://github.com/Samsung/ONE/pull/12124

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Review by seanshpark — DISMISSED** [review]
LGTM

**Comment by jinevening** [comment]
Could you add this option to O1 list?

**Comment by BalyshevArtem** [comment]
> Could you add this option to O1 list?

Sure, done)

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
