### PR TITLE
[one-cmds] Bump PyTorch version

### PR DESCRIPTION
**Pull request by binarman**
This PR updates PyTorch version to 1.10.

related issue: #7939

ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by binarman** [comment]
Ubuntu 18.04 and 20.04 successfully works with this change.
Used docker to check this.

**Comment by seanshpark** [comment]
@binarman , I need to check this in our internet test system. please wait.

**Comment by seanshpark** [comment]
Out internal test system currenrly does not use pytorch :)

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by lucenticus — APPROVED** [review]

**Pull request merged**
