### PR TITLE
[github] Add workflow for tools/model-explorer-circle

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce initial workflow for PR build and testing for tools/model-explorer-circle.

### CODE REVIEW

**Comment by seanshpark** [comment]
- for #14330
- from  #14334

**Review by batcheu — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@hseok-oh PTAL

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
