### PR TITLE
[luci] Enable PadV2 operator in tests

### PR DESCRIPTION
**Pull request by a-zh**
This enables tests for PadV2 operator

Draft: #3566
Issue: #3362

### CODE REVIEW

**Comment by seanshpark** [comment]
`nnfw-bot` is our CI bot :) you don't need to add to reviewer list.

**Review by binarman — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Review by binarman — APPROVED** [review]

**Review by ai-moiseev — APPROVED** [review]
LGTM :+1:

**Pull request merged**
