### PR TITLE
[onert] Add generating training usedefs for Softmax op

### PR DESCRIPTION
**Pull request by ragmani**
This commit adds generating training usedefs for Softmax operation.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Review by jyoungyun — DISMISSED** [review]
LGTM

**Comment by ragmani** [comment]
Resolved conflict

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
