### PR TITLE
[luci/export] Fix order of registry of CumSum

### PR DESCRIPTION
**Pull request by batcheu**
It fixes the order of registry of CumSum.

ONE-DCO-1.0-Signed-off-by: Jonghwa Lee <jonghwa3.lee@samsung.com>

### CODE REVIEW

**Comment by batcheu** [comment]
This fixes the wrong registration order of CumSum which is applied by #11916.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by batcheu** [comment]
> LGTM

Thanks for rapid response.
Sorry for bothering due to my mistake 😢

**Comment by seanshpark** [comment]
> Sorry for bothering due to my mistake 

No worry :)

**Pull request merged**
