### PR TITLE
[doc] Remove a link to a blank document

### PR DESCRIPTION
**Pull request by pfusik**

### CODE REVIEW

**Comment by hseok-oh** [comment]
IMO, we need to fill `overall-architecture.md` document instead of removing link.
cc/ @lemmaa

**Comment by lemmaa** [comment]
> IMO, we need to fill `overall-architecture.md` document instead of removing link.

How about taking this opportunity to write the pending overall-architecture.md document? :)

**Comment by pfusik** [comment]
I'm completely new to ONE. All I can say is that it looks very bad to have a blank document in README of an open source project. It scares away potential users and contributors, must of which will ignore the project without saying a word and some will complain about its quality to others.
Of course it's better to have a good documentation, but until it's ready, I suggest to remove the link from README.
Just my two cents.

**Comment by hseok-oh** [comment]
I think @pfusik 's suggestion and concern looks reasonable. I agree to remove link and revive when ready.

@seanshpark Do you have any suggestion about this?

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
