### PR TITLE
[onert/test] Revisit Equal test

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit updates Equal GenModelTest to test more type.

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
We need similar test for `NotEqual`, `Less`, `LessEqual`, `Greater`, `GreaterEqual`
cc/ @glistening

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
Maybe related to https://github.com/Samsung/ONE/issues/8775#issuecomment-1098956890

**Pull request merged**
