### PR TITLE
[npud] Add npud main

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds an initial commit of npud.
It defines BUILD_NPUD and builds npud code when this option is on.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

draft pr: #9267

### CODE REVIEW

**Comment by chunseoklee** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by chunseoklee** [comment]
@jyoungyun Do you have any idea how to test the code like npud ?

**Comment by jyoungyun** [comment]
>Do you have any idea how to test the code like npud ?

For now, I have not thought about it in the current server-only structure. If the library is implemented in the future, it will be possible to check whether the intended response comes when the server is executed and the library function is called.

**Review by chunseoklee — APPROVED** [review]

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by dayo09 — APPROVED** [review]

**Pull request merged**
