### PR TITLE
[circle-opselector] Fix README.md EOL

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit changes README.md 's EOL: CRLF -> LF

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Please merge after 1 approval

### CODE REVIEW

**Comment by hseok-oh** [comment]
I found previous EOL checker has bug.

**Comment by hseok-oh** [comment]
It will resolve #8235

**Review by chunseoklee — APPROVED** [review]

**Comment by seanshpark** [comment]
Not sure @Paran-Yu may respond.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
I've merged without @Paran-Yu and @mhs4670go 's approval (simple patch)

**Pull request merged**
