### PR TITLE
[luci] Correct low weight scales

### PR DESCRIPTION
**Pull request by Bronnikoff**
This commit introduces correction of low weight and input scales.

ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov <max120199@gmail.com>

-------------------------------

For: https://github.com/Samsung/ONE/issues/6970#issuecomment-858503901

### CODE REVIEW

**Comment by Bronnikoff** [comment]
After this changes weight and bias scales for mobilenetv2(details: https://github.com/Samsung/ONE/issues/6970#issue-916328038) corrected to upper values! Bias scale becomes equal to `1e-15` with quantized value equal to `-1215652912168960`. Dequantized value also seems correct:

```python
>>> -1215652912168960 * 1e-15
-1.21565291216896
```

**Comment by Bronnikoff** [comment]
@AShedko @binarman @jinevening Could you please take a look?

**Comment by jinevening** [comment]
> Could you please take a look?

The draft correctly updates `QuantizeWithMinMax`, but `QuantizeDequantizeWeights` should be considered as well. It is difficult to update `QuantizeDequantizeWeights` in the same way because we don't know `s_in` in `QuantizeDequantizeWeights`.

We're thinking about using a fixed minimum value for `s_w` as we did in Q8 quantization. @meejeong is doing experiments with some models so let's wait for her :)

**Comment by Bronnikoff** [comment]
@nnfw-bot test pr-nncc-debug

**Comment by Bronnikoff** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
#7063 covers this issue. I think this PR can be closed.

**Comment by Bronnikoff** [comment]
> #7063 covers this issue. I think this PR can be closed.

I'm agree with you =)

**Pull request closed without merging**
