### PR TITLE
[onert] Set dynamic shape inferer off by default and enable when necessary

### PR DESCRIPTION
**Pull request by glistening**
- Currently dynamic shape inferer is enabled by default.
It will change the default value to false.

- Also, it removes `dynamic_cast` which was necessary to switch
true(enabled) (previously default value) to false(disabled).

- Also, it removes tensor_registry member, which is not used any longer.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

### CODE REVIEW

**Comment by glistening** [comment]
model: 0.351 → 0.334 (5.1 % improvement)
app: 0.962 → 0.929 (about 0.033 improvement)

**Review by hyunsik-yoon — DISMISSED** [review]
LGTM

**Comment by hseok-oh** [comment]
@glistening Please fix test fail

**Comment by glistening** [comment]
`cpu` backend is ok. `acl_cl` and `acl_neon` fail during `GeneratedTests.expand_dims_dynamic_nnfw_1`.

**Comment by hyunsik-yoon** [comment]
https://github.com/Samsung/ONE/pull/4557 has been merged. :-) Please rebase~!

**Comment by glistening** [comment]
@hyunsik-yoon I've already rebased. Error occurrs during `AddTwo`. I will take a look next week.

**Comment by glistening** [comment]
I've found #4512 was merged during rebasing. #4512 introduces `initRunning` which sets `_enable_dynamic_shape_inferer` to `true`. It should be `false` because I am changing the default value of `_enable_dynamic_shape_inferer` in this PR. Thus, I've updated.

**Comment by glistening** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by glistening** [comment]
I cannot reproduce `GeneratedTests.transpose_v1_2*` errors in ubuntu mate 18.04 xu4. I ran 10 times respectively for `acl_cl`, `acl_neon` and `cpu` backecnd. All passes. Besides, our CI fails for 2 of 2 runs with same error:

```
[ RUN      ] GeneratedTests.transpose_v1_2
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/include/TestHarness.h:303: Failure
The difference between expected and actual is 1, which exceeds fpRange, where
expected evaluates to 3,
actual evaluates to 2, and
fpRange evaluates to 1.178813909064047e-05.
Google Test trace:
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/include/TestHarness.h:261: When comparing output 0 element 1
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/src/TestGenerated.cpp:123: 0
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/src/TestGenerated.cpp:235: TestCompilationCaching = 0
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/include/TestHarness.h:303: Failure
The difference between expected and actual is 1, which exceeds fpRange, where
expected evaluates to 2,
actual evaluates to 3, and
fpRange evaluates to 1.1192092642886564e-05.
Google Test trace:
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/include/TestHarness.h:261: When comparing output 0 element 2
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/src/TestGenerated.cpp:123: 0
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/src/TestGenerated.cpp:235: TestCompilationCaching = 0
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/include/TestHarness.h:389: Failure
      Expected: size_t{0}
      Which is: 0
To be equal to: totalNumberOfErrors
      Which is: 2
Google Test trace:
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/src/TestGenerated.cpp:123: 0
/opt/jenkins_slave/workspace/nnfw/master/pr-cross-runtime-test-pipeline-release/tests/nnapi/src/TestGenerated.cpp:235: TestCompilationCaching = 0
```

**Comment by hyunsik-yoon** [comment]
I did the same test with the following command and the tests passed:

```
odroid@odroid:~/work/3/ONE$ BACKENDS=acl_cl ./Product/armv7l-linux.release/out/unittest/nnapi_gtest --gtest_filter=GeneratedTests.transpose_v1_2
...
odroid@odroid:~/work/3/ONE$ BACKENDS=acl_neon ./Product/armv7l-linux.release/out/unittest/nnapi_gtest --gtest_filter=GeneratedTests.transpose_v1_2
...
```

<details>

```
odroid@odroid:~/work/3/ONE$ BACKENDS=acl_cl ./Product/armv7l-linux.release/out/unittest/nnapi_gtest --gtest_filter=GeneratedTests.transpose_v1_2
[**********] useCpuOnly = 0, computeMode = ComputeMode::ASYNC, allowSyncExecHal = 1  // pass 10
Note: Google Test filter = GeneratedTests.transpose_v1_2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GeneratedTests
[ RUN      ] GeneratedTests.transpose_v1_2
nnapi function 'ANeuralNetworksModel_create' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperand' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperation' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_identifyInputsAndOutputs' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_finish' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_create' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_finish' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_create' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setInput' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setOutput' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_startCompute' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_wait' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_getOutputOperandRank' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_getOutputOperandDimensions' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
[       OK ] GeneratedTests.transpose_v1_2 (119 ms)
[----------] 1 test from GeneratedTests (119 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (120 ms total)
[  PASSED  ] 1 test.
[**********] useCpuOnly = 0, computeMode = ComputeMode::SYNC, allowSyncExecHal = 1  // pass 8
Note: Google Test filter = GeneratedTests.transpose_v1_2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GeneratedTests
[ RUN      ] GeneratedTests.transpose_v1_2
nnapi function 'ANeuralNetworksExecution_compute' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
[       OK ] GeneratedTests.transpose_v1_2 (2 ms)
[----------] 1 test from GeneratedTests (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3 ms total)
[  PASSED  ] 1 test.
odroid@odroid:~/work/3/ONE$ BACKENDS=acl_neon ./Product/armv7l-linux.release/out/unittest/nnapi_gtest --gtest_filter=GeneratedTests.transpose_v1_2
[**********] useCpuOnly = 0, computeMode = ComputeMode::ASYNC, allowSyncExecHal = 1  // pass 10
Note: Google Test filter = GeneratedTests.transpose_v1_2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GeneratedTests
[ RUN      ] GeneratedTests.transpose_v1_2
nnapi function 'ANeuralNetworksModel_create' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperand' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_addOperation' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_identifyInputsAndOutputs' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_finish' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_create' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_finish' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksCompilation_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_create' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setInput' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_setOutput' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_startCompute' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_wait' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksEvent_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_getOutputOperandRank' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_getOutputOperandDimensions' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksExecution_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
nnapi function 'ANeuralNetworksModel_free' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
[       OK ] GeneratedTests.transpose_v1_2 (61 ms)
[----------] 1 test from GeneratedTests (61 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (62 ms total)
[  PASSED  ] 1 test.
[**********] useCpuOnly = 0, computeMode = ComputeMode::SYNC, allowSyncExecHal = 1  // pass 8
Note: Google Test filter = GeneratedTests.transpose_v1_2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GeneratedTests
[ RUN      ] GeneratedTests.transpose_v1_2
nnapi function 'ANeuralNetworksExecution_compute' is loaded from '/home/odroid/work/3/ONE/Product/armv7l-linux.release/out/unittest/../lib/libneuralnetworks.so' 
[       OK ] GeneratedTests.transpose_v1_2 (1 ms)
[----------] 1 test from GeneratedTests (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2 ms total)
[  PASSED  ] 1 test.
```

</details>

**Comment by glistening** [comment]
I've found 1 suspicious test case during debugging this issue.

`GeneratedTests.reshape_quant8_weights_as_inputs` is considered as "dynamic shape` for `acl_cl` and `acl_neon` backend.
Those two backends don't work for `dynamic shape`.


```py
# model
model = Model()
# a line of 3 pixels, 3 components/pixel
i1 = Input("op1", "TENSOR_QUANT8_ASYMM", "{1, 1, 3, 3}, 1.f, 0")
i2 = Input("op2", "TENSOR_INT32", "{1}")
i3 = Output("op3", "TENSOR_QUANT8_ASYMM", "{9}, 1.f, 0")
model = model.Operation("RESHAPE", i1, i2).To(i3)

# Example 1. Input in operand 0,
input0 = {i1: # input 0
             [1, 2, 3,
              4, 5, 6,
              7, 8, 9],
          i2: # input 1
             [-1]}

output0 = {i3: # output 0
           [1, 2, 3, 4, 5, 6, 7, 8, 9]}

# Instantiate an example
Example((input0, output0))
```

```c++
void StaticShapeInferer::visit(const ir::operation::Reshape &op)
{
...
    if (shape.isConstant())
    {
      const auto *shape_buf = reinterpret_cast<const int32_t *>(shape.data()->base());
      assert(shape_buf);

      ir::Shape new_shape = shape_inference::inferReshapeShape(
          shape_buf, shape.shape().num_elements(), input.shape().num_elements());

      // if shape is from Const, TFLC put the shape of output into tensor
      if (new_shape != output.shape())
      {
        // change on output shape
        output.info().shape(new_shape);
      }
    }
    else
    {
      printf("setDynamic()\n");
      // if shape is NOT Const, set output shape to be dynamic_
      output.info().setDynamic();
      _return_has_dynamic_tensor = true;
    }
}
```
It prints "setDynamic()".

Also, I've found `reshape_quant8_weights_as_inputs` requires us to do special handling in `Linear.cc`.

```c++
    // TODO Remove if onert doesn't support anymore such as
    // GeneratedTests.reshape_quant8_weights_as_inputs
    if (lower_info->def_factors().size() == 0 && lower_info->use_factors().size() == 0 &&
        !graph.getInputs().contains(ind))
    {
      VERBOSE(LINEAR) << "Operand #" << ind.value() << " will not be used. no more process."
                      << std::endl;
      return;
    }
```

**Comment by glistening** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by hseok-oh** [comment]
@glistening Could you check with below patch?

```diff
--- a/runtime/onert/backend/cpu/ops/TransposeLayer.cc
+++ b/runtime/onert/backend/cpu/ops/TransposeLayer.cc
@@ -44,7 +44,7 @@ template <typename T> void TransposeLayer::transpose()
   if (_perm->dimension(0) == 0) // This means _perm is (n-1...0)
   {
     const auto begin = param.perm;
-    const auto end = param.perm + _input->num_dimensions() - 1;
+    const auto end = param.perm + _input->num_dimensions();
     std::iota(begin, end, 0);
     std::reverse(begin, end);
   }
```

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Pull request merged**
