### PR TITLE
[one-cmds] Support folding SparseToDense Op

### PR DESCRIPTION
**Pull request by jinevening**
This supports folding SparseToDense Op.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to : #5598
Draft PR: #5621

### CODE REVIEW

**Comment by mhs4670go** [comment]
Maybe you don't match the yapf version, e.g. 0.22.0.

**Comment by jinevening** [comment]
> Maybe you don't match the yapf version, e.g. 0.22.0.

Thanks! You've saved my time a lot.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@mhs4670go , it seems we need to update also `compiler/one-cmds/how-to-use-one-commands.txt` file for recent added options :)

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
