### PR TITLE
[tflitefile_tools] Apply new IRs

### PR DESCRIPTION
**Pull request by YongseopKim**
Let's apply new IRs to model_parser.

Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

---

for https://github.com/Samsung/ONE/issues/8086
draft https://github.com/Samsung/ONE/pull/8184

PTAL @hseok-oh and @chunseoklee

### CODE REVIEW

**Comment by YongseopKim** [comment]
So now,
```

#123 CONV_2D
  Fused Activation: NONE
  Input Tensors[%221, %224, %223]
    %221  : buffer (Empty)                   | FLOAT32 | Memory 8.0K   | Shape [1, 1, 1, 2048] (b'InceptionV3/Logits/AvgPool_1a_8x8/AvgPool')
    %224  : buffer (&284 : [[[[ ... ]]]])    | FLOAT32 | Memory 7.8M   | Shape [1001, 1, 1, 2048] (b'InceptionV3/Logits/Conv2d_1c_1x1/weights')
    %223  : buffer (&2   : [ ... ])          | FLOAT32 | Memory 3.9K   | Shape [1001] (b'InceptionV3/Logits/Conv2d_1c_1x1/Conv2D_bias')
  Output Tensors[%222]
    %222  : buffer (Empty)                   | FLOAT32 | Memory 3.9K   | Shape [1, 1, 1, 1001] (b'InceptionV3/Logits/Conv2d_1c_1x1/BiasAdd')
  Options
    Stride W:H = 1:1, Dilation W:H = 1:1, Padding = SAME

#124 RESHAPE
  Fused Activation: NONE
  Input Tensors[%222, %226]
    %222  : buffer (Empty)                   | FLOAT32 | Memory 3.9K   | Shape [1, 1, 1, 1001] (b'InceptionV3/Logits/Conv2d_1c_1x1/BiasAdd')
    %226  : buffer (&1   : [   1, 1001])     | INT32   | Memory 8.0B   | Shape [2] (b'InceptionV3/Logits/SpatialSqueeze_shape')
  Output Tensors[%225]
    %225  : buffer (Empty)                   | FLOAT32 | Memory 3.9K   | Shape [1, 1001] (b'InceptionV3/Logits/SpatialSqueeze')

#125 SOFTMAX
  Fused Activation: NONE
  Input Tensors[%225]
    %225  : buffer (Empty)                   | FLOAT32 | Memory 3.9K   | Shape [1, 1001] (b'InceptionV3/Logits/SpatialSqueeze')
  Output Tensors[%316]
    %316  : buffer (Empty)                   | FLOAT32 | Memory 3.9K   | Shape [1, 1001] (b'InceptionV3/Predictions/Reshape_1')

Number of all operator types          :    6
  AVERAGE_POOL_2D                     :   10
  CONCATENATION                       :   15
  CONV_2D                             :   95
  MAX_POOL_2D                         :    4
  RESHAPE                             :    1
  SOFTMAX                             :    1
Number of all operators               :  126

Expected TOTAL  memory: 146.6M
Expected FILLED memory: 90.9M
```

**Comment by YongseopKim** [comment]
```
~/Works/ONE/tools/tflitefile_tool(pr/apply_new_irs ✗) python -m unittest discover
..........................
----------------------------------------------------------------------
Ran 26 tests in 0.002s

OK
~/Works/ONE/tools/tflitefile_tool(pr/apply_new_irs ✗)
```

**Comment by chunseoklee** [comment]
I found that tflite **genereated by tflchef** is not processed by this PR : 

```
~/d/ONE ⬢  8.10.0 32.663s
➜  ./tools/tflitefile_tool/model_parser.py /tmp/Conv2D_001.tflite
Traceback (most recent call last):
  File "./tools/tflitefile_tool/model_parser.py", line 110, in <module>
    subg_list = ModelParser(option.model_file).Parse()
  File "/home/twoflower/dev/ONE/tools/tflitefile_tool/parser/model_parser.py", line 31, in Parse
    return self.parser.Parse()
  File "/home/twoflower/dev/ONE/tools/tflitefile_tool/parser/tflite/tflite_parser.py", line 96, in Parse
    subg_parser = TFLiteSubgraphParser(tf_model, subgraph_index)
  File "/home/twoflower/dev/ONE/tools/tflitefile_tool/parser/tflite/tflite_parser.py", line 27, in __init__
    self.subg = TFLiteSubgraph(subgraph_index, self.tf_subgraph)
  File "/home/twoflower/dev/ONE/tools/tflitefile_tool/parser/tflite/tflite_subgraph.py", line 27, in __init__
    self.subg_name = tf_subgraph.Name()
  File "/home/twoflower/dev/ONE/tools/tflitefile_tool/ir/subgraph.py", line 117, in subg_name
    raise TypeError("must be set to a str")
TypeError: must be set to a str
```

**Comment by YongseopKim** [comment]
I'll investigate it. Can yoy share the tflite file?

**Comment by seanshpark** [comment]
> TypeError: must be set to a str

Maybe tflchef has a bug... -_-;;;

**Comment by chunseoklee** [comment]
> I'll investigate it. Can yoy share the tflite file?

Sure, I will upload small size one.

**Comment by chunseoklee** [comment]
> > TypeError: must be set to a str
> 
> Maybe tflchef has a bug... -_-;;;

Maybe.. I am not sure that str subgraph name is mandatory one or not in tflite definition.

**Comment by chunseoklee** [comment]
[tflchef_conv.tar.gz](https://github.com/Samsung/ONE/files/7760553/tflchef_conv.tar.gz)

@YongseopKim Here is a tflite gen by tflchef.

**Comment by YongseopKim** [comment]
> Maybe.. I am not sure that str subgraph name is mandatory one or not in tflite definition.

Yes, if subg name is mandatory, there is no change. But if not, I can add some patch.

**Comment by YongseopKim** [comment]
```

// The root type, defining a subgraph, which typically represents an entire
// model.
table SubGraph {
  // A list of all tensors used in this subgraph.
  tensors:[Tensor];

  // Indices of the tensors that are inputs into this subgraph. Note this is
  // the list of non-static tensors that feed into the subgraph for inference.
  inputs:[int];

  // Indices of the tensors that are outputs out of this subgraph. Note this is
  // the list of output tensors that are considered the product of the
  // subgraph's inference.
  outputs:[int];

  // All operators, in execution order.
  operators:[Operator];

  // Name of this subgraph (used for debugging).
  name:string;
}
```

This looks mandatory but it just used for debugging.

**Comment by YongseopKim** [comment]
If there is code for null string, it would be good.

**Comment by YongseopKim** [comment]
Wow, the tflite's the subgraph's name type is bytes, not string.

**Comment by chunseoklee** [comment]
> Wow, the tflite's the subgraph's name type is bytes, not string.

?  

```
  // Name of this subgraph (used for debugging).
  name:string;
```

**Comment by chunseoklee** [comment]
I have converted uploaded model into json format, but it contains str subgraph name : 

```
      ],
      name: "main"
    }

```

But, it fail with this PR.

**Comment by YongseopKim** [comment]
Maybe it will convert bytes to str automatically. Its type is actually `bytes`.

**Comment by YongseopKim** [comment]
I resolve the problem but I face another problem.

**Comment by chunseoklee** [comment]
> I resolve the problem but I face another problem. (operator's input index is -1)
> 
> ```
> table Operator {
>   // Index into the operator_codes array. Using an integer here avoids
>   // complicate map lookups.
>   opcode_index:uint;
> 
>   // Optional input and output tensors are indicated by -1.
>   inputs:[int];
>   outputs:[int];
> ...
> }
> ```
FYI,  the uploaded model is generated after deleting bias(of conv) input from recipe, which induce optional input.

**Comment by YongseopKim** [comment]
```
~/Works/ONE/tools/tflitefile_tool(pr/apply_new_irs ✗) ./model_parser.py -v1 ~/Works/ONE/Conv2D_001.tflite
[#0 b'main' (MAIN)]

#0 b'main' (MAIN) input tensors: [0]
    %0    : buffer (Empty)                   | FLOAT32 | Memory 120.0B | Shape [1, 3, 5, 2] (b'ifm')
#0 b'main' (MAIN) output tensors: [3]
    %3    : buffer (Empty)                   | FLOAT32 | Memory 60.0B  | Shape [1, 3, 5, 1] (b'ofm')

#0 CONV_2D
  Fused Activation: NONE
  Input Tensors[%0, %1, %-1]
    %0    : buffer (Empty)                   | FLOAT32 | Memory 120.0B | Shape [1, 3, 5, 2] (b'ifm')
    %1    : buffer (&3   : [[[[ ... ]]]])    | FLOAT32 | Memory 72.0B  | Shape [1, 3, 3, 2] (b'ker')
    %-1   : (OPTIONAL)
  Output Tensors[%3]
    %3    : buffer (Empty)                   | FLOAT32 | Memory 60.0B  | Shape [1, 3, 5, 1] (b'ofm')
  Options
    Stride W:H = 1:1, Dilation W:H = 1:1, Padding = SAME

Number of all operator types          :    1
  CONV_2D                             :    1
Number of all operators               :    1

Expected TOTAL  memory: 256.0B
Expected FILLED memory: 76.0B
```

**Comment by YongseopKim** [comment]
FYI,

> [#0 b'main' (MAIN)]

`b'main'` means bytes string.

**Comment by YongseopKim** [comment]
PTAL again

**Comment by chunseoklee** [comment]
It seems that circle file gen by onecc contains b'main' subgraph name.

**Review by chunseoklee — APPROVED** [review]

**Review by hseok-oh — APPROVED** [review]

**Pull request merged**
