### PR TITLE
[luci-intp] Revise to support NEON for armv7l-linux

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise ARMv7l-linux PAL to support NEON with RUY.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #8379 from draft #8578

**Review by jinevening — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
@jinevening , PTAL again. I've applied what you've left in DRAFT PR.

**Review by jinevening — APPROVED** [review]
LGTM

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
