### PR TITLE
[luci] Enable convert to NHWC for LeakyRelu

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable conversion to NHWC for CircleLeakyRelu.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Review by jinevening — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
@jinevening , sorry for early request. I think I need to add a test :)

**Comment by seanshpark** [comment]
@jinevening , PTAL again

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
