### PR TITLE
[infra] Install pydot in docker image

### PR DESCRIPTION
**Pull request by jinevening**
This installs pydot in docker image.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/10324 https://github.com/Samsung/ONE/issues/10322

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
Do you know reason why test is not failed on PR test?

**Comment by seanshpark** [comment]
test is done with venv
```
# Use Python in venv to run unittest with pydot module
add_test(
  NAME visq_unittest
  COMMAND ${NNCC_OVERLAY_DIR}/venv_2_8_0/bin/python -m unittest
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
)
```
@jinevening , can you double check this issue?

**Comment by hseok-oh** [comment]
I've cleaned up all cache of overlay (`NNCC_OVERLAY_DIR`). Then https://github.com/Samsung/ONE/issues/10322 is passed. 
It may be related with overlay caching mechanism.

**Comment by jinevening** [comment]
> I've cleaned up all cache of overlay (NNCC_OVERLAY_DIR). Then https://github.com/Samsung/ONE/issues/10322 is passed.

Let me close this issue.

**Pull request closed without merging**
