### PR TITLE
[infra] Update cmsis-nn version

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This pr updates cmsis-nn version.

for https://github.com/Samsung/ONE/issues/13634
from #13719

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@chunseoklee No problem to merge this?

**Comment by chunseoklee** [comment]
It is OK to merge although it is not mandatory for now ( based on https://github.com/Samsung/ONE/pull/13719#discussion_r1726362217)

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Pull request merged**
