### PR TITLE
[one-cmds] Upgrade venv to TF2.6.0

### PR DESCRIPTION
**Pull request by seanshpark**
This will upgrade one-cmds venv to use TF2.6.0.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
This change will run one-cmds frontend compiler to run on TensorFlow 2.6.0.

**Comment by seanshpark** [comment]
Problem running internal test
```
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists
```

**Review by lemmaa — APPROVED** [review]
LGTM.

**Comment by lemmaa** [comment]
@chunseoklee , @hseok-oh , can you confirm the runtime impact of this PR?

**Comment by hseok-oh** [comment]
@nnfw-bot test nnpackage-test

**Comment by hseok-oh** [comment]
@nnfw-bot test nnpackage-test

**Comment by hseok-oh** [comment]
@nnfw-bot test nnpackage-test

**Comment by hseok-oh** [comment]
No conflict found on current test set.

**Review by hseok-oh — APPROVED** [review]

**Comment by seanshpark** [comment]
I'll merge this next Monday after @chunseoklee 's approval (I have work at home and vacation this week)

**Review by chunseoklee — APPROVED** [review]
LGTM

**Pull request merged**
