### PR TITLE
[onert] fix Range operation in cpu backend

### PR DESCRIPTION
**Pull request by dayo09**
- instead of using pointer as T, use value as T

ONE-DCO-1.0-Signed-off-by: dayo09 <dayg502@gmail.com>

### CODE REVIEW

**Comment by dayo09** [comment]
This operator doesn't have any tests. It isn't within nnapi, so I think even oneapi test should be updated.

**Comment by hyunsik-yoon** [comment]
1. can you also mention the `start` value change into the body of PR message? I was confused with this PR since some lines are not relate to template type change.

2. can you also add parent issue?

Thanks!

**Comment by ragmani** [comment]
@hyunsik-yoon 
> 1. can you also mention the `start` value change into the body of PR message? I was confused with this PR since some lines (to fix `start`) are not relate to template type change.

- Before
`T start = start_data;` <---- T is `float *` or `int32_t *`
- After
`T value = start_value;` <---- T is `float` or `int32_t`

**Comment by ragmani** [comment]
> This operator doesn't have any tests. It isn't within nnapi, so I think even oneapi test should be updated.

@dayo09 
This operator was introduced into `NeuralNetworksEx.h` and have nnapi tests in `tests/nnapi/specs/Ex/`

**Comment by hyunsik-yoon** [comment]
@dayo09 
I guess this was written for https://github.sec.samsung.net/STAR/nnfw/issues/11494
and could you mention this fixes #11494?

**Comment by hyunsik-yoon** [comment]
FYI, the test still fails
```
odroid@odroid:~/work/1/ONE$ BACKENDS=cpu ${ONE_PATH}/Product/out/bin/nnpackage_run ${MODEL_ZOO_ENMT_PATH}/subg_0_0_191 --shape_run '[0, [1, 10]]' --load ${MODEL_ZOO_ENMT_PATH}/large_test_input_0.h5
nnpackage_run: /home/eric/work/1/ONE/compute/cker/include/cker/operation/Range.h:57: void nnfw::cker::Range(const T*, const T*, const T*, T*) [with T = int]: Assertion `value < limit_value' failed.
Aborted
```

both `value` and `limit_value` are 10

**Comment by dayo09** [comment]
@hyunsik-yoon I think that is wrong assert, you can just delete it.

**Comment by ragmani** [comment]
I think `num_elements` value is different from actual the num of elements.

**Pull request merged**
