### PR TITLE
[infra] Speed up file search in format

### PR DESCRIPTION
**Pull request by m-bronnikov**
This commit speed ups format by using grep instead of bash loops.

ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov <max120199@gmail.com>
Co-authored-by: Andrey Shedko <a.shedko@samsung.com>

### CODE REVIEW

**Comment by m-bronnikov** [comment]
@AShedko applied usage of `grep` instead `bash` loops in internal repo. As @hseok-oh mentioned, this approach can be applied in other repos. This PR introduces this changes.

With this `PR` (9b1bec29eb4c35c4025a431160c5c9e03cff78f3)
```
$ time ./nnas format
[PASSED] Format checker succeed.

real	1m6,198s
user	1m18,521s
sys	0m12,111s
```

With master `master` (a50ea9bd920c38131c019b9c7ef8b0f0e9095178)
```
$ time ./nnas format
[PASSED] Format checker succeed.

real	1m12,719s
user	1m24,820s
sys	0m13,537s
```

**Review by AShedko — COMMENTED** [review]
LGTM. Thank you!

**Comment by AShedko** [comment]
@nnfw-bot test cross-runtime-test-debug

**Review by AShedko — DISMISSED** [review]

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-debug
@nnfw-bot test cross-runtime-test-release
@nnfw-bot test cross-aarch64-runtime-test-release

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-release

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@m-bronnikov Just curiosity, is there any reason of using `egrep` instead of `find`?

**Comment by m-bronnikov** [comment]
> @m-bronnikov Just curiosity, is there any reason of using `egrep` instead of `find`?

@mhs4670go Personally I see 2 reasons:
1. I would like to make changes in this PR similar to @AShedko's changes applied in internal repo as much as possible (reason why I use `egrep`).
2. `find` tool helps to search **files** in given directory, but current design of `format` command defines `FILES_TO_CHECK` variable  with all files which could be checked using `git` first and then applies search of **strings** by some patterns in `FILES_TO_CHECK` variable to define filespaths for `CPP`, `PYTHON`, PERMISSION`,...etc checks.

**Review by AShedko — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@m-bronnikov Thank you for your explanation:) On second thought with your explanation, the implementation looks better under current design as you said.

**Pull request merged**
