### PR TITLE
[infra] Add arm-none-eabi-gcc.cmake to infra/cmake/packages

### PR DESCRIPTION
**Pull request by SlavikMIPT**
This commit adds arm-none-eabi-gcc.cmake toolchain configuration file which is needed to configure builds for arm microcontrollers.

ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov slavikmipt@gmail.com

### CODE REVIEW

**Comment by SlavikMIPT** [comment]
@nnfw-bot test x64-builder

**Review by jj-crypto — APPROVED** [review]

**Review by jj-crypto — APPROVED** [review]

**Comment by SlavikMIPT** [comment]
@nnfw-bot test x64-builder

**Review by jj-crypto — DISMISSED** [review]

**Comment by SlavikMIPT** [comment]
@nnfw-bot test x64-builder

**Comment by hseok-oh** [comment]
@SlavikMIPT `infra/nnfw/cmake/buildtool/config` directory is toolchain configuration directory for runtime. `compiler/luci-micro/standalone/Toolchain.cmake` looks very compiler (`luci-micro`) specific configuration.

Please use directory under `infra/nncc/cmake` if you want to move into `infra` directory.

**Comment by SlavikMIPT** [comment]
> looks very compiler (`luci-micro`) specific configuration.

It is, but it is needed as a dependency for different components, by moving this config to a common directory I want to avoid cyclical dependencies and duplication

**Comment by SlavikMIPT** [comment]
@hseok-oh @jj-crypto @binarman PTAL

**Review by binarman — DISMISSED** [review]
LGTM

**Comment by hseok-oh** [comment]
Please keep directory policy. `arm-none-eabi-gcc.cmake` is toolchain configuration file, and `infra/cmake/packages` is external library package configuration directory. 

`compiler/luci-micro/standalone/Toolchain.cmake` -> `infra/nncc/cmake/buildtool/config/arm-non-eabi-gcc.cmake`

**Comment by SlavikMIPT** [comment]
> `compiler/luci-micro/standalone/Toolchain.cmake` -> `infra/nncc/cmake/buildtool/config/arm-non-eabi-gcc.cmake`

Done

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by binarman — APPROVED** [review]

**Comment by binarman** [comment]
@jj-crypto ping?

**Comment by seanshpark** [comment]
I'm not sure who @jj-crypto is... he made a LGTM to a PR that has landed several days ago (#7777)
@binarman , I have no objection on landing this PR without @jj-crypto 's approval.

**Pull request merged**
