### PR TITLE
[debian] Update changelog

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit updates changelog for release 1.27.1.

### CODE REVIEW

**Comment by mhs4670go** [comment]
This has been also merged to main branch. Let's merge it to release branch.

**Review by jyoungyun — APPROVED** [review]
LGTM Thank you :)

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by lemmaa — APPROVED** [review]
LGTM. 

----

Based on symentic versioning, it would probably be appropriate to change the minor version. However, to avoid various complicated situations, we will proceed as is this time.

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```
https://semver.org/#summary

**Pull request merged**
