### PR TITLE
Fix false no asserion in TCA

### PR DESCRIPTION
**Pull request by chunseoklee**
by adding redundant SUCCEED

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@chunseoklee , I've seen several warnings but you've added fix for only one.
Can you check again?

**Comment by chunseoklee** [comment]
> @chunseoklee , I've seen several warnings but you've added fix for only one.
> Can you check again?

In my report, there is only 1 warning. Let me check again

**Comment by seanshpark** [comment]
> In my report, there is only 1 warning. Let me check again

The report I've seen is from last week when you asked me to check.

**Comment by chunseoklee** [comment]
I rerun the test with this PR on [link](https://analysishub.sec.samsung.net/service/analyses/1328892). It shows 1 warning and do not fix the issue. I will ask to person in charge of SE.

**Comment by chunseoklee** [comment]
I found tca tool's version diff : 

TCM Version 1.1.1 / Checker Version 0.8.7 (new)

vs

TCM Version 1.0.7 / Checker Version 0.8.3 (old)

**Comment by hseok-oh** [comment]
FYI

### v1.0.8
- fix templateMethod analyze (C / C++)
- add subdirectory Filter Feature
- expand custom assertion option (for all of test framework)

### v1.0.9
- [hotfix] fix bug (java analyze failure)

### v1.1.0
- new feature
  - C# xunit support
  - (develop) MeaninglessAssertion checker added(it can turn on manually until offical release).
- Issue fix
  - bug fix when C/C++ lambda method analyze

### v1.1.1
- Issue fix
  - hot fix when python import statement analyze

**Comment by hseok-oh** [comment]
Similar issue on `runtime/libs/misc/src/tensor/IndexIterator.test.cpp` Line 26.

**Comment by hseok-oh** [comment]
https://github.com/hseok-oh/ONE/tree/tcm_test also cannot resolve issue on runtime

**Comment by hseok-oh** [comment]
@chunseoklee This issue was resolved.

**Pull request closed without merging**
