### PR TITLE
[tizen] Upgrade ruy tar ball

### PR DESCRIPTION
**Pull request by periannath**
- This commit upgrades ruy tar ball to use upgraded ruy library
- Modify spec file to unzip cpuinfo tar ball to externals

ONE-DCO-1.0-Signed-off-by: JiHwan Yeo <jihwan.yeo@samsung.com>

---

For issue: #3231 
From draft: #4074

### CODE REVIEW

**Comment by hseok-oh** [comment]
```
[   49s] -- Download RUY from https://github.com/google/ruy/archive/2e2658f964638ab7aa562d4b48b76007d44e38f0.tar.gz
[   49s] CMake Error at /home/abuild/rpmbuild/BUILD/nnfw-1.10.0/infra/cmake/modules/ExternalSourceTools.cmake:58 (message):
[   49s]   error: downloading
[   49s]   'https://github.com/google/ruy/archive/2e2658f964638ab7aa562d4b48b76007d44e38f0.tar.gz'
[   49s]   failed
[   49s] 
[   49s]                 status_code: 1
[   49s]                 status_string: "Unsupported protocol"
[   49s]                 log: Protocol "https" not supported or disabled in libcurl
[   49s] 
[   49s]   Closing connection -1
[   49s] 
[   49s] Call Stack (most recent call first):
```

This PR makes gbs build fail

- Directory name may invalid
- ruy.tar.gz is updated, but runtime build is not updated yet

Please update tar.gz with ruy version update to check build success

**Review by hseok-oh — CHANGES_REQUESTED** [review]
```
[   49s] -- Download RUY from https://github.com/google/ruy/archive/2e2658f964638ab7aa562d4b48b76007d44e38f0.tar.gz
[   49s] CMake Error at /home/abuild/rpmbuild/BUILD/nnfw-1.10.0/infra/cmake/modules/ExternalSourceTools.cmake:58 (message):
[   49s]   error: downloading
[   49s]   'https://github.com/google/ruy/archive/2e2658f964638ab7aa562d4b48b76007d44e38f0.tar.gz'
[   49s]   failed
[   49s] 
[   49s]                 status_code: 1
[   49s]                 status_string: "Unsupported protocol"
[   49s]                 log: Protocol "https" not supported or disabled in libcurl
[   49s] 
[   49s]   Closing connection -1
[   49s] 
[   49s] Call Stack (most recent call first):
```

This PR makes gbs build fail

- Directory name may invalid
- ruy.tar.gz is updated, but runtime build is not updated yet

Please update tar.gz with ruy version update to check build success

**Comment by periannath** [comment]
@hseok-oh Thanks. I'll test again after #4273 is merged.

**Comment by hseok-oh** [comment]
@periannath Please merge this PR with #4273

**Comment by periannath** [comment]
@hseok-oh Then I'll merge this PR into #4273.

**Pull request closed without merging**
