### PR TITLE
[luci] Rename Propagate QParam Pass

### PR DESCRIPTION
**Pull request by jinevening**
This adds direction of propagation (Forward) to pass name.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
For reviewers:

I renamed the pass because backward propagation pass will be introduced.

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
Can I ask a question?
Since qparam is propagated from output to input, 'backward' (not `forward`) sounds better to me. Maybe I misunderstand the term `forward` and `backward`. Could you explain a bit?

```
/**
 * @brief  Class to propagate quantization parameters of an operator's output to input
 */
struct PropagateQParamForwardPass final : public logo::Pass
```

**Comment by jinevening** [comment]
> Could you explain a bit?

Ah, the comment is wrong. The direction of the pass was changed in #7215, but the comment was not updated. I've updated the comment too. Thanks.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
