### PR TITLE
DRAFT Compiler FE: Enable Rank operator

### PR DESCRIPTION
**Pull request by d-krylov**
Draft for Rank operator

ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@d-krylov , about the task issue. I've made template of steps and modules to check so that one can always be sure about one's work. 
I don't see any issue about `RANK` Op. I;d like to ask about this.
- Forgot to create one
- It's usesless
- It exists but I didn't find it
Which is it for you?

**Comment by d-krylov** [comment]
@seanshpark, @binarman, PTAL, please.

**Comment by seanshpark** [comment]
Looks good! thank you! Please proceed with posting PRs.

**Comment by binarman** [comment]
everything is merged, closing.

**Pull request closed without merging**
