### PR TITLE
[onert/test] Rename tflite_loader_test_tool to tflite_comparator

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit renames tflte_loader_test_tool to tflite_comparator

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: #5213

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@glistening I've rebased. PTAL

**Comment by hseok-oh** [comment]
@glistening Ping

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
