### PR TITLE
[one-cmds] Invoke preprocessing script for numpy files 

### PR DESCRIPTION
**Pull request by Seunghui98**
This invokes preprocessing script for numpy files in prepare_test_materials.sh.

ONE-DCO-1.0-Signed-off-by: SeungHui Lee <shsh1004.lee@samsung.com>

---
Related Issue: https://github.com/Samsung/ONE/issues/12053
Draft PR: https://github.com/Samsung/ONE/pull/12186

### CODE REVIEW

**Comment by seanshpark** [comment]
I can't match title/commit message and actual change of this PR. Please fix the title/commit message so that it expresses the change.

**Comment by Seunghui98** [comment]
@seanshpark 

Okay. Thank you for comment.
I modified title/commit message. :)

**Comment by seanshpark** [comment]
@Seunghui98 you've changed `Introduce` to `Add`...
There is `CMakeLists.txt` in explanation but I do not see any changes for that file.
There is `proprocess_images_numpy script` in explanation but I do not see any addition of that file.

**Comment by Seunghui98** [comment]
@seanshpark 

I'm sorry to have confused you. 😅
The title and commit message were modified again to match the length of the limit. :)

**Comment by seanshpark** [comment]
Current title: `Add preprocess_images_numpy script`

What is changed: `compiler/one-cmds/tests/prepare_test_materials.sh` file

I don't see any new `preprocess_images_numpy` script.
What I see is `prepare_test_materials.` is changed to invoke `preprocess_images_numpy` script with some conditions. 

Please update the title and commit message to reflect this.

**Review by jinevening — APPROVED** [review]
LGTM

(optional) I would rather write a commit message as below.

```
[one-cmds] Invoke preprocessing script for numpy files

This invokes preprocessing script for numpy files in prepare_test_materials.sh.
```

**Review by seanshpark — APPROVED** [review]

**Pull request merged**
