### PR TITLE
[one-cmds] Extends the point where codegen finds backends

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit extends the point where `one-codegen` finds backends.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@seanshpark please review this PR:)

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
2 more reviews needed

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
