### PR TITLE
[tools/tflitefile_tool] Add io info of original model to io file

### PR DESCRIPTION
**Pull request by ragmani**
This commit adds io info of original model to generated io file.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
```bash
$ ./tools/tflitefile_tool/select_operator.py mobilenet_v1_1.0_224.tflite 0-26.txt m1.tflite --store-io-info m1.json
Input tensor(s): [81]
Output tensor(s): [44]
Append subgraphs, orginal index :  0 , new index :  0
$ ./tools/tflitefile_tool/select_operator.py mobilenet_v1_1.0_224.tflite 27-30.txt m2.tflite --store-io-info m2.json
Input tensor(s): [6]
Output tensor(s): [7]
Append subgraphs, orginal index :  0 , new index :  0
$ cat m1.json
{"org-model": {"inputs": {"org": [88], "new": [81]}, "outputs": {"org": [87], "new": [-1]}}, "new-model": {"inputs": {"org": [88], "new": [81]}, "outputs": {"org": [50], "new": [44]}}}
$ cat m2.json
{"org-model": {"inputs": {"org": [88], "new": [-1]}, "outputs": {"org": [87], "new": [7]}}, "new-model": {"inputs": {"org": [50], "new": [6]}, "outputs": {"org": [87], "new": [7]}}}
```

**Comment by ragmani** [comment]
@glistening @hseok-oh PTAL

**Comment by glistening** [comment]
@ragmani I don't understand the meaning of the followings:

> {"org-model": {"inputs": {"org": [88], "new": [81]}, "outputs": {"org": [87], "new": [-1]}}, "new-model": {"inputs": {"org": [88], "new": [81]}, "outputs": {"org": [50], "new": [44]}}}
$ cat m2.json
{"org-model": {"inputs": {"org": [88], "new": [-1]}, "outputs": {"org": [87], "new": [7]}}, "new-model": {"inputs": {"org": [50], "new": [6]}, "outputs": {"org": [87], "new": [7]}}}

- `org-model` and `new-model` : I guess `org-model` is the original model before selection. `new-model` is selected model.
- `org` and `new` : I don't know the meaning of `org-model`'s `new`
-  and so on

**Comment by ragmani** [comment]
Here is the result of splitting inception model.

```bash
- 0-94
$ cat i1.json 
{"org-model": {"inputs": {"org": [316], "new": [247]}, "outputs": {"org": [314], "new": [-1]}}, "new-model": {"inputs": {"org": [316], "new": [247]}, "outputs": {"org": [165, 173, 175], "new": [165, 173, 175]}}}
- 95-108
$ cat i2.json 
{"org-model": {"inputs": {"org": [316], "new": [-1]}, "outputs": {"org": [314], "new": [-1]}}, "new-model": {"inputs": {"org": [165, 173, 175], "new": [0, 1, 2]}, "outputs": {"org": [198], "new": [25]}}}
- 109-113
$ cat i3.json 
{"org-model": {"inputs": {"org": [316], "new": [-1]}, "outputs": {"org": [314], "new": [-1]}}, "new-model": {"inputs": {"org": [198], "new": [0]}, "outputs": {"org": [199, 207], "new": [1, 9]}}}
- 114-120
$ cat i4.json 
{"org-model": {"inputs": {"org": [316], "new": [-1]}, "outputs": {"org": [314], "new": [-1]}}, "new-model": {"inputs": {"org": [198], "new": [0]}, "outputs": {"org": [216, 218], "new": [9, 11]}}}
- 121-124
$ cat i5.json 
{"org-model": {"inputs": {"org": [316], "new": [-1]}, "outputs": {"org": [314], "new": [9]}}, "new-model": {"inputs": {"org": [199, 207, 216, 218], "new": [0, 1, 2, 3]}, "outputs": {"org": [314], "new": [9]}}}
```

And it's okay to remove "org" of "org-model" from json results.

**Comment by glistening** [comment]
@ragmani Let me think more. I still don't fully understand. I am thinking the followings:

1. If we are creating a package by partitioning existing one model, the user interface and implementation may be simpler. 

For the case of your example in https://github.com/Samsung/ONE/pull/10196#issuecomment-1353103276,

I am thinking of the user interface like:
```
$ partition2nnpkg -p 0-94:95-108:109-113:114-120:121-124 inceptionv3_slim_2016.tflite 
Generating nnpkg...
```
2. For selecting op from circle model, we may need similar work on `circle-opselector`.

3. I also want to remove `jq` dependency if possible.

**Comment by ragmani** [comment]
> If we are creating a package by partitioning existing one model, the user interface and implementation may be simpler.

I will create a new python script to create nnpkg by partitioning existing one model once.

> For selecting op from circle model, we may need similar work on circle-opselector.

To use `circle-opselector`, we should build `circle-opselector` and I don't know about it.  I consider it later.

> I also want to remove jq dependency if possible.

`model2nnpkg` is shell script. It's too difficult to parse json without `jq`. I can move the part of parsing json out of `model2nnpkg` instread.

**Comment by ragmani** [comment]
I modified name of elements and removed unnecessary emelemts.
```bash
$ cat m1.json 
{"org-model-io": {"inputs": {"new-indices": [81]}, "outputs": {"new-indices": [-1]}}, "new-model-io": {"inputs": {"org-indices": [88], "new-indices": [81]}, "outputs": {"org-indices": [50], "new-indices": [44]}}}
$ cat m2.json
{"org-model-io": {"inputs": {"new-indices": [-1]}, "outputs": {"new-indices": [7]}}, "new-model-io": {"inputs": {"org-indices": [50], "new-indices": [6]}, "outputs": {"org-indices": [87], "new-indices": [7]}}}
```

**Comment by ragmani** [comment]
@glistening @hseok-oh PTAL

**Comment by glistening** [comment]
@ragmani  

Here is `m1.json` reformatted.

```json
{
    "org-model-io": {
        "inputs": {
            "new-indices": [
                81
            ]
        },
        "outputs": {
            "new-indices": [
                -1
            ]
        }
    },
    "new-model-io": {
        "inputs": {
            "org-indices": [
                88
            ],
            "new-indices": [
                81
            ]
        },
        "outputs": {
            "org-indices": [
                50
            ],
            "new-indices": [
                44
            ]
        }
    }
}
```

, and the following is my interpretation.

- original model has 1 input and 1 output
  - The only input is located at tensors[81] from new model.
  - The only output has new-index **-1**, which means it is not in new-model.
- new-model has 1 input and 1 output
  - The only input was located at tensors[88] from org model, and it is located at tensors[81] from new model.
  - The only output was located at tensors[50] from org model, and it is located at tensors[44] from new model.

Could you please check it is right?

**Comment by ragmani** [comment]
@glistening 

> Could you please check it is right?
Exactly. Could I append the interpretation in README.md?

**Review by glistening — APPROVED** [review]
LGTM

@ragmani 

> Exactly. Could I append the interpretation in README.md?

Sure!

**Review by hseok-oh — APPROVED** [review]

**Pull request merged**
