### PR TITLE
[doc] Minor improvements of the overview docs

### PR DESCRIPTION
**Pull request by pfusik**

### CODE REVIEW

**Comment by seanshpark** [comment]
@pfusik , thanks for the update!

can you please check https://github.com/Samsung/ONE/wiki/ONE-Developer%27s-Certificate-of-Origin ?

and please add some comments about the change like other PRs. 
something like

```
Minor style improvements of the overview docs

This will apply some minor style improvements of the overview docs.

ONE-DCO-1.0-Signed-off-by: ....
```

**Comment by seanshpark** [comment]
ping @lemmaa

**Comment by pfusik** [comment]
@seanshpark I edited the commit message as you suggested.

**Review by lemmaa — APPROVED** [review]
LGTM. Thank you!

By the way, this content needs to be updated.

**Pull request merged**
