### PR TITLE
[infra] Add dh-python to focal Dockerfile

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds `dh-python` to focal Dockerfile.

Related: #6978 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
It's weird. `python3-all` package depends on `dh-python` but focal docker container doesn't have it..

**Comment by seanshpark** [comment]
Title `pr[infra]`, what is `pr` for?

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-runtime-test-debug

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@hseok-oh PTAL:)

**Review by hseok-oh — APPROVED** [review]

**Pull request merged**
