### PR TITLE
[infra/gbs] Update nncc build list for mio-circle06

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit adds to mio-circle06 build list to prepare circle version up.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
We should have update this with #11440...

**Review by jinevening — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
