### PR TITLE
[circle-quantizer] verify circle file

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit enables circle-quantizer to verify circle file.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-release

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Comment by ragmani** [comment]
Please rebase this

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
