### PR TITLE
[debian] Add postrm script

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds postrm script. This script removes virtualenv file at the end of `apt purge` step.

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Maybe remove symbolic links? or removed by `dpkg` ?

**Comment by mhs4670go** [comment]
@seanshpark Yes. Symbolic things are removed by `dpkg`. Only python things are still there after removing package.

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by seanshpark** [comment]
@nnfw-bot test cross-runtime-test-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
