### PR TITLE
[luci] Introduce TestFirstNode

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce TestFirstNode providing first_node method that will
return first node of a type in the graph.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
From #6111

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

I think `target_nodes<T>(g)` could be introduced as well that returns set of T in g.

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
