### PR TITLE
[CI] Jenkinsfile for CI

### PR DESCRIPTION
**Pull request by hseok-oh**
Introduce jenkinsfile for format-checker (jenkins multibranch project)

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test format-checker

**Comment by hseok-oh** [comment]
@nnfw-bot test format-checker

**Comment by hseok-oh** [comment]
@nnfw-bot test format-checker

**Comment by hseok-oh** [comment]
@nnfw-bot test format-checker

**Comment by hseok-oh** [comment]
We will use github action

**Review by jj-crypto — APPROVED** [review]

**Pull request closed without merging**
