### PR TITLE
[onert/trix] Build on higher version

### PR DESCRIPTION
**Pull request by hseok-oh**
Let's assume that trix-engine support backend compatibility.

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM ( Same change is required for frontend. I am okay for you or me to make another PR for frontend. )

**Comment by hseok-oh** [comment]
@glistening I've updated for frontend. PTAL

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
