### PR TITLE
[infra] Revise scripts to include mio-circle04

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise scripts to include mio-circle04.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #8664, from draft #8668

**Comment by seanshpark** [comment]
cc @yunjayh

**Review by hseok-oh — APPROVED** [review]

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@nnfw-bot test x64-builder

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder
@nnfw-bot test cross-runtime-test-release
@nnfw-bot test cross-runtime-test-debug
@nnfw-bot test cross-aarch64-runtime-test-release

**Pull request merged**
