### PR TITLE
[luci-interpreter] Add negative tests for MUL op

### PR DESCRIPTION
**Pull request by binarman**
This PR adds several negative tests for mul op.

ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by binarman** [comment]
@nnfw-bot test nncc-debug

**Comment by binarman** [comment]
@nnfw-bot test nncc-debug

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Review by kvochko — APPROVED** [review]
LGTM

**Pull request merged**
