### PR TITLE
[common-artifacts] exclude NYI OP from tc generation

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit excludes NYI OP from tc generation

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
@seanshpark I've fixed typo in the commit. PTAL:)

**Comment by mhs4670go** [comment]
@seanshpark sorry lots of mistakes:( PTAL

**Comment by seanshpark** [comment]
I'll wait for test results :)

**Comment by seanshpark** [comment]
Related with https://github.com/Samsung/ONE/issues/457#issuecomment-654066181 ?

**Comment by mhs4670go** [comment]
@seanshpark 
> Related with #457 (comment) ?

Right

**Pull request merged**
