### PR TITLE
[visq] Use quoted node name

### PR DESCRIPTION
**Pull request by jinevening**
This uses quoted node name.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
To reviewers:

This PR allows to use not-allowed characters for node ID. For example, colon `:`. Without this PR, colon is ignored in the dot graph.

**Review by seanshpark — DISMISSED** [review]
LGTM

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
@seanshpark @mhs4670go I've fixed the test error. PTAL

My local machine used cached (previous) code, so the test failure was not detected.. Sorry for repeated review requests.

**Comment by seanshpark** [comment]
> Sorry for repeated review requests.

Not a problem :)

**Review by mhs4670go — APPROVED** [review]

**Pull request merged**
