### PR TITLE
[tool/kernel_report] Remove onert base directory from argument

### PR DESCRIPTION
**Pull request by periannath**
- This commit removes onert base directory from argument
  - This script finds onert base directory by using relative path from its absolute path

ONE-DCO-1.0-Signed-off-by: JiHwan Yeo <jihwan.yeo@samsung.com>

### CODE REVIEW

**Review by hseok-oh — APPROVED** [review]
LGTM 

This script is outdated.

**Comment by periannath** [comment]
@hseok-oh I'm planning to use this script to find supported operations for newly introduced backends (`ruy` and `xnnpack`). 

> This script is outdated.

Is that mean this script is not working as expected?

**Comment by hseok-oh** [comment]
>Is that mean this script is not working as expected?

This script is introduced to report which tflite(circle) operation is supported by backends. But kernel generator use runtime's IR, and runtime IR is not 1:1 mapping with tflite(circle) operation any more. So it is outdated.

**Comment by periannath** [comment]
@hseok-oh Ah, I dind't know that. Thanks for explaining in detail.

**Pull request merged**
