### PR TITLE
[luci-interpreter] Remove type conversion warning

### PR DESCRIPTION
**Pull request by jinevening**
This removes type conversion warning

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
@llFreetimell Can you check this PR can remove the warning?

**Review by llFreetimell — APPROVED** [review]
LGTM, Thanks!

**Comment by llFreetimell** [comment]
@jinevening I can check after this PR is merged :( After this PR merged, I will check it!

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
