### PR TITLE
[onert] Remove IOptimizer and ITensorBuilder

### PR DESCRIPTION
**Pull request by wateret**
Remove legacy backend interface classes -
IOptimizer and ITensorBuilder.

Each backend still make use of their Optimizer and TensorBuilder, but
they do not derive from parent interface classes.

Draft: #5272

ONE-DCO-1.0-Signed-off-by: Hanjoung Lee <hanjoung.lee@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
```
16:31:48 CMakeFiles/onert_backend_xnnpack.dir/BackendContext.cc.o: In function `onert::backend::xnnpack::BackendContext::genKernels(std::__ndk1::vector<onert::util::Index<unsigned int, onert::ir::OpSequenceIndexTag>, std::__ndk1::allocator<onert::util::Index<unsigned int, onert::ir::OpSequenceIndexTag> > > const&, onert::ir::OpSequences const&)':
16:31:48 BackendContext.cc:(.text._ZN5onert7backend7xnnpack14BackendContext10genKernelsERKNSt6__ndk16vectorINS_4util5IndexIjNS_2ir18OpSequenceIndexTagEEENS3_9allocatorIS9_EEEERKNS7_11OpSequencesE+0x12c): undefined reference to `onert::backend::xnnpack::BackendContext::initConsts()'
```

**Comment by seanshpark** [comment]
```
16:24:16 [ RUN      ] TrivialTest.AddTwo
16:24:17 /jenkins_slave/workspace/nnfw/master/pr-x64-builder-tester/Product/out/test/command/unittest: line 80:   363 Segmentation fault      (core dumped) $TEST_BIN $(get_gtest_option)
```

**Comment by wateret** [comment]
@seanshpark PTAL :)

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
