### PR TITLE
[one-cmds] Enable fuse_horizontal_fc_layers

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This commit enables fuse_horizontal_fc_layers option for one-cmds optimize.

for issue: https://github.com/Samsung/ONE/issues/11705
from draft: https://github.com/Samsung/ONE/pull/11739

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
@BalyshevArtem Could you add this option to O1?

**Comment by BalyshevArtem** [comment]
> @BalyshevArtem Could you add this option to O1? This option is safe and beneficial in general.

Sure

**Pull request merged**
