### PR TITLE
DRAFT Compiler FE: Enable Round operator 

### PR DESCRIPTION
**Pull request by d-krylov**
Draft - Enable Round operator 

ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@d-krylov , about the task issue. I've made template of steps and modules to check so that one can always be sure about one's work. 
I don't see any issue about `ROUND` Op. I;d like to ask about this.
- Forgot to create one
- It's usesless
- It exists but I didn't find it
Which is it for you?

**Comment by d-krylov** [comment]
Oh, I forgot to create it. Thank you for reminding.

**Comment by seanshpark** [comment]
Thank you! Looks good. Please proceed with posting PRs

**Comment by binarman** [comment]
Everything from this PR is merged, closing

**Pull request closed without merging**
