### PR TITLE
[one-cmds] Remove `-b` option from `one-infer`

### PR DESCRIPTION
**Pull request by yunjayh**
This commit removes `-b` option from `one-infer`.
Since `-d|--driver` includes the usage of `-b|--backend`, `-b` option has been trimmed. And also, corresponding tests are fixed respectively.

Signed-off-by: yunjay-hong <yunjay.hong@samsung.com>

---

The help message has been changed like this. (epilog is added after the arguments. Any suggestion is welcome!!)

```text
$ ./bin/one-infer -h
usage: one-infer [-h] [-v] [-C CONFIG] [-d DRIVER] [--post-process POST_PROCESS] [--] [COMMANDS FOR BACKEND DRIVER]

command line tool to infer model

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -V, --verbose         output additional information to stdout or stderr
  -C CONFIG, --config CONFIG
                        run with configuation file
  -d DRIVER, --driver DRIVER
                        backend inference driver name to execute
  --post-process POST_PROCESS
                        post processing python script and arguments which can be used to convert I/O data to standard format

one-infer provides post-processing after invoking backend inference driver
use python script and its arguments to '--post-process' argument as below
one-infer -d dummy-infer --post-process "script.py arg1 arg2" -- [arguments for dummy-infer]
```

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
(out of curiosity) Why `one-infer` uses different option for seeming same purpose? For example, `one-profile` uses `-b` to specify backend. But `one-infer` uses `-d` to specify driver. What is the difference between `backend` and `driver` ?

**Comment by yunjayh** [comment]
> (out of curiosity) `one-profile` uses `-b` to specify backend. But `one-infer` uses `-d` to specify driver. What is the difference between `backend` and `driver` ?

That's a good question! 
`-b` option in `one-profile` searches a executable which name is `{backend}-profile`.
`-d` option for `one-infer` searches a executable which name is given `{driver}`. 

`-d` is suggested since (1) our npu backend currently doesn't use `{backend}-infer` format as its inference binary and (2) to use other interpreter scripts, such as `circle-interpreter` .

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
