### PR TITLE
[luci] Support quantization of FloorDiv 

### PR DESCRIPTION
**Pull request by dayo09**
This commit enables floor div operation's quantization unit test.

DCO-ONE-1.0-Signed-off-by: Dayoung Lee <dayg502@gmail.com>

--------------

For #6367 
Ready after #6503 is merged

### CODE REVIEW

**Comment by dayo09** [comment]
This will be rebased after div.
Div and Floordiv PR don't conflict in their contents, but as merge conflict happens so frequently, I just included div commit.

**Comment by dayo09** [comment]
Rebased and ready to be merged :-D

**Review by jinevening — APPROVED** [review]
LGTM Thank you

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
