### PR TITLE
[contrib/android] Introduce android.x test for java api

### PR DESCRIPTION
**Pull request by YongseopKim**
Introduce android.x test for validating java apis.
In this commit, the only positive unit tests are supported.

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
for https://github.com/Samsung/ONE/issues/4772

**Comment by YongseopKim** [comment]
current problem.

nnfwapi's opendir() errors EACCESS (Permission denied)
```
04-20 22:19:23.009 20354 20379 E ONERT_NATIVE: NNFW_STATUS nnfw_session::load_model_from_file(const char *)] invalid nnpackge directory(/sdcard/nnpkg/convolution_test) because of Permission denied
```

This log always appeares.
```
04-20 22:29:46.439 20916 20948 W System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
04-20 22:29:46.440 20916 20948 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:496)
04-20 22:29:46.440 20916 20948 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
04-20 22:29:46.440 20916 20948 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
04-20 22:29:46.440 20916 20948 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
04-20 22:29:46.440 20916 20948 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
04-20 22:29:46.440 20916 20948 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
04-20 22:29:46.441 20916 20948 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
04-20 22:29:46.441 20916 20948 W System.err:    at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
04-20 22:29:46.441 20916 20948 W System.err:    at com.samsung.onert.Session.$jacocoInit(Unknown Source:13)
04-20 22:29:46.441 20916 20948 W System.err:    at com.samsung.onert.Session.<init>(Unknown Source:0)
04-20 22:29:46.441 20916 20948 W System.err:    at com.samsung.onert.TestSession.test_Session_p(TestSession.java:40)
04-20 22:29:46.441 20916 20948 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-20 22:29:46.441 20916 20948 W System.err:    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
04-20 22:29:46.441 20916 20948 W System.err:    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
04-20 22:29:46.441 20916 20948 W System.err:    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
04-20 22:29:46.442 20916 20948 W System.err:    at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
04-20 22:29:46.442 20916 20948 W System.err:    at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
04-20 22:29:46.442 20916 20948 W System.err:    at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:130)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-20 22:29:46.442 20916 20948 W System.err:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-20 22:29:46.443 20916 20948 W System.err:    at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.Suite.runChild(Suite.java:128)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.Suite.runChild(Suite.java:27)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
04-20 22:29:46.443 20916 20948 W System.err:    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
04-20 22:29:46.444 20916 20948 W System.err:    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
04-20 22:29:46.444 20916 20948 W System.err:    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
04-20 22:29:46.444 20916 20948 W System.err:    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
04-20 22:29:46.444 20916 20948 W System.err:    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
04-20 22:29:46.444 20916 20948 W System.err:    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
04-20 22:29:46.444 20916 20948 W System.err:    at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
04-20 22:29:46.444 20916 20948 W System.err:    at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
04-20 22:29:46.444 20916 20948 W System.err:    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2209)
04-20 22:29:46.445 20916 20948 W System.err: Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
04-20 22:29:46.445 20916 20948 W System.err:    at libcore.io.Linux.open(Native Method)
04-20 22:29:46.445 20916 20948 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-20 22:29:46.445 20916 20948 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
04-20 22:29:46.445 20916 20948 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-20 22:29:46.445 20916 20948 W System.err:    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7893)
04-20 22:29:46.445 20916 20948 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:482)
04-20 22:29:46.445 20916 20948 W System.err:    ... 42 more
```

**Comment by YongseopKim** [comment]
I cannot solve the problem. For now, I close and then will reopen this.

**Comment by periannath** [comment]
FYI. https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df

> Apps targeting Android 10 (API level 29) and higher are given scoped access into an external storage device, or scoped storage, by default. Such apps can see only their app-specific directory
> If your app is not ready for the changes that are coming in for Android 10 then you can “opt-out” by setting the flag requestLegacyExternalStorage to true in your manifest.

I'm not sure but adding `<application android:requestLegacyExternalStorage="true" ... >` might solve this issue.

**Pull request closed without merging**
