### PR TITLE
[one-cmds] Add missing option for reshape_matmul.circle

### PR DESCRIPTION
**Pull request by jinevening**
This adds a missing option to create reshape_matmul.circle

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/10555#issuecomment-1484501455

### CODE REVIEW

**Comment by jinevening** [comment]
This PR will resolve

one-quantize_016.test FAILED
onecc_045.test FAILED

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
Why wasn't it fail when the `one-quantize_016.test` was introduced..?

**Comment by jinevening** [comment]
> Why wasn't it fail when the one-quantize_016.test was introduced..?

prepare_test_materials.sh was updated after one-quantize_016.test is added.

**Comment by mhs4670go** [comment]
The failed PR in the CI is #10530 but the updating PR is #10554. Hmm..

**Comment by jinevening** [comment]
I think there are different problems here. PTAL https://github.com/Samsung/ONE/issues/10555#issuecomment-1484546594

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
