### PR TITLE
[luci-interpreter] throw error when the memory limit exceeded

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds an exception of memroy limit exceeded.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
may need two or more reviewers for relelase branch.

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@hseok-oh , CI was canceled by you. can you please trigger when CI is ready?

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug nncc-release

**Comment by seanshpark** [comment]
> At least 3 approving

@lemmaa PTAL

**Comment by mhs4670go** [comment]
> @mhs4670go , by the way, where can I find the original copy of this PR in the master branch?

https://github.com/Samsung/ONE/pull/9769 Please see this one.

**Pull request merged**
