### PR TITLE
[DRAFT] Support Reduce Max operation

### PR DESCRIPTION
**Pull request by d-krylov**
Support Reduce Max operation in luci import, lang, tests

ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>

### CODE REVIEW

**Comment by binarman** [comment]
@seanshpark 
We already merged tflchef for this operator (#238 ).
Is it ok, if this PR will not contain it?

If you want to see all changes (including tflchef) we can do it.

**Comment by seanshpark** [comment]
> We already merged tflchef for this operator (#238 ).
Is it ok, if this PR will not contain it?

It is OK to rebase master and also OK with already landed changes are not here :)

**Comment by binarman** [comment]
new draft in #1335
moved because after ONE repo `private->public` transition we can not update this PR

**Comment by binarman** [comment]
@jinevening @llFreetimell FYI Your comments are fixed

**Pull request closed without merging**
