### PR TITLE
[onert] Introduce MutableOperationVisitor

### PR DESCRIPTION
**Pull request by ragmani**
This commit introduces MutableOperationVisitor that can modify operation itself.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
It is necessary to introduce `MutableOperationVisitor` for the following reason:
- `OperationVisitor`'s `visit()` method has only one `const ir::Operation` argument.
- There is also no index information in `visit()` method to find an operation in `Graph`.
So, we `OperationVisitor` cannot modify operation itself in `visit()` method.

**Comment by ragmani** [comment]
@nnfw-bot test onert-x64-release

**Review by glistening — APPROVED** [review]
LGTM :+1:

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]

**Comment by ragmani** [comment]
I will consider more about how to separate into `Operation` and `TrainableOperation`. Please wait for merging this PR.

**Comment by ragmani** [comment]
This PR is discarded.

**Pull request closed without merging**
