### PR TITLE
[tools/onert_train] Measure training speed in one step

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit measures training speed in one step and show the time result in logs.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Draft: #11035

### CODE REVIEW

**Comment by jyoungyun** [comment]
@nnfw-bot test onert-x64-release

**Review by ragmani — APPROVED** [review]

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
@jyoungyun I am waiting for https://github.com/Samsung/ONE/pull/11373#discussion_r1308507284.

**Review by ragmani — APPROVED** [review]

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Comment by ragmani** [comment]
@nnfw-bot test onert-x64-release

**Pull request merged**
