### PR TITLE
[one-cmds] Use lower column limit in one-quantize

### PR DESCRIPTION
**Pull request by jinevening**
This uses lower column limit in one-quantize.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug nncc-release nncc-jammy-debug

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug nncc-release nncc-jammy-debug

**Comment by hseok-oh** [comment]
@nnfw-bot test all

**Pull request merged**
