### PR TITLE
[DRAFT] Compiler FE Support for LOG Op

### PR DESCRIPTION
**Pull request by kishcs**
On-going draft PR to support LOG Op

ONE-DCO-1.0-Signed-off-by: kishore.cs <kishore.cs@samsung.com>

Ref: #953

### CODE REVIEW

**Comment by seanshpark** [comment]
Codes seems OK,
If you fix `format checker` failure, we can see build result of this patch.

**Comment by seanshpark** [comment]
Please proceed posting PRs :)

**Comment by kishcs** [comment]
> Please proceed posting PRs :)

Okay.. :)

**Comment by kishcs** [comment]
All the modules added for Log.
So closing the draft.

**Pull request closed without merging**
