### PR TITLE
[infra] Install flatbuffers to docker image

### PR DESCRIPTION
**Pull request by jinevening**
This installs flatbuffers to docker image.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/10287

### CODE REVIEW

**Comment by jinevening** [comment]
To reviewers: I guess that this can resolve #10287.

**Comment by seanshpark** [comment]
compiler and onert both uses flatbuffers from source.
I think installing flatbuffers python package is OK but can you check this in local?

@hseok-oh , if you think local test is not needed we can go as-is.
if you think local test is needed, can you please help @jinevening if he needs some?

**Comment by hseok-oh** [comment]
No problem on this PR. But I wonder it really resolves #10287.

**Review by hseok-oh — APPROVED** [review]

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> But I wonder it really resolves

@jinevening , let's try again with this patch.
if python somehow didn't find flatbuffers, it may fail to find other packages.

**Comment by hseok-oh** [comment]
@jinevening CI infra docker images are updated.

**Pull request merged**
