### PR TITLE
[python] Speed up memory allocation of empty numpy arrays for inputs and outputs

### PR DESCRIPTION
**Pull request by jiwaszki**
This commit is replacing slower list initialization with faster numpy call to create empty inputs and outputs for a `nnfw_session`.

ONE-DCO-1.0-Signed-off-by: Jan Iwaszkiewicz <j.iwaszkiewi@samsung.com>

### CODE REVIEW

**Comment by jiwaszki** [comment]
Here is a difference between both approaches:
```python
In [1]: import numpy as np

In [2]: %timeit _ = np.array([0.] * (2**16), dtype=np.float32)
1.34 ms ± 4.46 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [3]: %timeit _ = np.zeros((2**16), dtype=np.float32)
4.19 μs ± 0.743 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [4]: %timeit _ = np.array([0.] * 268203, dtype=np.float32)  # example input of model like Inception
5.43 ms ± 38 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [5]: %timeit _ = np.zeros((268203), dtype=np.float32)  # example input of model like Inception
25.1 μs ± 34.8 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@jiwaszki Is it just draft?

**Comment by jiwaszki** [comment]
@hseok-oh I just made it ready for review. Thank you for keeping an eye on it!

**Comment by hseok-oh** [comment]
Commit body requires at least 4 words (except title and email line). Please update your commit message.

**Comment by jiwaszki** [comment]
@hseok-oh thank you, I hope the commit looks ok now.

**Pull request merged**
