### PR TITLE
[onert] Fix the wrong creation of type-aware quantization.

### PR DESCRIPTION
**Pull request by ragmani**
This commit fixes the wrong creation of type-aware quantization.
  - Fix what doesn't work if there are more than 2 `from` in a model
  - Renaming `type_aware_quant` to `edge_quant`

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

---
For https://github.com/Samsung/ONE/issues/10002
Draft https://github.com/Samsung/ONE/pull/10329

### CODE REVIEW

**Comment by ragmani** [comment]
This PR is a part of #10455

**Comment by hseok-oh** [comment]
Rebase?

**Comment by ragmani** [comment]
> Rebase?

Ah.. I was missing this.
I will.

**Review by hseok-oh — APPROVED** [review]

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
