### PR TITLE
[infra/onert] Remove boost usage on infra resources

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit removes boost library usage on cmake, makefile, bash script and documentation.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM

**Review by ragmani — DISMISSED** [review]
LGTM

**Review by zetwhite — APPROVED** [review]
LGTM :+1:

**Comment by hseok-oh** [comment]
I've force pushed by my mistake... PTAL @glistening @zetwhite @ragmani

**Review by zetwhite — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Pull request merged**
