### PR TITLE
[lib/tflite] Remove OpResolve extension

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit removes OpResolver extension library and use TFLite original OpResolver.

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Draft: #7347
Related issue: #7346

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by chunseoklee** [comment]
```
18:41:32  ok 14 - conv_2d/convolution2
18:41:32  not ok 15 - custom/squared_difference
18:41:32  ok 16 - depthwise_conv_2d/depthconv1
```

**Comment by hseok-oh** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by hseok-oh** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by hseok-oh** [comment]
@chunseoklee tizen armcl package v21.02 is not uploaded in `nnfw.mooo.com`.

**Comment by chunseoklee** [comment]
it is weird since download.tizen has http://download.tizen.org/snapshots/tizen/unified/latest/repos/standard/packages/armv7l/libarmcl-devel-v21.02-19.16.armv7l.rpm

**Comment by chunseoklee** [comment]
@hseok-oh We have not built for gbs-tizen recently ?

**Comment by hseok-oh** [comment]
@chunseoklee We've built on internal server only, not on aws.

**Comment by chunseoklee** [comment]
I will upload packages. Anyway it is strange that gbs stop searching v21.02 when it found v19.05.

**Comment by hseok-oh** [comment]
>Anyway it is strange that gbs stop searching v21.02 when it found v19.05.

Yes. It looks strange.

**Comment by chunseoklee** [comment]
@nnfw-bot test tizen-gbs-builder

**Comment by chunseoklee** [comment]
@nnfw-bot test tizen-gbs-builder

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
