### PR TITLE
[infra] Revise compiler_modules

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise compiler_modules script to include luci-eval-driver and
luci-pass-value-test.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
From draft #5904

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test x64-builder

**Pull request merged**
