### PR TITLE
[onert] Introduce training feature flag 

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduces training feature build flag to disable on tizen build.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Test build on ubuntu: `make OPTIONS=-DENABLE_ONERT_TRAIN=OFF'

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Review by glistening — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
