### PR TITLE
[onert] Introduce getCustomOpAttrMap in BaseLoader

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduces helper function getCustomOpAttrMap to get custom op's attribute.

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

---

Related issue: https://github.com/Samsung/ONE/issues/8786

### CODE REVIEW

**Review by ragmani — APPROVED** [review]
LGTM (How about changing the function name to `getCustomOptAttrMap` or `getCustomOptionAttrMap`? I think `CustomOp` is ambiguous)

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@ragmani `getCustomOpAttrMap` means "get custom operation's attribute map". So I used this name.

**Comment by ragmani** [comment]
Sorry, I mistook them for not custom operation .

**Pull request merged**
