### PR TITLE
[luci-interpreter] Rename Prelu->PRelu

### PR DESCRIPTION
**Pull request by SlavikMIPT**
This commit renames Prelu->PRelu class and .cpp/.h files to support configurable build.

Draft: https://github.com/Samsung/ONE/pull/7304

ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <slavikmipt@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
> compiler/luci-interpreter/src/loader/KernelBuilder.cpp:62:10: fatal error: kernels/Prelu.h: No such file or directory
21:58:27  #include "kernels/Prelu.h"

**Comment by SlavikMIPT** [comment]
@nnfw-bot test nncc-debug

**Comment by SlavikMIPT** [comment]
@nnfw-bot test nncc-release

**Comment by SlavikMIPT** [comment]
@nnfw-bot test nncc-debug

**Comment by SlavikMIPT** [comment]
@nnfw-bot test nncc-release

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
