### PR TITLE
[luci] Names of nodes in Pass test

### PR DESCRIPTION
**Pull request by seanshpark**
This will set names for nodes in Pass test.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #5913, from draft #6013

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@seanshpark Setting the name is what we should do even if it isn't used in the test?

**Comment by seanshpark** [comment]
> Setting the name is what we should do even if it isn't used in the test?

It's not used (to export or some kind) but new CircleNode that reference this will access the name and set the new node name with that name. Logically it seems strange if it's empty...
I'm adding `assert(name.length() > 0);` in accessing the name in all Passes to know if the node name is valid or not.

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
