### PR TITLE
[circle2circle] Add resolve_former_customop

### PR DESCRIPTION
**Pull request by Seunghui98**
This commit adds resolve_former_customop to circle2circle2.

ONE-DCO-1.0-Signed-off-by: SeungHui Lee <shsh1004.lee@samsung.com>

---
Related to Issue: https://github.com/Samsung/ONE/issues/10784
Draft PR: [#10737](https://github.com/Samsung/ONE/pull/11701)

### CODE REVIEW

**Comment by seanshpark** [comment]
CI is busy with internal maintenance ...

**Comment by hseok-oh** [comment]
@nnfw-bot test all

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
