### PR TITLE
DRAFT: Support requantization from int8 to uint8

### PR DESCRIPTION
**Pull request by jinevening**
On going draft to support requantization from int8 to uint8

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to #3779

### CODE REVIEW

**Comment by seanshpark** [comment]
Please revise related tool in one-cmds

**Comment by jinevening** [comment]
> Please revise related tool in one-cmds

This feature will not be included in the release package, so it is unnecessary.

**Comment by seanshpark** [comment]
@jinevening , how do we test this?

**Comment by jinevening** [comment]
@seanshpark I think requantization can tested by comparing the execution result of int8 model (run with TFLite interpreter 2.x) with that of uint8 model (run with TFLite interpreter 1.13).

**Pull request closed without merging**
