### PR TITLE
[tflitefile_tool] Print STRIDED_SLICE's option

### PR DESCRIPTION
**Pull request by chunseoklee**
model_parser prints strided_slice's 5 option fields like :

```
        Output Tensors[45]
                Tensor   45 : buffer 46    |  Empty | FLOAT32 | Memory 24.0K  | Shape [4, 1536] (b'strided_slice_3')
        Options
                begin_mask(5), end_mask(5), ellipsis_mask(0), new_axis_mask(0), shrink_axis_mask(2)
```

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@chunseoklee Please fix format

**Comment by chunseoklee** [comment]
patch file seems weird to me : 

```
diff --git a/tools/tflitefile_tool/option_printer.py b/tools/tflitefile_tool/option_printer.py
index dea805a..f875f35 100755
--- a/tools/tflitefile_tool/option_printer.py
+++ b/tools/tflitefile_tool/option_printer.py
@@ -68,7 +68,7 @@ class OptionPrinter(object):
         elif (self.op_name == "STRIDED_SLICE"):
             return "{}, {}, {}, {}, {}".format(
                 "begin_mask({})".format(self.options.BeginMask()),
-                "end_mask({})".format(self.options.EndMask()),
-                "ellipsis_mask({})".format(self.options.EllipsisMask()),
-                "new_axis_mask({})".format(self.options.NewAxisMask()),
-                "shrink_axis_mask({})".format(self.options.ShrinkAxisMask()))
+                "end_mask({})".format(self.options.EndMask()), "ellipsis_mask({})".format(
+                    self.options.EllipsisMask()), "new_axis_mask({})".format(
+                        self.options.NewAxisMask()), "shrink_axis_mask({})".format(
+                            self.options.ShrinkAxisMask()))
```

**Comment by hseok-oh** [comment]
@YongseopKim PTAL

**Review by YongseopKim — APPROVED** [review]
LGTM

**Pull request merged**
