### PR TITLE
[res] Add a CircleRecipe for GRU

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This pr adds a CircleRecipe for GRU op.

for issue: https://github.com/Samsung/ONE/issues/12320
from draft: https://github.com/Samsung/ONE/pull/12319

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
> [2024-03-19T09:53:27.444Z] terminate called after throwing an instance of 'oops::InternalExn'
[2024-03-19T09:53:27.444Z]   what():  Internal Exception. CircleNodeVisitor: NYI node [/opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug/compiler/luci/lang/include/luci/IR/CircleNodeVisitor.h:57]

> [2024-03-19T09:53:27.700Z] Aborted (core dumped)
[2024-03-19T09:53:27.700Z] compiler/common-artifacts/CMakeFiles/common_artifacts_deps.dir/build.make:22335: recipe for target 'compiler/common-artifacts/GRU_000.opt.circle' failed
[2024-03-19T09:53:27.700Z] make[2]: *** [compiler/common-artifacts/GRU_000.opt.circle] Error 134

**Comment by BalyshevArtem** [comment]
> > [2024-03-19T09:53:27.444Z] terminate called after throwing an instance of 'oops::InternalExn'
> > [2024-03-19T09:53:27.444Z]   what():  Internal Exception. CircleNodeVisitor: NYI node [/opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug/compiler/luci/lang/include/luci/IR/CircleNodeVisitor.h:57]
> 
> > [2024-03-19T09:53:27.700Z] Aborted (core dumped)
> > [2024-03-19T09:53:27.700Z] compiler/common-artifacts/CMakeFiles/common_artifacts_deps.dir/build.make:22335: recipe for target 'compiler/common-artifacts/GRU_000.opt.circle' failed
> > [2024-03-19T09:53:27.700Z] make[2]: *** [compiler/common-artifacts/GRU_000.opt.circle] Error 134

I will rebase this pr, after #12800 will be merged

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
