### PR TITLE
[luci-interpreter] Enable UnidirectionalSequenceLSTM loader

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable UnidirectionalSequenceLSTM Op loader.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #9895 from #9899

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@jinevening ping

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
