### PR TITLE
[onert] Unify ConstantInitializer (cpu-based)

### PR DESCRIPTION
**Pull request by wateret**
Unify ConstantInitializer of cpu-based backends.

ONE-DCO-1.0-Signed-off-by: Hanjoung Lee <hanjoung.lee@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@wateret Is it ready to merge?

**Pull request merged**
