### PR TITLE
[tool/stab] Introduce static backend scheduler

### PR DESCRIPTION
**Pull request by periannath**
- This commit introduces static basckend scheduler (`Stab`)
  - `Stab` is a tool to schedule backend for each opration using profiled data
  - Target nnpackage is executed on remote device using ssh
  - `Stab` uses profiled data to select fastes backend for each operation
  - nnpackage with backend configuration will be created at `./tools/stab/nnpkg_sched`

ONE-DCO-1.0-Signed-off-by: JiHwan Yeo <jihwan.yeo@samsung.com>

---

For issue #5118 
From draft #5110

### CODE REVIEW

**Comment by periannath** [comment]
Please check README.me for its usage. https://github.com/Samsung/ONE/pull/5597/files?short_path=fce73a5#diff-fce73a5c7515a4593cde458a76377944af8d0dab15b5c11b41bb7e0cd6be2f21

I've used `op_list.txt` to specify available operations for each backend. (I can't find a proper way to get available operations)

**Review by wateret — DISMISSED** [review]
LGTM

**Comment by glistening** [comment]
@periannath Did you consider backend switching overhead? I am not sure assignining each op's fastest backend would lead to fastest execution time without considering backend switching overhead especially when it is involved with `acl-cl` or `acl-neon` backend and cpu-base backends.

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by wateret** [comment]
@periannath I will merge this once you're ready :smiley:

**Comment by periannath** [comment]
@glistening In the current status, `Stab` doesn't consider context switching overhead. I'll implement the measurement and use of context switching overhead and push it as another PR later.

I'll add supported backend list at `README.md` to avoid unnecessary confusion.

**Comment by periannath** [comment]
@hseok-oh @wateret @glistening I've added supported backend list at README.md. PTAL.

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Review by wateret — APPROVED** [review]

**Pull request merged**
