### PR TITLE
Draft: Full quantization on runtime (WIP)

### PR DESCRIPTION
**Pull request by hseok-oh**
Call full quantization path on on-device quantization (use #11497)

### CODE REVIEW

**Comment by Torrero** [comment]
@hseok-oh, hello!
I watched your draft, if I understand correctly this draft fully covers the `hidden switching mechanism` for `odc`? Could you clarify, please, are there some uncovered tasks which can be resolved by me?

**Comment by hseok-oh** [comment]
This PR does not cover `hidden switching mechanism`. It requires API calls to quantize and use codegen by user when ready to quantize.

**Comment by Torrero** [comment]
> This PR does not cover `hidden switching mechanism`. It requires API calls to quantize and use codegen by user when ready to quantize.

Can we participate in the implementation of this feature or you plan to implement it?

**Comment by hseok-oh** [comment]
@Torrero I don't have any plan for `hidden switching mechanism` yet. Let's talk about this on different issue.

**Pull request closed without merging**
