### PR TITLE
DRAFT [luci] add broadcast support in Floor Mod operator

### PR DESCRIPTION
**Pull request by binarman**
This adds broadcasting of tensors in floor mod operator

ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>

### CODE REVIEW

**Comment by binarman** [comment]
This fixes shape inference according to tensorflow documentation:

https://www.tensorflow.org/api_docs/python/tf/math/floormod
`Note: math.floormod supports broadcasting. More about broadcasting here`

**Comment by seanshpark** [comment]
Looks good! thank you!

**Comment by seanshpark** [comment]
@binarman , how is this going?

**Comment by binarman** [comment]
@seanshpark 
I didn't forget about this, just switched to other tasks =)

**Comment by seanshpark** [comment]
@binarman , maybe we can close this?

**Comment by seanshpark** [comment]
ping~

**Comment by seanshpark** [comment]
another ping ~

**Comment by binarman** [comment]
I thought was already closed O_o
Everything is merged, thank you!

**Pull request closed without merging**
