### PR TITLE
[luci-interpreter] Implement evalFloat()

### PR DESCRIPTION
**Pull request by seanshpark**
This will fill implementation of evalFloat() method.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #9895 from #9899
- code itself is from TensorFlow lite kernel

**Comment by seanshpark** [comment]
cc @mhs4670go

**Comment by jinevening** [comment]
Could you fix the build warning?

```
/opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp: In function ‘void luci_interpreter::kernels::lstm::{anonymous}::UpdateLstmCellFloat(int, int, float*, const float*, float*, const float*, bool, float)’:
08:50:15 /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp:38:85: error: passing argument 4 to restrict-qualified parameter aliases with argument 2 [-Werror=restrict]
08:50:15    tensor_utils::VectorVectorCwiseProduct(forget_gate, cell_state, n_batch * n_cell, cell_state);
08:50:15                                                        ~~~~~~~~~~                    ^~~~~~~~~~
08:50:15 /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp: In function ‘void luci_interpreter::kernels::lstm::{anonymous}::CalculateLstmOutputFloat(int, int, int, const float*, const float*, TfLiteFusedActivation, const float*, const float*, float, float*, float*)’:
08:50:15 /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp:67:82: error: passing argument 4 to restrict-qualified parameter aliases with argument 2 [-Werror=restrict]
08:50:15    tensor_utils::VectorVectorCwiseProduct(output_gate, scratch, n_batch * n_cell, scratch);
08:50:15                                                        ~~~~~~~                    ^~~~~~~
08:50:15 /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp: In function ‘void luci_interpreter::kernels::lstm::{anonymous}::CalculateLstmGateFloat(const float*, const float*, const float*, const float*, const float*, const float*, const float*, const float*, const float*, const float*, int, int, int, int, int, TfLiteFusedActivation, float*, bool, bool)’:
08:50:15 /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp:145:49: error: passing argument 2 to restrict-qualified parameter aliases with argument 1 [-Werror=restrict]
08:50:15      tensor_utils::MeanStddevNormalization(gate, gate, n_cell, n_batch);
08:50:15                                            ~~~~  ^~~~
08:50:15 /opt/jenkins_agent/workspace/nnfw/master/pr-nncc-debug@2/compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp:151:77: error: passing argument 4 to restrict-qualified parameter aliases with argument 1 [-Werror=restrict]
08:50:15    tensor_utils::ApplyActivationToVector(gate, n_batch * n_cell, activation, gate);
08:50:15                                          ~~~~                                ^~~~
08:50:15 cc1plus: all warnings being treated as errors
```

**Comment by seanshpark** [comment]
> error: passing argument 4 to restrict-qualified parameter aliases with argument 2 [-Werror=restrict]

Strange that this is TF code as-is and also no problem with local build... hum...

**Comment by hseok-oh** [comment]
Maybe TF may not use strict building. (just warning)

**Review by jinevening — APPROVED** [review]

**Pull request merged**
