### PR TITLE
[record-minmax-conversion-test] Add FullyConnected_002 in test list

### PR DESCRIPTION
**Pull request by llFreetimell**
Parent Issue : #2734
Full Draft : #2737

This commit will add `FullyConnected_002` in the test list,
because thie test could not be enable for now.

ONE-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Why do you add the commented test? Are you going to enable it later?

**Comment by llFreetimell** [comment]
@jinevening Is this list only contains passed tests? I added `FullyConnected_002` only because `test.lst` contains `FullyConnected` operation. If I was wrong, I will close this PR :)

**Comment by jinevening** [comment]
> Is this list only contains passed tests?

Yes, `test.lst` only has the whitelist. If #2734 is not related to `record-minmax`, it would be better to close this PR :) Thanks.

**Comment by llFreetimell** [comment]
As the test list only includes passed tests, I will close this PR!

**Pull request closed without merging**
