### PR TITLE
[luci/import] Return reverted commits

### PR DESCRIPTION
**Pull request by m-bronnikov**
This commit returns reverted commits which related with direct-access API introduction.

ONE-DCO-1.0-Signed-off-by: Maksim Bronnikov <max120199@gmail.com>

-------------

Revert for fa8b9434f1bacf8d5928e1f7751cd50c20d8178e and then for c0c216943a795903633241ee70c9e961a611f5cd (to exclude auto-detect related changes)

Related with: #7965 and #7962

### CODE REVIEW

**Comment by m-bronnikov** [comment]
This PR prepared using:

```bash
$ git revert fa8b9434f1bacf8d5928e1f7751cd50c20d8178e c0c216943a795903633241ee70c9e961a611f5cd
```

and fixup of latest commit. Nothing new has been added!

**Comment by m-bronnikov** [comment]
@nnfw-bot test nncc-release

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
