### PR TITLE
[circle-quantizer-dredd-recipe-test] Add tests with multiple-output nodes

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This commit adds test recipes with multiple-outputs nodes

draft: https://github.com/Samsung/ONE/pull/8673
issue: https://github.com/Samsung/ONE/issues/8654

ONE-DCO-1.0-Signed-off-by: Artem Balyshev a.balyshev@partner.samsung.com

### CODE REVIEW

**Comment by BalyshevArtem** [comment]
This pr should be rebased after #8718 will be merged

**Comment by lucenticus** [comment]
LGTM

**Comment by seanshpark** [comment]
close-reopened to trigger testing...

**Review by jinevening — APPROVED** [review]
LGTM Thank you!

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
