### PR TITLE
[luci/pass] Use mio_tflite260

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise luci/pass to use mico_tflite260.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #7616, from draft #7593

**Comment by seanshpark** [comment]
Not a must for now...

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
closing as #7800 posted

**Pull request closed without merging**
