### PR TITLE
[res] pbtxt model and recipe with zero dim

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce pbtxt model and tflite recipe with zero dim value

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
CC @hyunsik-yoon

**Comment by hyunsik-yoon** [comment]
I tried to run the graph in TensorFlow

```python
import tensorflow.compat.v1 as tf
from tensorflow.core.framework import graph_pb2 as gpb
from google.protobuf import text_format as pbtf

model_path = 'const_zero_dim.pbtxt'  # test.pbtxt was renamed

gdef = gpb.GraphDef()

with open(model_path, 'r') as fh:
    graph_str = fh.read()

pbtf.Parse(graph_str, gdef)

tf.import_graph_def(gdef)

graph = tf.get_default_graph()
'''
ops = graph.get_operations()
for op in ops:
    print(op.name)
'''
output = graph.get_tensor_by_name("import/add:0")
input_shape = graph.get_tensor_by_name("import/input_shape:0")

with tf.Session() as sess:
    tf.initialize_all_variables().run()

    print(sess.run(output, feed_dict={input_shape: [1, 0, 8, 64]}))
```

Output:
```
[]
```

**Comment by seanshpark** [comment]
Yes it runs and the output is `[]` :)

**Comment by seanshpark** [comment]
I

**Comment by parjong** [comment]
It looks good to me although I'm unable to understand details ^^;

**Comment by parjong** [comment]
BTW, @seanshpark Is the below change conforms to your intuition behind these testcases?

> (one minor fix I did was that I put dim { size : 0 } as the second dim of zeros const just in case. (currently dim { })

**Comment by parjong** [comment]
(One minor point) This commit updates two resources at once. I'm not against this, but it would be better to make it explicit whether this repo allows such a change or not ;-)

**Comment by seanshpark** [comment]
> Is the below change conforms to your intuition behind these testcases?

I'm not sure... -_-; but I think we may also need to deal with this(`dim { size : 0 }`) too.

**Comment by seanshpark** [comment]
> Two immediate questions pop up in my mind.

Hum.. If we treat `compiler` and `res` same, it is likely we should do with as same.
I'm not strict with `res` but I'll split in two PRs :)

**Comment by seanshpark** [comment]
closed as posted two PRs

**Pull request closed without merging**
