### PR TITLE
[vconone] Bump version to 1.17.0

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit bumps version to 1.17.0.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by jyoungyun** [comment]
The man page of our tools should be updated. After merging #7531, I will update the version string at once.

**Comment by binarman** [comment]
@jyoungyun 
Hi! Could you confirm mentioned PR (7531) is related?

**Comment by jyoungyun** [comment]
@binarman Oh, I'm sorry. I typed the issue number wrong.... I fixed the number. :) Thanks!

**Comment by mhs4670go** [comment]
@seanshpark 
We are going to follow https://github.com/Samsung/ONE/issues/7421#issuecomment-901785804. Please merge this PR.

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
