### PR TITLE
[tools/pareto_profiler] Add preliminary scripts for on-device pareto estimation

### PR DESCRIPTION
**Pull request by dr-venkman**
This commit adds preliminary scripts for pareto estimation, which includes the following:

1. configuration scripts to map backend assignments to pareto decision variables
2. Brute force exploration script to generate lookup data
3. Random sampler -- the simplest available on-device pareto estimator.

This commit is first of a series of subsequent ones that achieve multiobjective optimization for on-device inference tasks.
Kindly review the commit, and let me have your remarks and any specific ideas that you would like to see improved. Thank you in advance.

ONE-DCO-1.0-Signed-off-by: venkat.iyer venkat.iyer@samsung.com

### CODE REVIEW

**Comment by dr-venkman** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-debug

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by hseok-oh** [comment]
cc/ @wateret @chunseoklee

**Review by wateret — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
