### PR TITLE
[onert] Pass optimizer to KernelGenerator

### PR DESCRIPTION
**Pull request by ragmani**
This commits makes KernelGenerator in train backend can use optimizer.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@ragmani Please resolve conflict

**Comment by ragmani** [comment]
Resolved conflict

**Review by glistening — APPROVED** [review]

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
