### PR TITLE
[luci] Revise to use mio-circle08

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This will revise to use mio-circle08.

for issue: https://github.com/Samsung/ONE/issues/12706
from draft: https://github.com/Samsung/ONE/pull/12707

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@nnfw-bot test tizen-gbs

**Comment by seanshpark** [comment]
@BalyshevArtem , please revise after #12730 lands

**Comment by BalyshevArtem** [comment]
> @BalyshevArtem , please rebase after #12730 lands

Done!

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
