### PR TITLE
[luci-value-test] Update README.md

### PR DESCRIPTION
**Pull request by glistening**
Step 1 and Step 2's diagrams are shown in one line.
Now, it will be shown properly in mark-down view.

Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

ONE approval please

### CODE REVIEW

**Comment by glistening** [comment]
Before:

image

After:

image

**Review by jinevening — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
@Samsung/nncc_committers PTAL

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
