### PR TITLE
[pota-value-test] Add more single Op tests

### PR DESCRIPTION
**Pull request by jinevening**
This adds more single Op tests

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
This adds five tests for quantizing a single Op model. See `test.lst` only.

**Comment by seanshpark** [comment]
There are lots of .txt files with all numbers. How did you made these? 
I'd like to know if there can be any way to add a program to generate these instead of adding these files.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
> There are lots of .txt files with all numbers. How did you made these?
I'd like to know if there can be any way to add a program to generate these instead of adding these files.

@seanshpark I generated them using some Python scripts and dalgona. I'll add explanation on how to generate test data in README.

**Pull request merged**
