### PR TITLE
[docs] Update how-to-build-compiler for ARM32

### PR DESCRIPTION
**Pull request by seanshpark**
This will update how-to-build-compiler for ARM32 with python venv.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for https://github.com/Samsung/ONE/issues/12071#issuecomment-1841648762 , from #12206

**Comment by seanshpark** [comment]
@mhs4670go ping~

**Comment by seanshpark** [comment]
@mhs4670go , ping

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
