### PR TITLE
[res] Revise Net_Preactivation_BN_000 tflite recipe

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise Net_Preactivation_BN_000 tflite recipe to accept input
values for value testing.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #5782

**Comment by seanshpark** [comment]
@jinevening ping~

**Comment by seanshpark** [comment]
Comment PR (#5824) landed first :)

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
