### PR TITLE
[onert] Fix wrong shapes in FullyConnectedLayer for training

### PR DESCRIPTION
**Pull request by ragmani**
This commit fixes wrong shapes in FullyConnectedLayer for training.
  - Fixes transposed tensors to have correct shape.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
For #11341

**Comment by ragmani** [comment]
@nnfw-bot test onert-x64-release

**Comment by ragmani** [comment]
@nnfw-bot test onert-x64-release

**Review by glistening — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
