### PR TITLE
[onert/api] Fix : typos and wrong params name

### PR DESCRIPTION
**Pull request by jaemaning**
This PR fixes typos in nnfw.h comment

Related issue: #11404

### CODE REVIEW

**Comment by seanshpark** [comment]
plz follow https://github.com/Samsung/ONE/wiki/ONE-Developer's-Certificate-of-Origin

**Comment by hseok-oh** [comment]
Your commit does not have any message body. Please add commit message body at least 5 word.

**Comment by ragmani** [comment]
You can use our docker image to resolve the "Check PR commit" failure.
```
$ docker run -it --rm -v `pwd`:`pwd` -w `pwd` nnfw/one-devtools:focal ./nnas format
```

**Comment by jaemaning** [comment]
Thank you for review

As instructed, I added text to the commit message body.  :)

**Review by hseok-oh — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
