### PR TITLE
[nnpackage] Add MaxPoolWithArgMax op in circle schema

### PR DESCRIPTION
**Pull request by d-krylov**
Add MaxPoolWithArgMax op in circle schema

ONE-DCO-1.0-Signed-off-by: Denis Krylov <krylovdenism@gmail.com>

### CODE REVIEW

**Comment by chunseoklee** [comment]
Link to any background issue ?

**Comment by seanshpark** [comment]
> Link to any background issue ?

This Op is one of VD request and of SRR MBO. #1928 is one of related issue.

**Comment by d-krylov** [comment]
@nnfw-bot test cross-runtime-test-debug

**Review by lucenticus — APPROVED** [review]
LGTM

**Review by lucenticus — APPROVED** [review]

**Comment by glistening** [comment]
@d-krylov `onert` supports several operators without introducing new operator officially in `circle` schema. For example, we support `StatelessRandomUniform` by letting tflite converter bypass the operator as Custom. Then, `onert` handles this custom operator by providing its kernel. I would like to know the difference between `MaxPoolWithArgMax` and other builtin custom operators. It seems `MaxPoolWithArgmax` exists in tensorflow as https://www.tensorflow.org/api_docs/python/tf/raw_ops/MaxPoolWithArgmax. It seems possible to choose same approach. Does front-end or compiler will do something more than just bypassing the parameter?

**Comment by d-krylov** [comment]
Problem was solved. Look issue #4542.

**Pull request closed without merging**
