### PR TITLE
[luci-interpreter] Rename Reverse -> ReverseV2

### PR DESCRIPTION
**Pull request by SlavikMIPT**
This commit renames Reverse -> ReverseV2 class and .cpp/.h files to support configurable build.

Draft: https://github.com/Samsung/ONE/pull/7304

ONE-DCO-1.0-Signed-off-by: Vyacheslav Bazhenov <slavikmipt@gmail.com>

### CODE REVIEW

**Review by lucenticus — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Review by lucenticus — DISMISSED** [review]
LGTM

**Comment by SlavikMIPT** [comment]
@nnfw-bot test nncc-release

**Comment by SlavikMIPT** [comment]
@nnfw-bot test nncc-debug

**Comment by binarman** [comment]
@SlavikMIPT 
`/opt/jenkins_slave/workspace/nnfw/master/pr-nncc-release@2/compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp:65:10: fatal error: kernels/Reverse.h: No such file or directory
#include <kernels/Reverse.h>`

**Comment by SlavikMIPT** [comment]
@lucenticus @jinevening PTAL

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
