### PR TITLE
Skip copy on NONE activation of FC Hybrid

### PR DESCRIPTION
**Pull request by chunseoklee**
- Skip copy on NONE activation of FC Hybrid

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by glistening** [comment]
@chunseoklee Why don't you do nothing in `ApplyActivationToVector` if activation is none?

**Comment by ragmani** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by ragmani** [comment]
@nnfw-bot test android-runtime-builder

**Comment by periannath** [comment]
@glistening

> As source and target have the same address.
ApplyActivationToVector with FusedActivationFunctionType:kNone
will do nothing but copy to itself unless there's further modification
in ApplyActiviationToVector

Same as https://github.com/Samsung/ONE/pull/3384

**Comment by glistening** [comment]
@periannath 

> @glistening
> 
> > As source and target have the same address.
> > ApplyActivationToVector with FusedActivationFunctionType:kNone
> > will do nothing but copy to itself unless there's further modification
> > in ApplyActiviationToVector
> 
> The same as #3384

I know #3384. It was me who referenced this PR to your issue.
I am asking why this change cannot be handled in `ApplyActivationToVector`.

**Comment by chunseoklee** [comment]
@glistening I will merge this PR and then, refactor both #3384 and this PR

**Pull request merged**
