### PR TITLE
[luci/pass] Use copy_QuantParam

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise to use copy_QuantParam in lang.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #7627, from draft #7627

**Comment by jinevening** [comment]
I guess existing `copy_quantparam` functions should be removed.

**Comment by seanshpark** [comment]
@jinevening , ping

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
