### PR TITLE
[onert/lib_benchmark] Support overall memory measurement

### PR DESCRIPTION
**Pull request by YongseopKim**
Overall memory = memory after running - memory before initing
- To do this, extract some memory measurement functions from
MemoryPoller into MemoryInfo file

ONE-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
for https://github.com/Samsung/ONE/issues/4272

**Comment by YongseopKim** [comment]
PTAL @periannath and @chunseoklee

**Comment by periannath** [comment]
Printing overall memory with other memory stats (RSS, HWM, PSS) may make people confusing.
How about subtract inititial memory from current memory stats (RSS, HWM, PSS)? And print initial memory for whom wants detailed memory info.

**Comment by YongseopKim** [comment]
@periannath That's a good point. I'll apply it.

**Comment by YongseopKim** [comment]
@periannath I thought it again.

> Printing overall memory with other memory stats (RSS, HWM, PSS) may make people confusing.

That's right, but 

> How about subtract inititial memory from current memory stats (RSS, HWM, PSS)?

This could make difference from tflite's way.
- Overall memory = max rss memory(=eventually hwm) after each running - memory before initing

Therefore, I'll fix it as it only prints when users want detailed memory info.

**Comment by YongseopKim** [comment]
Like

```
y2q:/data/local/tmp/ONE $ LD_LIBRARY_PATH=`pwd` ./nnpackage_run /sdcard/mobilenet_v2_1.0_224/ -m1 -w1 -r50
Package Filename /sdcard/mobilenet_v2_1.0_224/
===================================
MODEL_LOAD   takes 12.816 ms
PREPARE      takes 51.842 ms
EXECUTE      takes 292.043 ms
- MEAN     :  292.043 ms
- MAX      :  351.955 ms
- MIN      :  194.439 ms
- GEOMEAN  :  289.659 ms
===================================
RSS
- MODEL_LOAD   takes 21236 kb
- PREPARE      takes 63044 kb
- EXECUTE      takes 75924 kb
- PEAK         takes 75924 kb
===================================
HWM
- MODEL_LOAD   takes 21244 kb
- PREPARE      takes 63044 kb
- EXECUTE      takes 76384 kb
- PEAK         takes 76384 kb
===================================
PSS
- MODEL_LOAD   takes 18996 kb
- PREPARE      takes 68318 kb
- EXECUTE      takes 70377 kb
- PEAK         takes 70377 kb
===================================
Overall Memory: 71256 kb
(HWM after run - HWM before init)
===================================
```

How about this, @periannath ?

**Comment by periannath** [comment]
It looks better, but the word `Overall Memory` is not clear for me. People might think it shows average memory usage. TFLite names it as `Peak memory footprint`.

**TFLite**
> Peak memory footprint (MB): init=3.55078 overall=41.1484

How about using `Overall Peak Memory`? At least any name with `Peak` would be better.

**Comment by YongseopKim** [comment]
> How about using Overall Peak Memory? At least any name with Peak would be better.

Very good. It's much better. I'll fix it soon.

**Review by periannath — DISMISSED** [review]
>How about Used Peak Memroy?

It looks good to me.

**Comment by YongseopKim** [comment]
PTAL @periannath @chunseoklee

**Review by periannath — APPROVED** [review]
LGTM

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
