### PR TITLE
[onert] Introduces a helper function ShapeLoop

### PR DESCRIPTION
**Pull request by ragmani**
For issue #4414
Draft issue #4395 

This commit introduces a helper function ShapeLoop.
  - Introdute ShapeLoop
  - Apply ShapeLoop to IPermuteFunction

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@ragmani Any reason to add `BackendContext.h ` and `ExternalContext.h` in `controlflow` backend?

**Comment by ragmani** [comment]
> @ragmani Any reason to add BackendContext.h and ExternalContext.h in controlflow backend?

@hseok-oh 
Those header files will be used by optimizing "PermuteLayer". It is not related to this PR. So I will divide this PR. Thanks for your pointing out.

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by wateret — APPROVED** [review]
LGTM

**Pull request merged**
