### PR TITLE
[circle-mpqsolver] Add unittests

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit adds unit tests for sources in core and bisection folders.

Related: #11374
ONE-DCO-1.0-Signed-off-by: s.malakhov

### CODE REVIEW

**Comment by stamalakhov** [comment]
@nnfw-bot test nncc-release

**Comment by stamalakhov** [comment]
@jinevening 
Can i split this draft into mergeable PR's?

**Comment by jinevening** [comment]
> Can i split this draft into mergeable PR's?

Yes. There are some duplicate codes, so please remove them before uploading.

**Comment by stamalakhov** [comment]
> > Can i split this draft into mergeable PR's?
> 
> Yes. There are some duplicate codes, so please remove them before uploading.

Ok. Thank you.

**Comment by seanshpark** [comment]
@stamalakhov , I was thinking of unit test with function calls with some hard-coded data...
but it seems you're using HDF5 files... this wasn't expected.
is it not possible with some hard coded data to call target APIs ?

**Comment by seanshpark** [comment]
I've looked into `compiler/circle-mpqsolver/src/core/Evaluator.cpp` file and found that
one important looking method
```
WholeOutput compute_outputs(const luci::Module *module, const std::string &h5file)
```
accepts HDF5 file path... and it's inside anonymous namespace...

from this design, adding unit test like I wrote, provide some hard-coded data, looks impossible.

what I could say is that...
- separate file I/O from data processing
- test data processing in unit tests

**Comment by stamalakhov** [comment]
It's possible only if `DatasetEvaluator` will be extended to receive `raw tensor data` input data, and `BisectionSolver` will be extended to receive raw `DatasetEvaluator`.

**Comment by seanshpark** [comment]
> It's possible only if DatasetEvaluator will be extended to receive raw tensor data input data, and BisectionSolver will be extended to receive raw DatasetEvaluator.

that would be adding APIs that won't be used. I don't expect this is realistic.

**Comment by stamalakhov** [comment]
@jinevening 
Only negative tests can be added for `BisectionSolver` and `Evaluator`.
1. Add them?
2. or m.b. to remove all `hdf5` reading operations from `Evaluator` and rework `BisectionSolver` and `Evaluator` ?
3. or for now there are enough tests?

**Comment by jinevening** [comment]
From http://npuci.mooo.com:8080/job/nnfw/job/master/job/daily-compiler-coverage/656/cobertura/ (10/10 report)

Columns: Files, Classes, Methods, Lines
image

You can add negative tests to increase test coverage. `BisectionSolver.cpp` is not tested at all, so it would be effective to find a way to test it.

It would be better to extract data reader from evaluator, so that we can test evaluator without h5 files. However that will require significant refactoring, so let's leave it as a future work.

**Comment by stamalakhov** [comment]
> You can add negative tests to increase test coverage. `BisectionSolver.cpp` is not tested at all, so it would be effective to find a way to test it.

ok.



> It would be better to extract data reader from evaluator, so that we can test evaluator without h5 files. 

ok.

 Thank you.

**Comment by stamalakhov** [comment]
This one can be closed as new one #11849 is opened.

**Pull request closed without merging**
