### PR TITLE
User can set 'ACL_BUILD_THREADS' for parallel build

### PR DESCRIPTION
**Pull request by cgbahk**
This commit introduces `ACL_BUILD_THREADS`. ACL build will be done by
`ACL_BUILD_THREADS` number of degree of parallelism.

Note that default behavior, without `ACL_BUILD_THREADS` specified, is
conserved.

Signed-off-by: Cheongyo Bahk <cg.bahk@gmail.com>

---
For #2674

### CODE REVIEW

**Comment by hseok-oh** [comment]
```
--- a/Makefile.template
+++ b/Makefile.template
@@ -135,6 +135,7 @@ endif
        NNFW_WORKSPACE="$(WORKSPACE)" NNFW_INSTALL_PREFIX=$(INSTALL_PATH) ./nnfw configure \
                -DCMAKE_BUILD_TYPE=$(BUILD_TYPE_LC) \
                -DNNFW_OVERLAY_DIR=$(OVERLAY_FOLDER) \
+               -DACL_BUILD_THREADS=$(NPROCS) \
                $(OPTIONS)
        touch $(TIMESTAMP_CONFIGURE)
```

It makes CI uses 4-thread build for acl

**Comment by cgbahk** [comment]
@hseok-oh Do you mean you want the patch to be applied to this PR? (I am happy to do that :smile: )

**Comment by cgbahk** [comment]
Oops... I accidently closedㅠㅠ

**Comment by seanshpark** [comment]
@nnfw-bot test x64-builder

**Comment by cgbahk** [comment]
@nnfw-bot test x64-builder

**Comment by hseok-oh** [comment]
@cgbahk Exactly

**Pull request merged**
