### PR TITLE
[debian] Install nnpkg tools

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit installs nnpkg tools.

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
@mhs4670go , please resolve conflict

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
