### PR TITLE
[luci] Remove Add_STR tests

### PR DESCRIPTION
**Pull request by jinevening**
This removes invalid Add_STR tests.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/pull/13750/files#r1730675966
Draft PR: https://github.com/Samsung/ONE/pull/13750

### CODE REVIEW

**Comment by seanshpark** [comment]
As the comment says
```
# This is test for import/export of STRING tensortype
# interpreter or runtime may fail as Add won't support this
``
this is just for STRING tensortype, happen to be using `Add` Op...
we should not remove this.

what test is failing?

**Comment by jinevening** [comment]
PTAL https://github.com/Samsung/ONE/pull/13750/files#r1730675966. STRING inputs are not valid for ADD. Those recipes should have CUSTOM operators.

**Comment by seanshpark** [comment]
> ... Those recipes should have CUSTOM operators.

I've read the comment but I don't know which test fails.
Asking again, which test fail?

**Comment by jinevening** [comment]
> what test is failing?

Circle files for Add_STR are not created under `common-artifacts` after ADD's shape inference logic is updated.

**Comment by jinevening** [comment]
It seems that circle2circle is a problem. `Add_STR_000.opt.circle`  is not created.

**Comment by seanshpark** [comment]
> under common-artifacts after ADD's shape inference logic is updated.

can you add to to exclude.lst  ?

**Comment by seanshpark** [comment]
> tcgenerate(Add_STR_000) # STRING is not supported
tcgenerate(Add_STR_001) # STRING is not supported

um.. already added...

**Comment by jinevening** [comment]
I think tcgenerate is not enough. May need to add `optimize(Add_STR_000)` and `optimize(Add_STR_001)`.

**Comment by seanshpark** [comment]
um... sorry for wrong questions. I was confused with the draft and changes of this PR.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
Anyway recipe itself should not be removed for tflchef.

**Comment by jinevening** [comment]
> Anyway recipe itself should not be removed for tflchef.

I see. With #13754, it will be possible to leave the recipes. But, those recipes generate invalid tflite, so I think it would be better to remove them someday.

**Comment by seanshpark** [comment]
> so I think it would be better to remove them someday.

Yes, they are invalid files but they exist for test creating STRING tensors, nothing more.

**Pull request merged**
