### PR TITLE
[circle2circle] Simplify option settings

### PR DESCRIPTION
**Pull request by seanshpark**
This will simplify option settings with add_switch method.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug
@nnfw-bot test nncc-release

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-debug

**Comment by hseok-oh** [comment]
@nnfw-bot test nncc-release

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
