### PR TITLE
[res/TensorFlowLiteRecipes] Add Logistic_U8_000

### PR DESCRIPTION
**Pull request by underflow101**
Parent Issue: #1880
Fired Issue: #3461 

This commit adds recipes for Logistic_U8_000. (Derived from SOS Mine Project)

Scale & Zero point is set according to [Tensorflow Guide](https://www.tensorflow.org/lite/performance/quantization_spec)
> logistic: {1 / 256.0, -128}

But it seems my `./nncc build` fails with this recipe.

Please review this Work in Progress codes @seanshpark , @jinevening
I'll be happy to get feedback and change to make improvement.

Thank you.

Signed-off-by: underflow101 <ikarus125@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
> But it seems my ./nncc build fails with this recipe.

Can you try with `quant { scale: 0.00390625 zero_point: -128 }` without `min, max` ?

**Comment by seanshpark** [comment]
```
16:56:46 [ 88%] Generate Logistic_U8_000.opt.circle
16:56:47 terminate called after throwing an instance of 'oops::UserExn'
16:56:47   what():  Error: Invalid operator: LOGISTIC
16:56:47 Aborted (core dumped)
```

**Comment by underflow101** [comment]
> > But it seems my ./nncc build fails with this recipe.
> 
> Can you try with `quant { scale: 0.00390625 zero_point: -128 }` without `min, max` ?

`[ 78%] Generate Logistic_U8_000.opt.circle
terminate called after throwing an instance of 'oops::UserExn'
  what():  Error: Invalid operator: LOGISTIC
Aborted (core dumped)
`
Same error occurred after deleting min & max from recipe...

**Comment by jinevening** [comment]
Build failed because luci importer does not support quantized logistic. I'll make a PR to fix that. Please wait.

**Comment by underflow101** [comment]
@jinevening , Thank you for your support!

Meanwhile, I'll work on another u8 ops.

**Comment by jinevening** [comment]
@underflow101 , please rebase to master after #3498 is merged.

**Comment by underflow101** [comment]
> @underflow101 , please rebase to master after #3498 is merged.

Thank you! :)

**Comment by underflow101** [comment]
OMG, I made a horrible mistake.
I made a `git rebase` in a wrong way...

I am truely sorry for this misaction.
I will close this PR and reopen a new one.

**Comment by seanshpark** [comment]
> I am truely sorry for this misaction.

It's OK, You don't have to be sorry :)

**Pull request closed without merging**
