### PR TITLE
[pota-quantization] Add parallel record-minmax test

### PR DESCRIPTION
**Pull request by BalyshevArtem**
This PR adds parallel record-minmax test.

for issue https://github.com/Samsung/ONE/issues/10133
from draft: https://github.com/Samsung/ONE/pull/10132

ONE-DCO-1.0-Signed-off-by: Artem Balyshev <a.balyshev@samsung.com>

### CODE REVIEW

**Review by jinevening — APPROVED** [review]
LGTM

**Review by seanshpark — DISMISSED** [review]
LGTM

**Comment by jinevening** [comment]
@BalyshevArtem  Please fix the issue.

```
17:03:09  The following tests FAILED:
17:03:09  	108 - pota_parallel_record_minmax_test (BAD_COMMAND)
```

**Comment by BalyshevArtem** [comment]
> @BalyshevArtem Please fix the issue.

Done, forgot to do `chmod +x` to .sh file

**Review by jinevening — APPROVED** [review]

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
