### PR TITLE
[tfldump] L2 norm in tfldump

### PR DESCRIPTION
**Pull request by AShedko**
Added L2 norm to tfldump

draft #1432
Signed-off-by: a.shedko sirius.frozen@gmail.com

### CODE REVIEW

**Comment by AShedko** [comment]
@nnfw-bot test signed-off-by

**Comment by struss** [comment]
I think this PR contains modification of two module.(`tfldump` and `circledump`)
We recommend to make one PR per one module modification.

**Comment by seanshpark** [comment]
@binarman , can @bogus-sudo access this repo? 7 days have passed by didn't review this PR...
@AShedko , please resolve conflict. Sorry for the inconvenience.

**Comment by seanshpark** [comment]
@struss , PTAL

**Pull request merged**
