### PR TITLE
[onert] Record subgraph input's minmax

### PR DESCRIPTION
**Pull request by glistening**
It adds subgraph input recording.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

Related: #11517

### CODE REVIEW

**Comment by glistening** [comment]
@nnfw-bot test onert-x64-release

**Comment by glistening** [comment]
@nnfw-bot test onert-x64-release

**Comment by glistening** [comment]
@hseok-oh Do you have any idea about this error?

```
[2023-09-27T08:53:31.313Z] ============================================
[2023-09-27T08:53:31.313Z] ============================================
[2023-09-27T08:53:31.313Z] Completed total 8 set of unittest
[2023-09-27T08:53:31.313Z] Unittest end
[2023-09-27T08:53:31.313Z] ============================================
[2023-09-27T08:53:31.313Z] Test NPUD
script returned exit code 1
```

**Comment by glistening** [comment]
```
$ BACKENDS=cpu MINMAX_FILEPATH=mm.h5 \
Product/x86_64-linux.debug/out/bin/onert_run \
--load input.h5 \
mv2.f32.circle

$ h5dump mm.h5 | grep -A 5 input
               DATASET "input_0" {
                  DATATYPE  H5T_IEEE_F32BE
                  DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
                  DATA {
                  (0): -4.99998, 4.99995
                  }
```

`input.h5` is generated by <sub> gen_golden.py </sub>
```py
elif this_dtype == np.float32:
    input_values.append(
        (10 * np.random.random_sample(this_shape) - 5).astype(np.float32))
```
, which generate input range in `[-5,5]`.

```
$ h5dump input.h5 
```
shows -4.99998.

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
