### PR TITLE
[nnpackage,res] Add RmsNorm op to circle schema

### PR DESCRIPTION
**Pull request by seockho-kim**
To support RmsNorm
- RmsNorm op added to circle schema (nnpackage and res)

issue: https://github.com/Samsung/ONE/issues/13964
draft: https://github.com/Samsung/ONE/pull/13967

ONE-DCO-1.0-Signed-off-by: seockho.kim [seockho.kim@samsung.com](mailto:seockho.kim@samsung.com)

### CODE REVIEW

**Comment by seanshpark** [comment]
@seockho-kim , plz fix your commit message.

**Comment by seockho-kim** [comment]
> @seockho-kim , plz fix your commit message.

Updated the commit message. Thanks :)

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by zetwhite — APPROVED** [review]
LGTM :+1:

**Review by hseok-oh — APPROVED** [review]
LGTM

**Pull request merged**
