### PR TITLE
[circle-operator] Revise multi output tensor

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise multi output tensor to dump first output.
- this is to fix as node is single object
- add todo for if there is other cases

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
related  #9336

**Comment by mhs4670go** [comment]
> this is to fix as node is single object

```cxx
for (const auto output : output_tensors)
```
This for loop seems enough but this case doesn't work with current codes?

**Comment by seanshpark** [comment]
> This for loop seems enough but this case doesn't work with current codes?

When there are multiple outputs, there will be multiple lines of tensor names for one node.
Which I don't think this will correctly work with one-vscode partition editor gui.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
