### PR TITLE
[nnpkg_run] don't warm up by default

### PR DESCRIPTION
**Pull request by glistening**
It restores warm up default value to 0.
Because `nnpackage_run` is running twice by default.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
@glistening can I upload new commit? If the runner takes an option for memory polling, warmup would be set minimally 1.

**Comment by glistening** [comment]
@YongseopKim I will close this issue if you would like to.

**Comment by YongseopKim** [comment]
@glistening No. Don't care about my comment. I will upload another PR for my comment.

**Comment by YongseopKim** [comment]
PTAL @chunseoklee

**Comment by chunseoklee** [comment]
> @glistening can I append new commit? If the runner takes an option for memory polling, warmup would be set minimally 1.

@YongseopKim Please make a PR for this.

**Pull request merged**
