### PR TITLE
[luci-compute] Introduce luci-compute

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce luci-compute for computation kernels.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by jinevening** [comment]
How about renaming the module to `tf-compute` or move `luci-compute` under luci?

**Comment by seanshpark** [comment]
I have plan to use this in _luci-interpreter_ so it would be appropriate to put this in the compile folder. This module won't use ONLY tensorflow kernels but also other computation codes if necessary so I don't want to use `tf` as the prefix.

**Comment by jinevening** [comment]
Thanks for the explanation. I was just curious why it has prefix `luci`, but not placed under `luci`.

**Review by jinevening — APPROVED** [review]

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
