### PR TITLE
[infra] Add rawdata2hdf5 to install preset

### PR DESCRIPTION
**Pull request by seanshpark**
This will add rawdata2hdf5 to install preset of 20200630

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
From draft #4935

**Review by hseok-oh — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
Will be revised after #4942 lands

**Comment by seanshpark** [comment]
@hseok-oh , @jinevening , PTAL again

**Review by hseok-oh — APPROVED** [review]

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
