### PR TITLE
[infra] Message for FlatBuffersConfig

### PR DESCRIPTION
**Pull request by seanshpark**
This will add message for FlatBuffersConfig when skipped.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Um ?
> 13:49:18 [ 32%] Building CXX object compiler/luci/partition/CMakeFiles/luci_partition.dir/src/Nodes/CircleOutputDummy.cpp.o
13:49:18 /usr/bin/ld: /overlay/lib/libflatbuffers.a(util.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-release

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
