### PR TITLE
[onert-micro] This PR adds NotEqual kernel.

### PR DESCRIPTION
**Pull request by Torrero**
This commit adds NotEqual kernel.

Kernels support. Support for the NotEqual kernel for the [issue](https://github.com/Samsung/ONE/issues/12427)
To merge after #13084 

ONE-DCO-1.0-Signed-off-by:  Evgenii Maltsev e.maltsev@samsung.com

### CODE REVIEW

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Comment by BalyshevArtem** [comment]
please rebase

**Review by BalyshevArtem — APPROVED** [review]
LGTM

**Pull request merged**
