### PR TITLE
[CI_TEST] Debug dalgona-test

### PR DESCRIPTION
**Pull request by jinevening**
This is for debugging dalgona-test on CI.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/10287

### CODE REVIEW

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by jinevening** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Pull request closed without merging**
