### PR TITLE
[onert] Update NNFW C API

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
# PR Summary
Commit f444dab7e2de17b7cbcdff39e2d1bc647e3103bc moved the location of the NNFW C API. This PR adjusts sources to changes.

### CODE REVIEW

**Review by glistening — APPROVED** [review]
LGTM

**Comment by chunseoklee** [comment]
@emmanuel-ferdman we need `ONE-DCO-1.0-Signed-off-by:`

**Comment by Torrero** [comment]
LGTM

**Comment by glistening** [comment]
@emmanuel-ferdman Please write commit body.

```
The body of your commit does not satisfy this repository requirements.
The body needs to contain at least 5 words.
```

In addition, could you please update the title of commit? It looks like updating nnfw API itself. But it would be better to clarify it doesn't API itself, but fix the documentation.

**Comment by hseok-oh** [comment]
@emmanuel-ferdman Sorry. I found it is updated by #14289. I'll close this PR.

**Pull request closed without merging**
