### PR TITLE
[loco] Minor doc fix

### PR DESCRIPTION
**Pull request by pfusik**
This corrects a typo and a missing article.

ONE-DCO-1.0-Signed-off-by: Piotr Fusik <p.fusik@samsung.com>

### CODE REVIEW

**Comment by pfusik** [comment]
Splitting #12695 to multiple PRs as requested by @seanshpark

**Comment by seanshpark** [comment]
you've mention `article`.. what is this `article` ?

**Comment by pfusik** [comment]
> you've mention `article`.. what is this `article` ?

https://dictionary.cambridge.org/pl/grammar/british-grammar/a-an-and-the

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
