### PR TITLE
[onert] Refines disabling applied dimension correction

### PR DESCRIPTION
**Pull request by ragmani**
For issue #4244

This commit refines disabling applied dimension correction to prevent bugs by calling set_tensor_shape() of arm_compute::ITensorInfo.
  - Changes the way that disables applied dimension correction from calling set_tensor_shape() to calling set() of arm_compute::TensorShape
  - Unify disabling and enabling applied dimension correction

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by wateret** [comment]
> This commit refines disabling applied dimension correction to prevent bugs by calling set_tensor_shape() of arm_compute::ITensorInfo.

Does that mean it had some bugs in the as-is code? Then could you add some test cases?

**Comment by ragmani** [comment]
> Does that mean it had some bugs in the as-is code? Then could you add some test cases?

I add a test case for it.

**Review by wateret — APPROVED** [review]
LGTM

**Review by hyunsik-yoon — APPROVED** [review]
+0.5

**Comment by wateret** [comment]
@hyunsik-yoon An approval always means +1 😃

 https://github.com/Samsung/ONE/wiki/How-We-Work

**Comment by ragmani** [comment]
Could you merge this?

**Pull request merged**
