### PR TITLE
[TensorFlowPythonExamples] Add minimum-maximum small network

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds minimum-maximum pattern network.

Related : #5599 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
image

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@nnfw-bot test format-checker

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
