### PR TITLE
[luci/pass] Introduce Algorithm:QuantizeWeights

### PR DESCRIPTION
**Pull request by glistening**
It introduces QuantizeWeights algorithm with empty implementation.

ONE-DCO-1.0-Signed-off-by: Sanggyu Lee <sg5.lee@samsung.com>

Related: #11073, #11057

### CODE REVIEW

**Review by jinevening — APPROVED** [review]
LGTM

**Review by hseok-oh — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
Could anyone (who can merge this PR) (maybe @jinevening or @seanpark) merge this?
It is my 1st time to make a PR to Compiler FE. Please let me know if I need more to do.

**Comment by jinevening** [comment]
This PR seems to have no special issue. CC @seanshpark

**Pull request merged**
