### PR TITLE
[luci/import] Add more type on CircleElu validate phase

### PR DESCRIPTION
**Pull request by struss**
This commit will Add more type on CircleElu import validate.

ONE-DCO-1.0-Signed-off-by: KiDeuk Bang <rrstrous@nate.com>

### CODE REVIEW

**Comment by struss** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
FYI

https://www.tensorflow.org/api_docs/python/tf/nn/elu
```
features | A Tensor. Must be one of the following types: half, bfloat16, float32, float64.
```

**Comment by seanshpark** [comment]
I think it would be better to revise commit message: `remove CircleElu Type check`

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Pull request merged**
