### PR TITLE
[infra] Introduce ubuntu 22.04 dev dockerfile

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduces ubuntu 22.04 developer environment dockerfile. It will be used for CI infra environment setting.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by chunseoklee — APPROVED** [review]

**Comment by chunseoklee** [comment]
Q. Anyway, Where will this be used for ?

**Comment by chunseoklee** [comment]
> Q. Anyway, Where will this be used for ?

sefl answer : https://github.com/Samsung/ONE/pull/9973

**Pull request merged**
