### PR TITLE
[luci/tests] Added YUV to RGB to luci tests

### PR DESCRIPTION
**Pull request by AShedko**
Added YUV to RGB to luci tests
Signed-off-by: Andrey Shedko <a.shedko@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Maybe you picked the wrong reviewer :) I have no idea about this PR. Can you remove me from the reviewer list?

**Comment by AShedko** [comment]
Depends on #2184

**Comment by AShedko** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
```
21:58:36 65/77 Test #65: luci_unit_readtest .........................***Failed    1.72 sec
21:58:36 FAILED
21:58:36 - YUV_TO_RGB_U8_000
```
Maybe you need to rebase to master

**Pull request merged**
