### PR TITLE
Update NN_Compiler TCM configuration to exclude base TC set in anlysis

### PR DESCRIPTION
**Pull request by lemmaa**
- Exclude base TC set from TCM in order to bypass the limitation of not
      considering base TC count while generating analysis report.

Signed-off-by: Sung-Jae Lee <sj925.lee@samsung.com>

### CODE REVIEW

**Comment by lemmaa** [comment]
@nnfw-bot test nncc-release

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by lemmaa** [comment]
@nnfw-bot test nncc-debug

**Comment by lemmaa** [comment]
@nnfw-bot test android-runtime-builder

**Comment by lemmaa** [comment]
https://analysishub.sec.samsung.net/service/analyses/540633

Screen Shot 2021-05-20 at 8 26 34 PM

**Pull request merged**
