### PR TITLE
[onert] Replace setting and getting dimension with setShape() and getShape() in ITensor

### PR DESCRIPTION
**Pull request by ragmani**
This commit replaces setting and getting dimension with setShape() and getShape() in ITensor
  - Move setShape() and getShape() into ITensor
  - Remove num_dimensions(size_t rank) and dimension(size_t index, size_t dim)
  - Change using the num_dimensions() and dimension() to using setShape() and getShape()

Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by wateret** [comment]
Well, if we are going to replace `num_dimensions` and `dimensions` with `setShape`, then I would agree. I would prefer to keeping interface classes compact. Or I think it would be better to keep the function as-is and move outside of `ITensor.h`

See also : https://github.com/Samsung/ONE/pull/52#discussion_r411991833

**Comment by ragmani** [comment]
@wateret 
If you would like to keep primitive types in ITensor without "ir::Shape", I will close this PR.

**Comment by wateret** [comment]
@hyunsik-yoon PTAL

**Comment by hyunsik-yoon** [comment]
I also agree with @wateret. ;-)
Having setShape and getShape in ITensor would be OK but
it seems that current `num_dimensions(val)`, etc. is duplicated.
I personally liked `setShape` and `getShape`...
So I once tried to replace `num_dimensions(val)` with `setShape` and `getShape`. However, the code change was too much (all kernels in interpreter uses `num_dimensions(val)` and `dimension(axis)` heavily) so I gave up and wrote `setShape` and `getShape` as separate functions.

**Comment by ragmani** [comment]
@hyunsik-yoon 
> So I once tried to replace num_dimensions(val) with setShape and getShape. However, the code change was too much (all kernels in interpreter uses num_dimensions(val) and dimension(axis) heavily) so I gave up and wrote setShape and getShape as separate functions.

This PR is not replace `num_dimensions(val)` and `dimension(axis)` with `setShape` and `getShape`. They are not virtual method. This PR just moves them into `ITensor`.

**Comment by hyunsik-yoon** [comment]
If we want to add `ITensor::setShape` and `ITensor::getShape`,

case 1) What I like 100%
1) add `setShape` and `getShape`
2) remove `num_dimensions` and `dimension`

case 2)  What I like 50%
1) add `setShape` and `getShape`
2) we keep `num_dimensions` and `dimension`

case 3) I like 70%
- same with case 2) but with some comment on `num_dimensions` and `dimension`, saying, "please use `setShape` and `getShape`, hoping that we will remove `num_dimensions` and `dimension` someday.

I don't want to be too much difficult on this. I am fine with case1) case 2), case 3).

**Comment by ragmani** [comment]
This PR was "case 2)".

**Comment by wateret** [comment]
I'm now even more confused on what we are talking about.

Let me summarize.

1. @hyunsik-yoon wanted to introduce `ITensor::getShape` and `ITensor::setShape`
2. And he wanted to replace `num_dimensions` and `dimension` but there was too many code changes so he introduced `getShape` and `setShape` as helpers(outside ITensor class)
3. Now @ragmani wants `get/setShape` to move in `ITensor`
4. I say, rather than having 3 functions in `ITensors` for shape getter or setter, make `set/getShape` virtual then we can remove the other two

```cpp
class ITensor
{
  virtual void dimension(size_t /* index */, size_t /* dim */);
  virtual void num_dimensions(size_t /*rank*/);
  void setShape(const ir::Shape &);
};
```

vs

```cpp
class ITensor
{
  // virtual void dimension(size_t /* index */, size_t /* dim */)
  // virtual void num_dimensions(size_t /*rank*/)
  virtual void setShape(const ir::Shape &);
};
```

5. So I say if we are going to remove `dimension`/`num_dimensions` then this PR LGTM. Or we should move `get/setShape` to another file as they are helpers.

**Comment by ragmani** [comment]
@wateret 
I think it looks fine to make `set/getShape` virtual then we can remove the other two.

**Comment by wateret** [comment]
@ragmani Are you going to merge this and continue on removing those two methods? Or are you going to make another PR without this? Please let me know if you want this to get merged.

**Comment by ragmani** [comment]
> Are you going to merge this and continue on removing those two methods? Or are you going to make another PR without this? Please let me know if you want this to get merged.

@wateret 
I'm going to change it in this PR.

**Pull request merged**
