### PR TITLE
[onert/cpu] Introduce getBuffer function

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit introduce getBuffer function to get tensor's buffer pointer

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by wateret — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM.

Beyond this PR. But two ideas popped into my head.

1. `getBuffer()` looks good. Then, we may use `getShape()` than `getTensorShape()`.

2. Why do we define the utility functions out of `IPortableTensor`? Why don't we define those in `IPortableTensor`? For example,

```diff
 switch (_output->data_type())
 {
   case OperandType::FLOAT32:
-    nnfw::cker::Fill<float *>(reinterpret_cast<float *>(_value->buffer()),
-                              getTensorShape(_output),
-                              reinterpret_cast<float *>(_output->buffer()));
+    nnfw::cker::Fill<float *>(_value->buffer<float>(), _output->shape(), _output->buffer<float>());
     break;
   case OperandType::INT32:
     nnfw::cker::Fill<int32_t *>(reinterpret_cast<int32_t *>(_value->buffer()),
```

**Comment by hseok-oh** [comment]
>we may use `getShape()` than `getTensorShape()`.

Agree. I also have same idea.

**Comment by hseok-oh** [comment]
>Why don't we define those in `IPortableTensor`? 

It needs more interface change, `IPortableTensor` and related classes, and `ITensor` if need. I'll leave this as issue.

**Comment by glistening** [comment]
@hseok-oh 

I prefer the style of `after` than `before` since it is more readable for me.

```diff
-    nnfw::cker::Fill<float *>(getBuffer<float>(_value), getTensorShape(_output), getBuffer<float>(_output));
+    nnfw::cker::Fill<float *>(_value->buffer<float>(), _output->shape(), _output->buffer<float>());
```

However, it is just a taste of mine. I will not make PR or issue. Thank you for your opinion.

**Pull request merged**
