### PR TITLE
[luci/pass] Add link to flatbuffers-1.10

### PR DESCRIPTION
**Pull request by seanshpark**
This will explictly add link to flatbuffers-1.10.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
From draft #7593

**Comment by mhs4670go** [comment]
@seanshpark luci/pass doesn't have the link in the first place. Does it become to be needed?

**Comment by seanshpark** [comment]
> luci/pass doesn't have the link in the first place. Does it become to be needed?

flatbuffers files was used in some Pass (you can see them previous PR)
but this was implictly OK as with `mio-circle`.
I had some trouble with while upgrading to TF2.6.0: #7688
To overcome this problem (I don't fully understand this) I had to explictly give flatbuffers version.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
