### PR TITLE
[luci] Support quantization of Elu

### PR DESCRIPTION
**Pull request by dayo09**
This commit supports quantization of Elu and verifies.

ONE-DCO-1.0-Signed-off-by: Dayoung Lee <dayoung.lee@samsung.com>

-----

For #6367
Includes #6545 (The commit doesn't contain functional relations, but many merge conflicts are expected.)

### CODE REVIEW

**Comment by dayo09** [comment]
https://www.tensorflow.org/api_docs/python/tf/nn/elu

image

**Comment by dayo09** [comment]
Includes #6545. (The commit doesn't contain functional relations, but many merge conflicts are expected.)

**Comment by dayo09** [comment]
@jinevening @seanshpark Ready :-D

**Comment by jinevening** [comment]
Please remove `err` and `log` file :)

**Review by jinevening — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
