### PR TITLE
[onert] Introduce TrainableBackendContext

### PR DESCRIPTION
**Pull request by ragmani**
This commit introduces TrainableBackendContext.
  - Introduce TrainableContextData
  - Introduce TrainableBackendContext

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
waiting for 10881

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
