### PR TITLE
[debian] Revise postrm script

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit revises postrm script.

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@seanshpark After this PR is landed, Upgrade procedure'd work out okay.

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
FYI, [this document](https://wiki.debian.org/MaintainerScripts) shows how the maintainer scripts work.

When upgrading the package, here's the step of it.
- old.prerm upgrade
- new.preinst upgrade
- Files are unpacked
- old.postrm upgrade # here
- Old files are deleted
- new.postinst upgrade

Before this PR, `postrm` script always removes `/usr/share/one/` folder, which causes the unpacked files to be removed. So, I'll change this not to remove the folder when `upgrade` argument is given to `postrm`.

**Pull request merged**
