### PR TITLE
[luci] Remove duplicate codes for quantization

### PR DESCRIPTION
**Pull request by jinevening**
This removes duplicate codes for quantization

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to [internal issue](https://github.sec.samsung.net/STAR/nnfw/issues/11533)

### CODE REVIEW

**Comment by seanshpark** [comment]
Maybe get a review from @meejeong also?

**Comment by seanshpark** [comment]
For #2753

**Comment by meejeong** [comment]
@jinevening , I changed some codes in ```compute_asym_scale_zp```. (https://github.com/Samsung/ONE/pull/2587)
How about merge previous PR first and make util files?

**Comment by jinevening** [comment]
> @jinevening , I changed some codes in compute_asym_scale_zp. (#2587)
How about merge previous PR first and make util files?

@seanshpark , Can you merge #2587? I will rebase after that.

**Comment by seanshpark** [comment]
> Can you merge #2587? I will rebase after that.

#2587 landed :)

**Pull request merged**
