### PR TITLE
[Compiler FE] build for armv7l on tizen obs

### PR DESCRIPTION
**Pull request by chunseoklee**

### CODE REVIEW

**Comment by hseok-oh** [comment]
@chunseoklee @seanshpark Why don't we use `flatbuffers` latest version (`2.0.0`) for all compiler and runtime modules? Tizen is using `2.0.0` to build both `tensorflow-1.13.1` and `tensorflow-2.7.0`.

**Comment by chunseoklee** [comment]
> @chunseoklee @seanshpark Why don't we use flatbuffers latest version (2.0.0) for all compiler and runtime modules? Tizen is using 2.0.0 to build both tensorflow-1.13.1 and tensorflow-2.7.0

I am not against this. 
compiler side has no problem ?

**Comment by seanshpark** [comment]
> I am not against this.
compiler side has no problem ?

I am also OK. Just didn't do any tests :)

**Comment by seanshpark** [comment]
> Why don't we use flatbuffers latest version (2.0.0) for all compiler and runtime modules? 

If NPU compiler is also OK then we can try with 2.0.0 :)

**Comment by seanshpark** [comment]
Related: #8397

**Comment by ejjeong** [comment]
@chunseoklee Here's the list we discussed offline. (cc/ @hseok-oh)

```
angkor
hermes
hermes-std
loco
locomotiv
locop
logo
logo-core
luci-env
luci-import
luci-lang
luci-log
luci-logex
luci-pass
luci-plan
luci-profile
luci-service
mio-circle
mio-tflite260
oops
pepper-csv2vec
pepper-str
pepper-strcast
pp
```

**Pull request closed without merging**
