### PR TITLE
[SAM] Add comments for exclude list

### PR DESCRIPTION
**Pull request by cgbahk**
This commit adds comment for each exclude file list.

ONE-DCO-1.0-Signed-off-by: Cheongyo Bahk <cg.bahk@gmail.com>

---
For https://github.com/Samsung/ONE/pull/6863#discussion_r635778619

Comment and empty line looks available for this file.

### CODE REVIEW

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-debug

**Comment by mhs4670go** [comment]
@hseok-oh 
> fatal error: error writing to /tmp/cccJGZc3.s: No space left on device

This is happening often recently. Has this ever happened before?

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by chunseoklee — APPROVED** [review]

**Pull request merged**
