### PR TITLE
[onert] Revisit ShapeLoop

### PR DESCRIPTION
**Pull request by ragmani**
This commit eliminates unnecessary code generation by making ShapeLoop simpler.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
This change hasn't been tested for coverage yet.

**Comment by glistening** [comment]
@ragmani I am reading several code to figure out and review this PR. I don't know the purpose of `ShapeLoop` yet. But `Permute` is closely related and https://github.com/Samsung/ONE/blob/master/runtime/onert/core/src/exec/IPermuteFunction.test.cc seems helpful to figure out.

**Comment by glistening** [comment]
(cont'd)

I've searched `ShapeLoop` and found:

- `Permute` is the only use case for `ShapeLoop`.
- `Permute` is not just for permutation (especially for layout conversion). `Permute` does more as taking a look, for example, it converts type also (including quantization) if necessary. As I understand `Permute` is a kind of Reconciling Layer for different type and/or layout.

I don't know what is the expected behavior especially for non-4D tensors. It may take more time to review this PR. Please others approve this change if he/she can review this change.

**Review by glistening — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
@Samsung/one_onert PTAL. I think it is required to get more test function coverage.

**Pull request merged**
