### PR TITLE
[tflchef] Assert filler for sparse with INT4

### PR DESCRIPTION
**Pull request by seanshpark**
This will add assert filler for sparse with INT4 as currently we don't support this.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for  #12717

**Review by jinevening — APPROVED** [review]
LGTM

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Review by Seunghui98 — APPROVED** [review]
LGTM :)

**Pull request merged**
