### PR TITLE
[DRAFT] Compiler FE: Support Ceil Operator

### PR DESCRIPTION
**Pull request by sun-sharma**
Added support for Ceil Operator in Compiler FE. Ref #2045 

ONE-DCO-1.0-Signed-off-by: Sunchit Sharma <sun.sharma@samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
Looks Good, please proceed with posting PRs :)

**Comment by sun-sharma** [comment]
Ok! Thank You :)

**Comment by seanshpark** [comment]
Close?

**Comment by seanshpark** [comment]
Can we close this draft?

**Pull request closed without merging**
