### PR TITLE
[onert] Change SoftMaxGrad test suite name

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit changes SoftMaxGrad test suite name to CKer_Operation.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Comment by jyoungyun** [comment]
onert-x64-release error:

```
[2023-10-31T00:33:45.690Z] [ RUN      ] odc_QuantizeManager.neg_invalid_model_path
[2023-10-31T00:33:45.690Z] Failed to load libonert_odc.so
...
[2023-10-31T00:33:45.694Z] [ RUN      ] GenModelTest.neg_Reshape_with_shape_param_as_const
[2023-10-31T00:33:45.694Z] Error during model prepare : Reshape: 2nd param is not compatible with the shape of input
...
```

I couldn't find the reason for this error. I will retry this build again after checking other build test.

**Comment by jyoungyun** [comment]
@nnfw-bot test onert-x64-release
@nnfw-bot test onert-cross-aarch64-release

**Comment by jyoungyun** [comment]
I will rebase this PR after merged #11829.

**Comment by jyoungyun** [comment]
@nnfw-bot test onert-x64-release

**Comment by jyoungyun** [comment]
@nnfw-bot test onert-cross-debug
@nnfw-bot test onert-cross-release
@nnfw-bot test onert-cross-aarch64-release

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-x64-release

**Comment by hseok-oh** [comment]
@nnfw-bot test onert-cross-aarch64-release onert-cross-release

**Review by glistening — APPROVED** [review]
LGTM. Although CI fails for limit exceeding, it should be okay it is just a fix for a testsuite name.

**Pull request merged**
