### PR TITLE
[npud] Add DBus test code

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit executes Server using child thread and sends a dbus method from main test thread to Server.

ONE-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Comment by jyoungyun** [comment]
@nnfw-bot test cross-aarch64-runtime-test-release
@nnfw-bot test cross-runtime-test-release
@nnfw-bot test cross-runtime-test-debug

**Comment by hseok-oh** [comment]
```
19:17:16  [==========] Running 10 tests from 3 test suites.
19:17:16  [----------] Global test environment set-up.
19:17:16  [----------] 2 tests from DBusTest
19:17:16  [ RUN      ] DBusTest.get_proxy
19:17:16  [       OK ] DBusTest.get_proxy (17 ms)
19:17:16  [ RUN      ] DBusTest.device_get_available_list
23:02:41  Sending interrupt signal to process
23:02:52  Sending interrupt signal to process
23:03:01  After 20s process did not stop
```

**Comment by jyoungyun** [comment]
This code is based on old codes. So it failed some test case. :( I will rebase it.

**Comment by hseok-oh** [comment]
```
18:53:14  [ RUN      ] DBusTest.device_get_available_list
22:37:47  Sending interrupt signal to process
22:37:54  ./infra/scripts/test_ubuntu_runtime_mixed.sh: line 20: 28108 Terminated              Product/out/test/onert-test unittest --unittestdir=Product/out/unittest
22:37:55  script returned exit code 143
```

**Comment by jyoungyun** [comment]
Um,,, to use system dbus in docker container, it needs `--privileged` option and `--volume /run/dbus/system_bus_socket:/run/dbus/system_bus_socket` option.

Current status:
```bash
$ docker run -it --rm -v ${PWD}:/opt/test -w /opt/test ubuntu_glib2.0:18.04 /bin/bash
root@e3ea97be4013:/opt/test# NPUD_LOG_ENABLE=1 DEVICE_MODULE_PATH=${PWD}/Product/x86_64-linux.debug/out/lib ./Product/x86_64-li
[      DBus      ] Starting dbus service
[      main      ] Starting npud
[     Server     ] Starting Server
[   DevManager   ] load modules from /opt/test/Product/x86_64-linux.debug/out/lib
[  DynamicLoader ] Fail to load libnpud_backend_trix.so module: libnpu-engine.so: cannot open shared object file: No such file
[   DevManager   ] Fail to load libnpud_backend_trix.so module
[      DBus      ] org.tizen.npud on name lost, Server will stop.
[     Server     ] Stop Server
[      main      ] Finished npud
[      DBus      ] Stop dbus service
```

With options..
```bash
$ docker run -it --rm --privileged -v /run/dbus/system_bus_sockeket -v ${PWD}:/opt/test -w /opt/test ubuntu_glib2.0:18.04 /bin/bash
root@9e08225d973f:/opt/test# NPUD_LOG_ENABLE=1 DEVICE_MODULE_PATH=${PWD}/Product/x86_64-linux.debug/out/lib ./Product/x86_64-li
[      DBus      ] Starting dbus service
[      main      ] Starting npud
[     Server     ] Starting Server
[   DevManager   ] load modules from /opt/test/Product/x86_64-linux.debug/out/lib
[  DynamicLoader ] Fail to load libnpud_backend_trix.so module: libnpu-engine.so: cannot open shared object file: No such file
[   DevManager   ] Fail to load libnpud_backend_trix.so module
[      DBus      ] org.tizen.npud on bus acquired
[      DBus      ] org.tizen.npud on name acquired
. . .
```

**Comment by ragmani** [comment]
@hseok-oh 
FYI, if you are going to use `--privileged` option to test, you need to change some nodes in jenkins CI such as `x64-ubuntu-02 ` using rootless docker to use root user docker.

**Comment by hseok-oh** [comment]
@ragmani I've already changed x64's setting.

@jyoungyun And as I commented on messanger, test run on host machine without docker. You need to check test on ordoid-xu4 or odroid-n2 machine. You can find machine IP on jenkins node description.

**Comment by jyoungyun** [comment]
@hseok-oh Thank you for your comments!

I finally found the reason why my test case is broken. To fix this issue, it needs some code modification and install the `org.tizen.npud.conf` file in the `/usr/share/dbus/system.d/` directory. Can I install this file in the `test_ubuntu_runtime_mixed.sh` script?

**Comment by hseok-oh** [comment]
> To fix this issue, it needs some code modification and install the `org.tizen.npud.conf` file in the `/usr/share/dbus/system.d/` directory. Can I install this file in the `test_ubuntu_runtime_mixed.sh` script?

You means that we need to install conf file in `/usr/share/dbus/system.d` on each test run, right? Jenkins is not allow to modify file over workspace because of security reason. And this restriction is reasonable. 

Currently, we don't build npud for ubuntu arm32 and arm64. And x64 ubuntu don't run test for npud (and other unittest in {install_dir}/unittest}) yet. We need to find better way for test until enable npud build and test.

**Comment by jyoungyun** [comment]
PTAL :) This code can be merged as it is.

**Comment by ragmani** [comment]
> PTAL :) This code can be merged as it is. 

I didn't understand fully your conversation. So I didn't realize why this code has to be merged quickly. But I'm willing to approve this PR for a quickly merger if someone guarantees.

**Comment by jyoungyun** [comment]
For now, there is no place to run this script in our CI. To run this script, we need to install the dbus config file in your specific system directory. So I will make a new script for preparing and executing the npud_test for CI infra.

The reason why I want to merge this file is that nevertheless, this file is necessary for manual testing. I would like to proceed by adding test cases to the unittest file when a new function is added, even if it has not been executed on CI yet.

I will add several test cases after manual testing.
And I expect this file to run on CI as soon as possible.

**Comment by jyoungyun** [comment]
PTAL

I tested this commit using https://github.com/Samsung/ONE/pull/10179 PR.
It should be executed in Docker image including trix engine.
```
export DOCKER_OPTS="--privileged"
export DOCKER_VOLUMES="-v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket"

# Run npud test
./nnfw docker-run ./infra/scripts/test_ubuntu_npud.sh
Running main() from /home/jyoung-linux/git/npu/ONE/externals/GTEST/googletest/src/gtest_main.cc
[==========] Running 9 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from DBusTest
[ RUN      ] DBusTest.get_proxy
[       OK ] DBusTest.get_proxy (8 ms)
[ RUN      ] DBusTest.device_get_available_list
[       OK ] DBusTest.device_get_available_list (1 ms)
[----------] 2 tests from DBusTest (9 ms total)

[----------] 2 tests from ServerTest
[ RUN      ] ServerTest.run
[       OK ] ServerTest.run (1 ms)
[ RUN      ] ServerTest.stop
[       OK ] ServerTest.stop (4 ms)
[----------] 2 tests from ServerTest (5 ms total)

[----------] 5 tests from SignalTest
[ RUN      ] SignalTest.raise_SIGTERM
[       OK ] SignalTest.raise_SIGTERM (1 ms)
[ RUN      ] SignalTest.raise_SIGINT
[       OK ] SignalTest.raise_SIGINT (1 ms)
[ RUN      ] SignalTest.raise_SIGILL
[       OK ] SignalTest.raise_SIGILL (1 ms)
[ RUN      ] SignalTest.raise_SIGABRT
[       OK ] SignalTest.raise_SIGABRT (1 ms)
[ RUN      ] SignalTest.raise_SIGFPE
[       OK ] SignalTest.raise_SIGFPE (0 ms)
[----------] 5 tests from SignalTest (5 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 3 test suites ran. (20 ms total)
[  PASSED  ] 9 tests.
```

**Review by hseok-oh — APPROVED** [review]
LGTM

**Review by ragmani — APPROVED** [review]
LGTM

**Pull request merged**
