### PR TITLE
[luci] Revise ForwardReshapeToUnaryOpPass test

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise ForwardReshapeToUnaryOpPass with TestIOGraph.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6110, from #6111

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Comment by seanshpark** [comment]
CI build failure depends on #6206

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
