### PR TITLE
[common-artifacts] Revise generation dependency

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise common-artifacts input.h5 dependencies to reduce build
actions for each time of project build.

Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@mhs4670go , I wanted to make build only changed files.
`MOVE` file made the change of dependency every time so there was build actions in every build although there was no change.
If you had some reason for this, please let me know; maybe we can add a comment about it.

**Comment by mhs4670go** [comment]
@seanshpark 
> If you had some reason for this, please let me know; maybe we can add a comment about it.

Well, it is because I didn't want them to be duplicated. Current outputs are like below.
```bash
$ tree Add_000.opt
Add_000.opt
├── Add_000.opt.circle
└── metadata
    ├── MANIFEST
    └── tc
        ├── expected.h5
        └── input.h5
```
But if this PR is applied,
```bash
$ tree Add_000.opt
Add_000.opt.input.h5 // duplicate
Add_000.opt.expected.h5 // duplicate
Add_000.opt
├── Add_000.opt.circle
└── metadata
    ├── MANIFEST
    └── tc
        ├── expected.h5
        └── input.h5
```

I think I can solve this issue without creating duplicates. If I add 'output directory' option to `testDataGenerator`, there's no need to generate them every time, which will solve this issue. I'll post a related issue and make a PR if you don't mind:)

**Comment by seanshpark** [comment]
> I'll post a related issue and make a PR if you don't mind:)

Thanks, please go ahead :)

**Comment by seanshpark** [comment]
Can close this :)

**Pull request closed without merging**
