### PR TITLE
[luci] Test for Square Op

### PR DESCRIPTION
**Pull request by kishcs**
This will enable test for Square Op

Signed-off-by: kishore.cs <kishore.cs@samsung.com>

For #452

### CODE REVIEW

**Comment by kishcs** [comment]
@mhs4670go 
In my case, Signed-off message is already there, so it will not add DCO signed off message as per the below code given in [here](https://github.com/Samsung/ONE/wiki/ONE-Developer%27s-Certificate-of-Origin).

> #!/usr/bin/env bash
> COMMIT_MSG_FILE=$1`
> NAME=$(git config user.name)
> EMAIL=$(git config user.email)
> 
> if ! grep "Signed-off-by:" ${COMMIT_MSG_FILE}; then
>   echo -e "\n\nONE-DCO-1.0-Signed-off-by: $NAME <$EMAIL>" >> ${COMMIT_MSG_FILE}
> fi

**Comment by kishcs** [comment]
@mhs4670go
I updated the bash script with an `else` part. How to update the Wiki page?

**Comment by seanshpark** [comment]
> How to update the Wiki page?

@lemmaa PTAL

**Comment by lemmaa** [comment]
> > How to update the Wiki page?
> 
> @lemmaa PTAL

@seanshpark , @kishcs , good opinion. There is no reason not to fix it.

However, in fact, it is doubtful whether I should obey this rule. Isn't just signed-off enough? I'll check this part separately. :)

**Pull request merged**
