### PR TITLE
[circle-opselector] Set proper output

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit fixes the bug to make it set valid output.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@mhs4670go , can you please add a comment about the actual problem or a link to some issue?

**Comment by mhs4670go** [comment]
> @mhs4670go , can you please add a comment about the actual problem or a link to some issue?

In a nutshell, there was a problem where the output shapes were set.

This bug had not been found because the circle exporter runs shape inference before graph export.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
for the record;
- if the node was used as an input to multiple nodes, output was created that much but actually only one for the node was necessary
- there was a typo in variable name that node was set instead of setting the shape
  - fixed code: `output_shape->dim(i).set(circle_output->dim(i).value());`

**Comment by mhs4670go** [comment]
@nnfw-bot test nncc-jammy-debug

**Comment by seanshpark** [comment]
@nnfw-bot test nncc-jammy-debug

**Pull request merged**
