### PR TITLE
[circle2circle-dredd-recipe-test] Add CircleRecipes

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit extends repo coverage to add test in CircleRecipes

ONE-DCO-1.0-ONE-DCO-1.0-ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@hseok-oh, can you please take a look?

**Comment by hseok-oh** [comment]
@mhs4670go Please update `infra/scripts/configure_compiler_coverage.sh` by adding `circle2circle-dredd-recipe-test` in `DEBUG_BUILD_ITEMS`.

**Comment by mhs4670go** [comment]
@hseok-oh I don't know what needs to be added to `configure_compiler_coverage.sh`. I mean, there are some modules that doesn't exist in `DEBUG_BUILD_ITEMS` yet. All our active compiler module should be added to there?

**Comment by seanshpark** [comment]
It would be better to add items(compiler modules) to `configure_compiler_coverage.sh` when existing items in `configure_compiler_coverage.sh` becomes depend on new module, or new test module is added that may widen coverage.

**Comment by hseok-oh** [comment]
>there are some modules that doesn't exist in DEBUG_BUILD_ITEMS yet. All our active compiler module should be added to there

Module for release (modules used in `preset`) and related test modules

**Comment by mhs4670go** [comment]
@seanshpark Is it okay to add below list?
```
circle2circle-dredd-recipe-test
record-minmax-conversion-test
tf2tfliteV2
tf2tfliteV2-conversion-test
tflite2circle-conversion-test
```

**Comment by seanshpark** [comment]
> @seanshpark Is it okay to add below list?

Let's put them in another PR... :)

**Pull request merged**
