### PR TITLE
Release note 1.24.0

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit is a release note for 1.24.0.

Related: #11085 
ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by mhs4670go** [comment]
This commit should be merged after #11095.

**Comment by seanshpark** [comment]
Title is 1.23.0 ... maybe typo?

**Comment by mhs4670go** [comment]
> Title is 1.23.0 ... maybe typo?

Oh,,Thanks!!

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
