### PR TITLE
[luci/test] Support HardSwish operation

### PR DESCRIPTION
**Pull request by shs-park**
Support HardSwish operation in luci tests

ONE-DCO-1.0-Signed-off-by: Seungho Henry Park <shs.park@samsung.com>

---

Related to: #10930 
Draft PR: #10985

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
Need to fix error
```
[2023-08-01T06:05:14.757Z]  91/121 Test  #91: luci_unit_readtest .........................***Failed    1.31 sec
[2023-08-01T06:05:14.757Z] FAILED
[2023-08-01T06:05:14.757Z] - HardSwish_000
[2023-08-01T06:05:14.757Z] 
[2023-08-01T06:05:14.757Z]         Start  92: luci_unit_writetest
[2023-08-01T06:05:16.112Z]  92/121 Test  #92: luci_unit_writetest ........................***Failed    1.35 sec
[2023-08-01T06:05:16.112Z] FAILED
[2023-08-01T06:05:16.112Z] - HardSwish_000
```

**Comment by seanshpark** [comment]
Maybe depends on #11196 ... plz rebase.

**Comment by shs-park** [comment]
I did rebase and forced push.
=)

**Comment by shs-park** [comment]
@nnfw-bot test nncc-jammy-debug

**Pull request merged**
