### PR TITLE
[record-minmax] Add profile option

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit adds `generate_profile_data` option to record-minmax.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
CC @jinevening

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
