### PR TITLE
[infra] Move git ignore for each project

### PR DESCRIPTION
**Pull request by hseok-oh**
This commit moves git ignore condition for each project into each project's directory.

ONE-DCO-1.0-Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Review by ys44kim — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@chunseoklee Please add @ys44kim to @samsung/one_onert team

**Comment by ys44kim** [comment]
> @chunseoklee Please add @ys44kim to @Samsung/one_onert team

thanks !! 😊

**Review by zetwhite — APPROVED** [review]
LGTM 👍 
Wow, I didn't know that repo contains multiple .gitignore files.

**Pull request merged**
