### PR TITLE
[tools/model_explorer_circle] Add __init__.py for packaging

### PR DESCRIPTION
**Pull request by batcheu**
It adds `__init__.py` to help making a package of circle adapter.

### CODE REVIEW

**Review by ys44kim — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
- for #14307

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by zetwhite — APPROVED** [review]

**Comment by seanshpark** [comment]
@ys44kim PTAL

**Review by ys44kim — APPROVED** [review]

**Pull request merged**
