### PR TITLE
[compiler/ahub] Remove stdex

### PR DESCRIPTION
**Pull request by seanshpark**
This will remove stdex item as not used anymore.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #6055

**Review by lemmaa — APPROVED** [review]
LGTM!

**Comment by lemmaa** [comment]
So, will we remove `./stdex` and the files below it from the next PR?

**Comment by seanshpark** [comment]
> So, will we remove ./stdex and the files below it from the next PR?

I'll remove `stdex` folder itself after our internal compiler backend is safe without this module.

**Pull request merged**
