### PR TITLE
[pota-value-test] Add CWQ PRelu tests

### PR DESCRIPTION
**Pull request by jinevening**
This adds tests for CWQ PRelu

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: #5121
Draft PR: #5119

### CODE REVIEW

**Comment by jinevening** [comment]
To reviewers: This adds two tests (uint8 cwq, int16 cwq) for PRelu Op.

**Comment by mhs4670go** [comment]
Maybe some values are modified rather than added. Is it right?

**Comment by jinevening** [comment]
> Maybe some values are modified rather than added. Is it right?

Yes, I've updated the data for int16 cwq as cwq algorithm for PRelu has changed. The test was disabled in https://github.com/Samsung/ONE/pull/5122 and enabled in this PR.

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
