### PR TITLE
[onert] Fix runtime coverage test bug

### PR DESCRIPTION
**Pull request by hseok-oh**
Unzip tar file before check test is prepared

Signed-off-by: Hyeongseok Oh <hseok82.oh@samsung.com>

### CODE REVIEW

**Comment by hseok-oh** [comment]
It will fix runtime coverage test fail

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-debug

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by hseok-oh** [comment]
@nnfw-bot test cross-runtime-test-debug

**Pull request merged**
