### PR TITLE
[circle-mpqsolver] Revisit logging

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit revisits logging to provide human-readable log of 'circle-mpqsolver' run.
Setting LUCI_LOG to 1 provides the following output of run:
```
Searching mixed precision configuration for /home/stanislav/repos/WorkSpaces/mobile_net_v1/model.recorded.circle
using /mnt/storage/datasets/ms_coco/dataset_MB_v1_3.h5
with input dtype set to uint8 and output dtype set to uint8
Front nodes will be quantized according to 'auto' algorithm 
Parameterizing /home/stanislav/repos/WorkSpaces/mobile_net_v1/model.recorded.circle by distance from inputs (depth)
Computing quantization errors...
Full int16 model quantization error 7.68947e-05
Full uint8 model quantization error 0.000291691
Target quantization error 9.83743e-05
Q16 will be set at input due to 
152628 error at input vs 
50324.6 error at output.
Looking for the optimal configuration inside [0 , 32] depth segment
Computing quantization error at depth of 16
Quantization error at depth of 16 is 9.1736e-05
so it's better to constrain search segment to [0 , 16]
Looking for the optimal configuration inside [0 , 16] depth segment
Computing quantization error at depth of 8
Quantization error at depth of 8 is 0.000132586
so it's better to constrain search segment to [8 , 16]
Looking for the optimal configuration inside [8 , 16] depth segment
Computing quantization error at depth of 12
Quantization error at depth of 12 is 0.000103023
so it's better to constrain search segment to [12 , 16]
Looking for the optimal configuration inside [12 , 16] depth segment
Computing quantization error at depth of 14
Quantization error at depth of 14 is 8.56753e-05
so it's better to constrain search segment to [12 , 14]
Looking for the optimal configuration inside [12 , 14] depth segment
Computing quantization error at depth of 13
Quantization error at depth of 13 is 0.000108196
so it's better to constrain search segment to [13 , 14]
Bisection converged
Found the best configuration at depth of 14
Saving output model to /home/stanislav/repos/WorkSpaces/mobile_net_v1/model.q_opt.circle
```

Please note: intermediate results will be provided in another draft.

Related: #10612
ONE-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Overall looks good to me, but it seems a little bit verbose. Could you update them similarly to the below?

```
>> Searching mixed precision configuration
model: /home/stanislav/repos/WorkSpaces/mobile_net_v1/model.recorded.circle
dataset: /mnt/storage/datasets/ms_coco/dataset_MB_v1_3.h5
input dtype: uint8
output dtype: uint8
algorithm: bisection (auto)
qerror metric: MSE
target qerror: 9.83743e-05

>> Computing baseline qerrors
Full int16 model quantization error: 7.68947e-05
Full uint8 model quantization error: 0.000291691

>> Running bisection(auto) algorithm
Qerror of front half: 152628 
Qerror of rear half: 50324.6
Front part will be Q16, while ther rear will be Q8

Looking for the optimal configuration in [0 , 32] depth segment
Qerror at depth 16 is 9.1736e-05 < target qerror (9.83743e-05)
Looking for the optimal configuration in [0 , 16] depth segment
Qerror at depth 8 is 0.000132586 > target qerror (9.83743e-05)
...
Found the best bisection point at depth 14
Saving output model to XXX.
```

**Comment by stamalakhov** [comment]
> Overall looks good to me, but it seems a little bit verbose. Could you update them similarly to the below?

Ok. Thank you.

**Comment by jinevening** [comment]
Looks good to me. Thanks.

**Comment by stamalakhov** [comment]
> Looks good to me. Thanks.

@jinevening 
do i need to split it?

**Comment by jinevening** [comment]
No, let's turn it non draft.

**Review by jinevening — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]

**Pull request merged**
