### PR TITLE
[record-minmax] Generate positive random int

### PR DESCRIPTION
**Pull request by jinevening**
This generates positive random int for indices.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
Some Ops (ex: Gather) accepts positive indices only. Generating positive int would be helpful to easily quantize those models.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
Q) for other nodes that work with negative values, is it OK with testing?

**Comment by jinevening** [comment]
Random int generation in record-minmax was introduced quite recently. AFAIK, there is no test that uses negative int yet.

In the long term, it would be better to distinguish (1) inputs that accept only positive int (indices) from (2) inputs that accept both negative/positive int (ex: axis) for wide range of testing.

**Review by m-bronnikov — APPROVED** [review]
LGTM

**Pull request merged**
