### PR TITLE
Use version 1.6.1

### PR DESCRIPTION
**Pull request by chunseoklee**
update version related files to use 1.6.1

ONE-DCO-1.0-Signed-off-by: Chunseok Lee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by ragmani** [comment]
@nnfw-bot test nncc-debug

**Comment by ragmani** [comment]
@nnfw-bot test nncc-release

**Comment by ragmani** [comment]
@nnfw-bot test nncc-release

**Comment by chunseoklee** [comment]
@Samsung/nnfw PTAL

**Pull request merged**
