### PR TITLE
[luci] Extract QuantizeWeights from QuantizeWithMinMax

### PR DESCRIPTION
**Pull request by jinevening**
This extracts QuantizeWeights from QuantizeWithMinMax.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

---
Related to: https://github.com/Samsung/ONE/issues/8524

### CODE REVIEW

**Comment by jinevening** [comment]
To reviewers:

This is just relocation of codes to allow `QuantizeWeights` to be used in other sources.

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
I've rebased the PR to resolve merge conflict.

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
