### PR TITLE
[luci-interpreter] Allow LogSoftmax ops for KernelBuilder

### PR DESCRIPTION
**Pull request by underflow101**
Related PR: #4018 
Fired Issue: #4097 

Added LogSoftmax kernel op for following source codes:
	- KernelBuilder.h
	- KernelBuilder.cpp
	- KernelBuilder.test.cpp

This commit have been tested on my PC.

Please review this PR, @seanshpark @jinevening .
I'll be happy to get feedback and change to make improvement.

Thank you.

(Derived from SOS Mine Project)

Signed-off-by: underflow101 <ikarus125@gmail.com>

### CODE REVIEW

**Comment by underflow101** [comment]
@nnfw-bot test nncc-debug

**Comment by underflow101** [comment]
@nnfw-bot test nncc-release

**Comment by underflow101** [comment]
@nnfw-bot test nncc-debug

**Comment by underflow101** [comment]
@nnfw-bot test nncc-debug

**Review by jinevening — APPROVED** [review]
LGTM

**Review by struss — APPROVED** [review]
LGTM

**Review by s-barannikov — APPROVED** [review]

**Pull request merged**
