### PR TITLE
[luci-interpreter] Support bool type in NotEqual and ReduceMax op

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit supports bool type in NotEqual and ReduceMax op.

ONE-DCO-1.0-Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@mhs4670go , can you add some unit tests for new codes?
- in another PR is also OK
- and test for previous StridedSlice too

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by Seunghui98 — APPROVED** [review]
LGTM!

**Comment by mhs4670go** [comment]
@seanshpark 
Good point. I'll add those tests in the next PR.

**Pull request merged**
