### PR TITLE
[luci] Fix bug in ConvertNCHWToNHWCPass

### PR DESCRIPTION
**Pull request by jinevening**
This clones a constant when expanding it to rank 4.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
To reviewer:

Previous code did in-place update, which causes a problem when the updated node is used by multiple operators.

This PR copies the target node before update, so that the change is only applied to the specific operator.

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
Is it possible to add a recipe for regression test with dredd test?

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
