### PR TITLE
[luci-compute] Introduce tflite_shape

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce tflite_shape to convert shape.

ONE-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #12100 , from  #12099

**Comment by jinevening** [comment]
Convert.h/cpp seems too general. How about renaming into `ConvertShape`?

**Comment by seanshpark** [comment]
> How about renaming into ConvertShape?

There will be convert also for `PaddingType`, `FullyConnectedWeightsFormat`

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
