### PR TITLE
[debian] install luci-eval-driver

### PR DESCRIPTION
**Pull request by mhs4670go**
This commit installs luci-eval-driver.

Signed-off-by: seongwoo <mhs4670go@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Comment by seanshpark** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by seanshpark** [comment]
@nnfw-bot test cross-runtime-test-release

**Comment by seanshpark** [comment]
```
14:21:39  [GitHub Checks] Trying to resolve checks parameters from Git SCM...
14:21:39  [GitHub Checks] No GitHub app credentials found: 'nnfw.bot'
14:21:39  [GitHub Checks] See: https://github.com/jenkinsci/github-branch-source-plugin/blob/master/docs/github-app.adoc
14:21:39  [GitHub Checks] Job does not have valid credentials
```

Um?

**Comment by seanshpark** [comment]
@hseok-oh could you pleas take a look?

**Comment by mhs4670go** [comment]
@nnfw-bot test cross-runtime-test-debug

**Pull request merged**
