### PR TITLE
[tools/model2nnpkg] Fix incorrectly generating metadata

### PR DESCRIPTION
**Pull request by ragmani**
This commits fixes incorrectly generating metadata.

ONE-DCO-1.0-Signed-off-by: ragmani <ragmani0216@gmail.com>

### CODE REVIEW

**Comment by ragmani** [comment]
- before
```json
{
  "major-version": "1",
  "minor-version": "2",
  "patch-version": "0",
  "configs": [
    ""
  ],
  "models": [
    "m1.tflite",
    "m2.tflite"
  ],
  "model-types": [
    "tflite",
    "tflite"
  ],
  "pkg-inputs": [
    "0:0:81"
  ],
  "pkg-outputs": [
    "1:0:7"
  ],
  "model-connect": {
    "0:0:0": [
      "1:0:0"
    ]
  }
}
```

- after
```json
{
  "major-version": "1",
  "minor-version": "2",
  "patch-version": "0",
  "configs": [
    ""
  ],
  "models": [
    "m1.tflite",
    "m2.tflite"
  ],
  "model-types": [
    "tflite",
    "tflite"
  ],
  "pkg-inputs": [
    "0:0:0"
  ],
  "pkg-outputs": [
    "1:0:0"
  ],
  "model-connect": [
    {
      "from": "0:0:0",
      "to": [
        "1:0:0"
      ]
    }
  ]
}
```

- test
```
BACKENDS=cpu /usr/bin/nnfw-test/Product/out/bin/onert_run mv1
Package Filename mv1
0:0:0 -> 1:0:0
===================================
MODEL_LOAD   takes 105.706 ms
PREPARE      takes 204.295 ms
EXECUTE      takes 195.359 ms
- MEAN     :  195.359 ms
- MAX      :  195.359 ms
- MIN      :  195.359 ms
- GEOMEAN  :  195.359 ms
===================================
```

**Review by hseok-oh — APPROVED** [review]

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by SlavikMIPT — APPROVED** [review]
LGTM

**Review by glistening — APPROVED** [review]
LGTM

**Pull request merged**
