### PR TITLE
[circle-eval-diff] Fix input data size

### PR DESCRIPTION
**Pull request by jinevening**
This fixes byte size of directory input.

ONE-DCO-1.0-Signed-off-by: Hyukjin Jeong <hj1.jeong@samsung.com>

### CODE REVIEW

**Comment by jinevening** [comment]
We'll need tests for this kind of bug 😭

**Comment by mhs4670go** [comment]
Could you change the codes like below?
```cxx
std::vector<size_t> getEachByteSizeOf(const std::vector<loco::Node *> &nodes)
{
  std::vector<size_t> vec;
  for (const auto node : nodes)
  {
    const auto input_node = loco::must_cast<const luci::CircleInput *>(node);
    size_t element_size = 1;

    for (uint32_t index = 0; index < input_node->rank(); index++)
    {
      element_size *= input_node->dim(index).value();
    }
    vec.push_back(element_size * loco::size(input_node->dtype())); // note here
  }
  return vec;
}
```

**Comment by mhs4670go** [comment]
> 

Well, yeah.. Even though I've added https://github.com/Samsung/ONE/pull/9273, it seems not enough.

**Comment by jinevening** [comment]
@mhs4670go I make a const variable for `loco::size(input_node->dtype())` for readability. PTAL :)

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
